// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: favor/favor.proto

package favor

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FavorService_GetInfo_FullMethodName       = "/favor.FavorService/GetInfo"
	FavorService_GetItem_FullMethodName       = "/favor.FavorService/GetItem"
	FavorService_BatchGetItems_FullMethodName = "/favor.FavorService/BatchGetItems"
	FavorService_Delete_FullMethodName        = "/favor.FavorService/Delete"
	FavorService_BatchDelete_FullMethodName   = "/favor.FavorService/BatchDelete"
	FavorService_Sync_FullMethodName          = "/favor.FavorService/Sync"
)

// FavorServiceClient is the client API for FavorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// FavorService 收藏服务
type FavorServiceClient interface {
	// GetInfo 获取收藏容量信息
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// GetItem 获取收藏项详情
	GetItem(ctx context.Context, in *GetFavItemRequest, opts ...grpc.CallOption) (*GetFavItemResponse, error)
	// BatchGetItems 批量获取收藏项
	BatchGetItems(ctx context.Context, in *BatchGetFavItemsRequest, opts ...grpc.CallOption) (*BatchGetFavItemsResponse, error)
	// Delete 删除收藏项
	Delete(ctx context.Context, in *DeleteFavItemRequest, opts ...grpc.CallOption) (*DeleteFavItemResponse, error)
	// BatchDelete 批量删除收藏项
	BatchDelete(ctx context.Context, in *BatchDeleteFavItemsRequest, opts ...grpc.CallOption) (*BatchDeleteFavItemsResponse, error)
	// Sync 同步收藏列表
	Sync(ctx context.Context, in *SyncFavorRequest, opts ...grpc.CallOption) (*SyncFavorResponse, error)
}

type favorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFavorServiceClient(cc grpc.ClientConnInterface) FavorServiceClient {
	return &favorServiceClient{cc}
}

func (c *favorServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, FavorService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favorServiceClient) GetItem(ctx context.Context, in *GetFavItemRequest, opts ...grpc.CallOption) (*GetFavItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFavItemResponse)
	err := c.cc.Invoke(ctx, FavorService_GetItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favorServiceClient) BatchGetItems(ctx context.Context, in *BatchGetFavItemsRequest, opts ...grpc.CallOption) (*BatchGetFavItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchGetFavItemsResponse)
	err := c.cc.Invoke(ctx, FavorService_BatchGetItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favorServiceClient) Delete(ctx context.Context, in *DeleteFavItemRequest, opts ...grpc.CallOption) (*DeleteFavItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFavItemResponse)
	err := c.cc.Invoke(ctx, FavorService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favorServiceClient) BatchDelete(ctx context.Context, in *BatchDeleteFavItemsRequest, opts ...grpc.CallOption) (*BatchDeleteFavItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDeleteFavItemsResponse)
	err := c.cc.Invoke(ctx, FavorService_BatchDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *favorServiceClient) Sync(ctx context.Context, in *SyncFavorRequest, opts ...grpc.CallOption) (*SyncFavorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncFavorResponse)
	err := c.cc.Invoke(ctx, FavorService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FavorServiceServer is the server API for FavorService service.
// All implementations must embed UnimplementedFavorServiceServer
// for forward compatibility.
//
// FavorService 收藏服务
type FavorServiceServer interface {
	// GetInfo 获取收藏容量信息
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// GetItem 获取收藏项详情
	GetItem(context.Context, *GetFavItemRequest) (*GetFavItemResponse, error)
	// BatchGetItems 批量获取收藏项
	BatchGetItems(context.Context, *BatchGetFavItemsRequest) (*BatchGetFavItemsResponse, error)
	// Delete 删除收藏项
	Delete(context.Context, *DeleteFavItemRequest) (*DeleteFavItemResponse, error)
	// BatchDelete 批量删除收藏项
	BatchDelete(context.Context, *BatchDeleteFavItemsRequest) (*BatchDeleteFavItemsResponse, error)
	// Sync 同步收藏列表
	Sync(context.Context, *SyncFavorRequest) (*SyncFavorResponse, error)
	mustEmbedUnimplementedFavorServiceServer()
}

// UnimplementedFavorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFavorServiceServer struct{}

func (UnimplementedFavorServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedFavorServiceServer) GetItem(context.Context, *GetFavItemRequest) (*GetFavItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (UnimplementedFavorServiceServer) BatchGetItems(context.Context, *BatchGetFavItemsRequest) (*BatchGetFavItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetItems not implemented")
}
func (UnimplementedFavorServiceServer) Delete(context.Context, *DeleteFavItemRequest) (*DeleteFavItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedFavorServiceServer) BatchDelete(context.Context, *BatchDeleteFavItemsRequest) (*BatchDeleteFavItemsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDelete not implemented")
}
func (UnimplementedFavorServiceServer) Sync(context.Context, *SyncFavorRequest) (*SyncFavorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedFavorServiceServer) mustEmbedUnimplementedFavorServiceServer() {}
func (UnimplementedFavorServiceServer) testEmbeddedByValue()                      {}

// UnsafeFavorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FavorServiceServer will
// result in compilation errors.
type UnsafeFavorServiceServer interface {
	mustEmbedUnimplementedFavorServiceServer()
}

func RegisterFavorServiceServer(s grpc.ServiceRegistrar, srv FavorServiceServer) {
	// If the following call pancis, it indicates UnimplementedFavorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FavorService_ServiceDesc, srv)
}

func _FavorService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavorServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavorService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavorServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavorService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFavItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavorServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavorService_GetItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavorServiceServer).GetItem(ctx, req.(*GetFavItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavorService_BatchGetItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetFavItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavorServiceServer).BatchGetItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavorService_BatchGetItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavorServiceServer).BatchGetItems(ctx, req.(*BatchGetFavItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavorService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFavItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavorServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavorService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavorServiceServer).Delete(ctx, req.(*DeleteFavItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavorService_BatchDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteFavItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavorServiceServer).BatchDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavorService_BatchDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavorServiceServer).BatchDelete(ctx, req.(*BatchDeleteFavItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FavorService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncFavorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FavorServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FavorService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FavorServiceServer).Sync(ctx, req.(*SyncFavorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FavorService_ServiceDesc is the grpc.ServiceDesc for FavorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FavorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "favor.FavorService",
	HandlerType: (*FavorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _FavorService_GetInfo_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _FavorService_GetItem_Handler,
		},
		{
			MethodName: "BatchGetItems",
			Handler:    _FavorService_BatchGetItems_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _FavorService_Delete_Handler,
		},
		{
			MethodName: "BatchDelete",
			Handler:    _FavorService_BatchDelete_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _FavorService_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "favor/favor.proto",
}
