// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: miniapp/miniapp.proto

package miniapp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MiniAppService_JSLogin_FullMethodName           = "/miniapp.MiniAppService/JSLogin"
	MiniAppService_QrcodeAuthLogin_FullMethodName   = "/miniapp.MiniAppService/QrcodeAuthLogin"
	MiniAppService_GetRuntimeSession_FullMethodName = "/miniapp.MiniAppService/GetRuntimeSession"
	MiniAppService_GetSessionQRCode_FullMethodName  = "/miniapp.MiniAppService/GetSessionQRCode"
	MiniAppService_OperateWxData_FullMethodName     = "/miniapp.MiniAppService/OperateWxData"
	MiniAppService_CloudCallFunction_FullMethodName = "/miniapp.MiniAppService/CloudCallFunction"
	MiniAppService_SendVerifyCode_FullMethodName    = "/miniapp.MiniAppService/SendVerifyCode"
	MiniAppService_CheckVerifyCode_FullMethodName   = "/miniapp.MiniAppService/CheckVerifyCode"
	MiniAppService_AddMobile_FullMethodName         = "/miniapp.MiniAppService/AddMobile"
	MiniAppService_DelMobile_FullMethodName         = "/miniapp.MiniAppService/DelMobile"
	MiniAppService_GetAllMobile_FullMethodName      = "/miniapp.MiniAppService/GetAllMobile"
	MiniAppService_GetRandomAvatar_FullMethodName   = "/miniapp.MiniAppService/GetRandomAvatar"
	MiniAppService_AddAvatar_FullMethodName         = "/miniapp.MiniAppService/AddAvatar"
	MiniAppService_UploadAvatarImg_FullMethodName   = "/miniapp.MiniAppService/UploadAvatarImg"
	MiniAppService_GetRecord_FullMethodName         = "/miniapp.MiniAppService/GetRecord"
	MiniAppService_AddRecord_FullMethodName         = "/miniapp.MiniAppService/AddRecord"
	MiniAppService_GetUserOpenID_FullMethodName     = "/miniapp.MiniAppService/GetUserOpenID"
	MiniAppService_OauthSdkApp_FullMethodName       = "/miniapp.MiniAppService/OauthSdkApp"
	MiniAppService_ThirdAppGrant_FullMethodName     = "/miniapp.MiniAppService/ThirdAppGrant"
)

// MiniAppServiceClient is the client API for MiniAppService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MiniAppService 小程序服务
type MiniAppServiceClient interface {
	// JSLogin 小程序 JS 登录授权
	JSLogin(ctx context.Context, in *JSLogin_Request, opts ...grpc.CallOption) (*JSLogin_Response, error)
	// QrcodeAuthLogin 小程序扫码授权登录
	QrcodeAuthLogin(ctx context.Context, in *QrcodeAuthLogin_Request, opts ...grpc.CallOption) (*QrcodeAuthLogin_Response, error)
	// GetRuntimeSession 获取小程序运行时会话
	GetRuntimeSession(ctx context.Context, in *GetRuntimeSession_Request, opts ...grpc.CallOption) (*GetRuntimeSession_Response, error)
	// GetSessionQRCode 获取小程序会话二维码
	GetSessionQRCode(ctx context.Context, in *GetSessionQRCode_Request, opts ...grpc.CallOption) (*GetSessionQRCode_Response, error)
	// OperateWxData 操作小程序数据
	OperateWxData(ctx context.Context, in *OperateWxData_Request, opts ...grpc.CallOption) (*OperateWxData_Response, error)
	// CloudCallFunction 调用小程序云函数
	CloudCallFunction(ctx context.Context, in *CloudCallFunction_Request, opts ...grpc.CallOption) (*CloudCallFunction_Response, error)
	// SendVerifyCode 发送手机验证码
	SendVerifyCode(ctx context.Context, in *SendVerifyCode_Request, opts ...grpc.CallOption) (*SendVerifyCode_Response, error)
	// CheckVerifyCode 校验手机验证码
	CheckVerifyCode(ctx context.Context, in *CheckVerifyCode_Request, opts ...grpc.CallOption) (*CheckVerifyCode_Response, error)
	// AddMobile 绑定手机号
	AddMobile(ctx context.Context, in *AddMobile_Request, opts ...grpc.CallOption) (*AddMobile_Response, error)
	// DelMobile 解绑手机号
	DelMobile(ctx context.Context, in *DelMobile_Request, opts ...grpc.CallOption) (*DelMobile_Response, error)
	// GetAllMobile 获取已绑定手机号列表
	GetAllMobile(ctx context.Context, in *GetAllMobile_Request, opts ...grpc.CallOption) (*GetAllMobile_Response, error)
	// GetRandomAvatar 获取随机头像
	GetRandomAvatar(ctx context.Context, in *GetRandomAvatar_Request, opts ...grpc.CallOption) (*GetRandomAvatar_Response, error)
	// AddAvatar 设置头像
	AddAvatar(ctx context.Context, in *AddAvatar_Request, opts ...grpc.CallOption) (*AddAvatar_Response, error)
	// UploadAvatarImg 上传自定义头像图片
	UploadAvatarImg(ctx context.Context, in *UploadAvatarImg_Request, opts ...grpc.CallOption) (*UploadAvatarImg_Response, error)
	// GetRecord 获取小程序使用记录
	GetRecord(ctx context.Context, in *GetRecord_Request, opts ...grpc.CallOption) (*GetRecord_Response, error)
	// AddRecord 添加小程序使用记录
	AddRecord(ctx context.Context, in *AddRecord_Request, opts ...grpc.CallOption) (*AddRecord_Response, error)
	// GetUserOpenID 获取用户 OpenID
	GetUserOpenID(ctx context.Context, in *GetUserOpenID_Request, opts ...grpc.CallOption) (*GetUserOpenID_Response, error)
	// OauthSdkApp SDK OAuth 确认授权
	OauthSdkApp(ctx context.Context, in *OauthSdkApp_Request, opts ...grpc.CallOption) (*OauthSdkApp_Response, error)
	// ThirdAppGrant 第三方 APP OAuth 授权
	ThirdAppGrant(ctx context.Context, in *ThirdAppGrant_Request, opts ...grpc.CallOption) (*ThirdAppGrant_Response, error)
}

type miniAppServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMiniAppServiceClient(cc grpc.ClientConnInterface) MiniAppServiceClient {
	return &miniAppServiceClient{cc}
}

func (c *miniAppServiceClient) JSLogin(ctx context.Context, in *JSLogin_Request, opts ...grpc.CallOption) (*JSLogin_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JSLogin_Response)
	err := c.cc.Invoke(ctx, MiniAppService_JSLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) QrcodeAuthLogin(ctx context.Context, in *QrcodeAuthLogin_Request, opts ...grpc.CallOption) (*QrcodeAuthLogin_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QrcodeAuthLogin_Response)
	err := c.cc.Invoke(ctx, MiniAppService_QrcodeAuthLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) GetRuntimeSession(ctx context.Context, in *GetRuntimeSession_Request, opts ...grpc.CallOption) (*GetRuntimeSession_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeSession_Response)
	err := c.cc.Invoke(ctx, MiniAppService_GetRuntimeSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) GetSessionQRCode(ctx context.Context, in *GetSessionQRCode_Request, opts ...grpc.CallOption) (*GetSessionQRCode_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionQRCode_Response)
	err := c.cc.Invoke(ctx, MiniAppService_GetSessionQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) OperateWxData(ctx context.Context, in *OperateWxData_Request, opts ...grpc.CallOption) (*OperateWxData_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OperateWxData_Response)
	err := c.cc.Invoke(ctx, MiniAppService_OperateWxData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) CloudCallFunction(ctx context.Context, in *CloudCallFunction_Request, opts ...grpc.CallOption) (*CloudCallFunction_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloudCallFunction_Response)
	err := c.cc.Invoke(ctx, MiniAppService_CloudCallFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) SendVerifyCode(ctx context.Context, in *SendVerifyCode_Request, opts ...grpc.CallOption) (*SendVerifyCode_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendVerifyCode_Response)
	err := c.cc.Invoke(ctx, MiniAppService_SendVerifyCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) CheckVerifyCode(ctx context.Context, in *CheckVerifyCode_Request, opts ...grpc.CallOption) (*CheckVerifyCode_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckVerifyCode_Response)
	err := c.cc.Invoke(ctx, MiniAppService_CheckVerifyCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) AddMobile(ctx context.Context, in *AddMobile_Request, opts ...grpc.CallOption) (*AddMobile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMobile_Response)
	err := c.cc.Invoke(ctx, MiniAppService_AddMobile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) DelMobile(ctx context.Context, in *DelMobile_Request, opts ...grpc.CallOption) (*DelMobile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelMobile_Response)
	err := c.cc.Invoke(ctx, MiniAppService_DelMobile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) GetAllMobile(ctx context.Context, in *GetAllMobile_Request, opts ...grpc.CallOption) (*GetAllMobile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllMobile_Response)
	err := c.cc.Invoke(ctx, MiniAppService_GetAllMobile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) GetRandomAvatar(ctx context.Context, in *GetRandomAvatar_Request, opts ...grpc.CallOption) (*GetRandomAvatar_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRandomAvatar_Response)
	err := c.cc.Invoke(ctx, MiniAppService_GetRandomAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) AddAvatar(ctx context.Context, in *AddAvatar_Request, opts ...grpc.CallOption) (*AddAvatar_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddAvatar_Response)
	err := c.cc.Invoke(ctx, MiniAppService_AddAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) UploadAvatarImg(ctx context.Context, in *UploadAvatarImg_Request, opts ...grpc.CallOption) (*UploadAvatarImg_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAvatarImg_Response)
	err := c.cc.Invoke(ctx, MiniAppService_UploadAvatarImg_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) GetRecord(ctx context.Context, in *GetRecord_Request, opts ...grpc.CallOption) (*GetRecord_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecord_Response)
	err := c.cc.Invoke(ctx, MiniAppService_GetRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) AddRecord(ctx context.Context, in *AddRecord_Request, opts ...grpc.CallOption) (*AddRecord_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddRecord_Response)
	err := c.cc.Invoke(ctx, MiniAppService_AddRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) GetUserOpenID(ctx context.Context, in *GetUserOpenID_Request, opts ...grpc.CallOption) (*GetUserOpenID_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserOpenID_Response)
	err := c.cc.Invoke(ctx, MiniAppService_GetUserOpenID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) OauthSdkApp(ctx context.Context, in *OauthSdkApp_Request, opts ...grpc.CallOption) (*OauthSdkApp_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OauthSdkApp_Response)
	err := c.cc.Invoke(ctx, MiniAppService_OauthSdkApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *miniAppServiceClient) ThirdAppGrant(ctx context.Context, in *ThirdAppGrant_Request, opts ...grpc.CallOption) (*ThirdAppGrant_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ThirdAppGrant_Response)
	err := c.cc.Invoke(ctx, MiniAppService_ThirdAppGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MiniAppServiceServer is the server API for MiniAppService service.
// All implementations must embed UnimplementedMiniAppServiceServer
// for forward compatibility.
//
// MiniAppService 小程序服务
type MiniAppServiceServer interface {
	// JSLogin 小程序 JS 登录授权
	JSLogin(context.Context, *JSLogin_Request) (*JSLogin_Response, error)
	// QrcodeAuthLogin 小程序扫码授权登录
	QrcodeAuthLogin(context.Context, *QrcodeAuthLogin_Request) (*QrcodeAuthLogin_Response, error)
	// GetRuntimeSession 获取小程序运行时会话
	GetRuntimeSession(context.Context, *GetRuntimeSession_Request) (*GetRuntimeSession_Response, error)
	// GetSessionQRCode 获取小程序会话二维码
	GetSessionQRCode(context.Context, *GetSessionQRCode_Request) (*GetSessionQRCode_Response, error)
	// OperateWxData 操作小程序数据
	OperateWxData(context.Context, *OperateWxData_Request) (*OperateWxData_Response, error)
	// CloudCallFunction 调用小程序云函数
	CloudCallFunction(context.Context, *CloudCallFunction_Request) (*CloudCallFunction_Response, error)
	// SendVerifyCode 发送手机验证码
	SendVerifyCode(context.Context, *SendVerifyCode_Request) (*SendVerifyCode_Response, error)
	// CheckVerifyCode 校验手机验证码
	CheckVerifyCode(context.Context, *CheckVerifyCode_Request) (*CheckVerifyCode_Response, error)
	// AddMobile 绑定手机号
	AddMobile(context.Context, *AddMobile_Request) (*AddMobile_Response, error)
	// DelMobile 解绑手机号
	DelMobile(context.Context, *DelMobile_Request) (*DelMobile_Response, error)
	// GetAllMobile 获取已绑定手机号列表
	GetAllMobile(context.Context, *GetAllMobile_Request) (*GetAllMobile_Response, error)
	// GetRandomAvatar 获取随机头像
	GetRandomAvatar(context.Context, *GetRandomAvatar_Request) (*GetRandomAvatar_Response, error)
	// AddAvatar 设置头像
	AddAvatar(context.Context, *AddAvatar_Request) (*AddAvatar_Response, error)
	// UploadAvatarImg 上传自定义头像图片
	UploadAvatarImg(context.Context, *UploadAvatarImg_Request) (*UploadAvatarImg_Response, error)
	// GetRecord 获取小程序使用记录
	GetRecord(context.Context, *GetRecord_Request) (*GetRecord_Response, error)
	// AddRecord 添加小程序使用记录
	AddRecord(context.Context, *AddRecord_Request) (*AddRecord_Response, error)
	// GetUserOpenID 获取用户 OpenID
	GetUserOpenID(context.Context, *GetUserOpenID_Request) (*GetUserOpenID_Response, error)
	// OauthSdkApp SDK OAuth 确认授权
	OauthSdkApp(context.Context, *OauthSdkApp_Request) (*OauthSdkApp_Response, error)
	// ThirdAppGrant 第三方 APP OAuth 授权
	ThirdAppGrant(context.Context, *ThirdAppGrant_Request) (*ThirdAppGrant_Response, error)
	mustEmbedUnimplementedMiniAppServiceServer()
}

// UnimplementedMiniAppServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMiniAppServiceServer struct{}

func (UnimplementedMiniAppServiceServer) JSLogin(context.Context, *JSLogin_Request) (*JSLogin_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method JSLogin not implemented")
}
func (UnimplementedMiniAppServiceServer) QrcodeAuthLogin(context.Context, *QrcodeAuthLogin_Request) (*QrcodeAuthLogin_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method QrcodeAuthLogin not implemented")
}
func (UnimplementedMiniAppServiceServer) GetRuntimeSession(context.Context, *GetRuntimeSession_Request) (*GetRuntimeSession_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRuntimeSession not implemented")
}
func (UnimplementedMiniAppServiceServer) GetSessionQRCode(context.Context, *GetSessionQRCode_Request) (*GetSessionQRCode_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSessionQRCode not implemented")
}
func (UnimplementedMiniAppServiceServer) OperateWxData(context.Context, *OperateWxData_Request) (*OperateWxData_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method OperateWxData not implemented")
}
func (UnimplementedMiniAppServiceServer) CloudCallFunction(context.Context, *CloudCallFunction_Request) (*CloudCallFunction_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CloudCallFunction not implemented")
}
func (UnimplementedMiniAppServiceServer) SendVerifyCode(context.Context, *SendVerifyCode_Request) (*SendVerifyCode_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVerifyCode not implemented")
}
func (UnimplementedMiniAppServiceServer) CheckVerifyCode(context.Context, *CheckVerifyCode_Request) (*CheckVerifyCode_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckVerifyCode not implemented")
}
func (UnimplementedMiniAppServiceServer) AddMobile(context.Context, *AddMobile_Request) (*AddMobile_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMobile not implemented")
}
func (UnimplementedMiniAppServiceServer) DelMobile(context.Context, *DelMobile_Request) (*DelMobile_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DelMobile not implemented")
}
func (UnimplementedMiniAppServiceServer) GetAllMobile(context.Context, *GetAllMobile_Request) (*GetAllMobile_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllMobile not implemented")
}
func (UnimplementedMiniAppServiceServer) GetRandomAvatar(context.Context, *GetRandomAvatar_Request) (*GetRandomAvatar_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRandomAvatar not implemented")
}
func (UnimplementedMiniAppServiceServer) AddAvatar(context.Context, *AddAvatar_Request) (*AddAvatar_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddAvatar not implemented")
}
func (UnimplementedMiniAppServiceServer) UploadAvatarImg(context.Context, *UploadAvatarImg_Request) (*UploadAvatarImg_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAvatarImg not implemented")
}
func (UnimplementedMiniAppServiceServer) GetRecord(context.Context, *GetRecord_Request) (*GetRecord_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedMiniAppServiceServer) AddRecord(context.Context, *AddRecord_Request) (*AddRecord_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRecord not implemented")
}
func (UnimplementedMiniAppServiceServer) GetUserOpenID(context.Context, *GetUserOpenID_Request) (*GetUserOpenID_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserOpenID not implemented")
}
func (UnimplementedMiniAppServiceServer) OauthSdkApp(context.Context, *OauthSdkApp_Request) (*OauthSdkApp_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method OauthSdkApp not implemented")
}
func (UnimplementedMiniAppServiceServer) ThirdAppGrant(context.Context, *ThirdAppGrant_Request) (*ThirdAppGrant_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ThirdAppGrant not implemented")
}
func (UnimplementedMiniAppServiceServer) mustEmbedUnimplementedMiniAppServiceServer() {}
func (UnimplementedMiniAppServiceServer) testEmbeddedByValue()                        {}

// UnsafeMiniAppServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MiniAppServiceServer will
// result in compilation errors.
type UnsafeMiniAppServiceServer interface {
	mustEmbedUnimplementedMiniAppServiceServer()
}

func RegisterMiniAppServiceServer(s grpc.ServiceRegistrar, srv MiniAppServiceServer) {
	// If the following call panics, it indicates UnimplementedMiniAppServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MiniAppService_ServiceDesc, srv)
}

func _MiniAppService_JSLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JSLogin_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).JSLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_JSLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).JSLogin(ctx, req.(*JSLogin_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_QrcodeAuthLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QrcodeAuthLogin_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).QrcodeAuthLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_QrcodeAuthLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).QrcodeAuthLogin(ctx, req.(*QrcodeAuthLogin_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_GetRuntimeSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeSession_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).GetRuntimeSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_GetRuntimeSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).GetRuntimeSession(ctx, req.(*GetRuntimeSession_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_GetSessionQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionQRCode_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).GetSessionQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_GetSessionQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).GetSessionQRCode(ctx, req.(*GetSessionQRCode_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_OperateWxData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperateWxData_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).OperateWxData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_OperateWxData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).OperateWxData(ctx, req.(*OperateWxData_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_CloudCallFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloudCallFunction_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).CloudCallFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_CloudCallFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).CloudCallFunction(ctx, req.(*CloudCallFunction_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_SendVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerifyCode_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).SendVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_SendVerifyCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).SendVerifyCode(ctx, req.(*SendVerifyCode_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_CheckVerifyCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVerifyCode_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).CheckVerifyCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_CheckVerifyCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).CheckVerifyCode(ctx, req.(*CheckVerifyCode_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_AddMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMobile_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).AddMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_AddMobile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).AddMobile(ctx, req.(*AddMobile_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_DelMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelMobile_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).DelMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_DelMobile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).DelMobile(ctx, req.(*DelMobile_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_GetAllMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllMobile_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).GetAllMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_GetAllMobile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).GetAllMobile(ctx, req.(*GetAllMobile_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_GetRandomAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRandomAvatar_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).GetRandomAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_GetRandomAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).GetRandomAvatar(ctx, req.(*GetRandomAvatar_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_AddAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAvatar_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).AddAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_AddAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).AddAvatar(ctx, req.(*AddAvatar_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_UploadAvatarImg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAvatarImg_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).UploadAvatarImg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_UploadAvatarImg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).UploadAvatarImg(ctx, req.(*UploadAvatarImg_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecord_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).GetRecord(ctx, req.(*GetRecord_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_AddRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRecord_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).AddRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_AddRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).AddRecord(ctx, req.(*AddRecord_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_GetUserOpenID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserOpenID_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).GetUserOpenID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_GetUserOpenID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).GetUserOpenID(ctx, req.(*GetUserOpenID_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_OauthSdkApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OauthSdkApp_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).OauthSdkApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_OauthSdkApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).OauthSdkApp(ctx, req.(*OauthSdkApp_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MiniAppService_ThirdAppGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThirdAppGrant_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MiniAppServiceServer).ThirdAppGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MiniAppService_ThirdAppGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MiniAppServiceServer).ThirdAppGrant(ctx, req.(*ThirdAppGrant_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MiniAppService_ServiceDesc is the grpc.ServiceDesc for MiniAppService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MiniAppService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "miniapp.MiniAppService",
	HandlerType: (*MiniAppServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JSLogin",
			Handler:    _MiniAppService_JSLogin_Handler,
		},
		{
			MethodName: "QrcodeAuthLogin",
			Handler:    _MiniAppService_QrcodeAuthLogin_Handler,
		},
		{
			MethodName: "GetRuntimeSession",
			Handler:    _MiniAppService_GetRuntimeSession_Handler,
		},
		{
			MethodName: "GetSessionQRCode",
			Handler:    _MiniAppService_GetSessionQRCode_Handler,
		},
		{
			MethodName: "OperateWxData",
			Handler:    _MiniAppService_OperateWxData_Handler,
		},
		{
			MethodName: "CloudCallFunction",
			Handler:    _MiniAppService_CloudCallFunction_Handler,
		},
		{
			MethodName: "SendVerifyCode",
			Handler:    _MiniAppService_SendVerifyCode_Handler,
		},
		{
			MethodName: "CheckVerifyCode",
			Handler:    _MiniAppService_CheckVerifyCode_Handler,
		},
		{
			MethodName: "AddMobile",
			Handler:    _MiniAppService_AddMobile_Handler,
		},
		{
			MethodName: "DelMobile",
			Handler:    _MiniAppService_DelMobile_Handler,
		},
		{
			MethodName: "GetAllMobile",
			Handler:    _MiniAppService_GetAllMobile_Handler,
		},
		{
			MethodName: "GetRandomAvatar",
			Handler:    _MiniAppService_GetRandomAvatar_Handler,
		},
		{
			MethodName: "AddAvatar",
			Handler:    _MiniAppService_AddAvatar_Handler,
		},
		{
			MethodName: "UploadAvatarImg",
			Handler:    _MiniAppService_UploadAvatarImg_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _MiniAppService_GetRecord_Handler,
		},
		{
			MethodName: "AddRecord",
			Handler:    _MiniAppService_AddRecord_Handler,
		},
		{
			MethodName: "GetUserOpenID",
			Handler:    _MiniAppService_GetUserOpenID_Handler,
		},
		{
			MethodName: "OauthSdkApp",
			Handler:    _MiniAppService_OauthSdkApp_Handler,
		},
		{
			MethodName: "ThirdAppGrant",
			Handler:    _MiniAppService_ThirdAppGrant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "miniapp/miniapp.proto",
}
