// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: command/command.proto

package command

import (
	contact "github.com/sbgayhub/golem/sdk/contact"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Command 命令
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cmd           string                 `protobuf:"bytes,1,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Args          map[string]string      `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Sender        *contact.Contact       `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_command_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_command_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_command_command_proto_rawDescGZIP(), []int{0}
}

func (x *Command) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *Command) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *Command) GetSender() *contact.Contact {
	if x != nil {
		return x.Sender
	}
	return nil
}

var File_command_command_proto protoreflect.FileDescriptor

const file_command_command_proto_rawDesc = "" +
	"\n" +
	"\x15command/command.proto\x12\acommand\x1a\x15contact/contact.proto\"\xae\x01\n" +
	"\aCommand\x12\x10\n" +
	"\x03cmd\x18\x01 \x01(\tR\x03cmd\x12.\n" +
	"\x04args\x18\x02 \x03(\v2\x1a.command.Command.ArgsEntryR\x04args\x12(\n" +
	"\x06sender\x18\x03 \x01(\v2\x10.contact.ContactR\x06sender\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B~\n" +
	"\vcom.commandB\fCommandProtoP\x01Z%github.com/sbgayhub/golem/sdk/command\xa2\x02\x03CXX\xaa\x02\aCommand\xca\x02\aCommand\xe2\x02\x13Command\\GPBMetadata\xea\x02\aCommandb\x06proto3"

var (
	file_command_command_proto_rawDescOnce sync.Once
	file_command_command_proto_rawDescData []byte
)

func file_command_command_proto_rawDescGZIP() []byte {
	file_command_command_proto_rawDescOnce.Do(func() {
		file_command_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_command_command_proto_rawDesc), len(file_command_command_proto_rawDesc)))
	})
	return file_command_command_proto_rawDescData
}

var file_command_command_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_command_command_proto_goTypes = []any{
	(*Command)(nil),         // 0: command.Command
	nil,                     // 1: command.Command.ArgsEntry
	(*contact.Contact)(nil), // 2: contact.Contact
}
var file_command_command_proto_depIdxs = []int32{
	1, // 0: command.Command.args:type_name -> command.Command.ArgsEntry
	2, // 1: command.Command.sender:type_name -> contact.Contact
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_command_command_proto_init() }
func file_command_command_proto_init() {
	if File_command_command_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_command_command_proto_rawDesc), len(file_command_command_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_command_command_proto_goTypes,
		DependencyIndexes: file_command_command_proto_depIdxs,
		MessageInfos:      file_command_command_proto_msgTypes,
	}.Build()
	File_command_command_proto = out.File
	file_command_command_proto_goTypes = nil
	file_command_command_proto_depIdxs = nil
}
