// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: user/user.proto

package user

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserService_GetProfile_FullMethodName          = "/user.UserService/GetProfile"
	UserService_UpdateProfile_FullMethodName       = "/user.UserService/UpdateProfile"
	UserService_UploadAvatar_FullMethodName        = "/user.UserService/UploadAvatar"
	UserService_GetQRCode_FullMethodName           = "/user.UserService/GetQRCode"
	UserService_SetPrivacy_FullMethodName          = "/user.UserService/SetPrivacy"
	UserService_SetAlias_FullMethodName            = "/user.UserService/SetAlias"
	UserService_VerifyPassword_FullMethodName      = "/user.UserService/VerifyPassword"
	UserService_SetPassword_FullMethodName         = "/user.UserService/SetPassword"
	UserService_SendVerifyMobile_FullMethodName    = "/user.UserService/SendVerifyMobile"
	UserService_BindMobile_FullMethodName          = "/user.UserService/BindMobile"
	UserService_BindEmail_FullMethodName           = "/user.UserService/BindEmail"
	UserService_SendVerifyEmail_FullMethodName     = "/user.UserService/SendVerifyEmail"
	UserService_GetSafetyInfo_FullMethodName       = "/user.UserService/GetSafetyInfo"
	UserService_DelSafeDevice_FullMethodName       = "/user.UserService/DelSafeDevice"
	UserService_ReportMotion_FullMethodName        = "/user.UserService/ReportMotion"
	UserService_GetBoundHardDevices_FullMethodName = "/user.UserService/GetBoundHardDevices"
	UserService_GetCert_FullMethodName             = "/user.UserService/GetCert"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// UserService 用户服务
type UserServiceClient interface {
	// GetProfile 获取个人信息
	GetProfile(ctx context.Context, in *GetProfile_Request, opts ...grpc.CallOption) (*GetProfile_Response, error)
	// UpdateProfile 更新个人信息
	UpdateProfile(ctx context.Context, in *UpdateProfile_Request, opts ...grpc.CallOption) (*UpdateProfile_Response, error)
	// UploadAvatar 上传头像
	UploadAvatar(ctx context.Context, in *UploadAvatar_Request, opts ...grpc.CallOption) (*UploadAvatar_Response, error)
	// GetQRCode 获取个人二维码
	GetQRCode(ctx context.Context, in *GetQRCode_Request, opts ...grpc.CallOption) (*GetQRCode_Response, error)
	// SetPrivacy 设置隐私选项
	SetPrivacy(ctx context.Context, in *SetPrivacy_Request, opts ...grpc.CallOption) (*SetPrivacy_Response, error)
	// SetAlias 设置微信号
	SetAlias(ctx context.Context, in *SetAlias_Request, opts ...grpc.CallOption) (*SetAlias_Response, error)
	// VerifyPassword 验证密码
	VerifyPassword(ctx context.Context, in *VerifyPassword_Request, opts ...grpc.CallOption) (*VerifyPassword_Response, error)
	// SetPassword 设置密码
	SetPassword(ctx context.Context, in *SetPassword_Request, opts ...grpc.CallOption) (*SetPassword_Response, error)
	// SendVerifyMobile 发送手机验证码
	SendVerifyMobile(ctx context.Context, in *SendVerifyMobile_Request, opts ...grpc.CallOption) (*SendVerifyMobile_Response, error)
	// BindMobile 绑定手机号
	BindMobile(ctx context.Context, in *BindMobile_Request, opts ...grpc.CallOption) (*BindMobile_Response, error)
	// BindEmail 绑定邮箱
	BindEmail(ctx context.Context, in *BindEmail_Request, opts ...grpc.CallOption) (*BindEmail_Response, error)
	// SendVerifyEmail 发送验证邮件
	SendVerifyEmail(ctx context.Context, in *SendVerifyEmail_Request, opts ...grpc.CallOption) (*SendVerifyEmail_Response, error)
	// GetSafetyInfo 获取安全设备列表
	GetSafetyInfo(ctx context.Context, in *GetSafetyInfo_Request, opts ...grpc.CallOption) (*GetSafetyInfo_Response, error)
	// DelSafeDevice 删除安全设备
	DelSafeDevice(ctx context.Context, in *DelSafeDevice_Request, opts ...grpc.CallOption) (*DelSafeDevice_Response, error)
	// ReportMotion 上报运动步数
	ReportMotion(ctx context.Context, in *ReportMotion_Request, opts ...grpc.CallOption) (*ReportMotion_Response, error)
	// GetBoundHardDevices 获取绑定的硬件设备列表
	GetBoundHardDevices(ctx context.Context, in *GetBoundHardDevices_Request, opts ...grpc.CallOption) (*GetBoundHardDevices_Response, error)
	// GetCert 获取证书信息
	GetCert(ctx context.Context, in *GetCert_Request, opts ...grpc.CallOption) (*GetCert_Response, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetProfile(ctx context.Context, in *GetProfile_Request, opts ...grpc.CallOption) (*GetProfile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfile_Response)
	err := c.cc.Invoke(ctx, UserService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfile_Request, opts ...grpc.CallOption) (*UpdateProfile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfile_Response)
	err := c.cc.Invoke(ctx, UserService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UploadAvatar(ctx context.Context, in *UploadAvatar_Request, opts ...grpc.CallOption) (*UploadAvatar_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadAvatar_Response)
	err := c.cc.Invoke(ctx, UserService_UploadAvatar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetQRCode(ctx context.Context, in *GetQRCode_Request, opts ...grpc.CallOption) (*GetQRCode_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQRCode_Response)
	err := c.cc.Invoke(ctx, UserService_GetQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetPrivacy(ctx context.Context, in *SetPrivacy_Request, opts ...grpc.CallOption) (*SetPrivacy_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPrivacy_Response)
	err := c.cc.Invoke(ctx, UserService_SetPrivacy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetAlias(ctx context.Context, in *SetAlias_Request, opts ...grpc.CallOption) (*SetAlias_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAlias_Response)
	err := c.cc.Invoke(ctx, UserService_SetAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) VerifyPassword(ctx context.Context, in *VerifyPassword_Request, opts ...grpc.CallOption) (*VerifyPassword_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPassword_Response)
	err := c.cc.Invoke(ctx, UserService_VerifyPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SetPassword(ctx context.Context, in *SetPassword_Request, opts ...grpc.CallOption) (*SetPassword_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPassword_Response)
	err := c.cc.Invoke(ctx, UserService_SetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendVerifyMobile(ctx context.Context, in *SendVerifyMobile_Request, opts ...grpc.CallOption) (*SendVerifyMobile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendVerifyMobile_Response)
	err := c.cc.Invoke(ctx, UserService_SendVerifyMobile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) BindMobile(ctx context.Context, in *BindMobile_Request, opts ...grpc.CallOption) (*BindMobile_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindMobile_Response)
	err := c.cc.Invoke(ctx, UserService_BindMobile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) BindEmail(ctx context.Context, in *BindEmail_Request, opts ...grpc.CallOption) (*BindEmail_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindEmail_Response)
	err := c.cc.Invoke(ctx, UserService_BindEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SendVerifyEmail(ctx context.Context, in *SendVerifyEmail_Request, opts ...grpc.CallOption) (*SendVerifyEmail_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendVerifyEmail_Response)
	err := c.cc.Invoke(ctx, UserService_SendVerifyEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetSafetyInfo(ctx context.Context, in *GetSafetyInfo_Request, opts ...grpc.CallOption) (*GetSafetyInfo_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSafetyInfo_Response)
	err := c.cc.Invoke(ctx, UserService_GetSafetyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DelSafeDevice(ctx context.Context, in *DelSafeDevice_Request, opts ...grpc.CallOption) (*DelSafeDevice_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelSafeDevice_Response)
	err := c.cc.Invoke(ctx, UserService_DelSafeDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ReportMotion(ctx context.Context, in *ReportMotion_Request, opts ...grpc.CallOption) (*ReportMotion_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportMotion_Response)
	err := c.cc.Invoke(ctx, UserService_ReportMotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBoundHardDevices(ctx context.Context, in *GetBoundHardDevices_Request, opts ...grpc.CallOption) (*GetBoundHardDevices_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBoundHardDevices_Response)
	err := c.cc.Invoke(ctx, UserService_GetBoundHardDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetCert(ctx context.Context, in *GetCert_Request, opts ...grpc.CallOption) (*GetCert_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCert_Response)
	err := c.cc.Invoke(ctx, UserService_GetCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility.
//
// UserService 用户服务
type UserServiceServer interface {
	// GetProfile 获取个人信息
	GetProfile(context.Context, *GetProfile_Request) (*GetProfile_Response, error)
	// UpdateProfile 更新个人信息
	UpdateProfile(context.Context, *UpdateProfile_Request) (*UpdateProfile_Response, error)
	// UploadAvatar 上传头像
	UploadAvatar(context.Context, *UploadAvatar_Request) (*UploadAvatar_Response, error)
	// GetQRCode 获取个人二维码
	GetQRCode(context.Context, *GetQRCode_Request) (*GetQRCode_Response, error)
	// SetPrivacy 设置隐私选项
	SetPrivacy(context.Context, *SetPrivacy_Request) (*SetPrivacy_Response, error)
	// SetAlias 设置微信号
	SetAlias(context.Context, *SetAlias_Request) (*SetAlias_Response, error)
	// VerifyPassword 验证密码
	VerifyPassword(context.Context, *VerifyPassword_Request) (*VerifyPassword_Response, error)
	// SetPassword 设置密码
	SetPassword(context.Context, *SetPassword_Request) (*SetPassword_Response, error)
	// SendVerifyMobile 发送手机验证码
	SendVerifyMobile(context.Context, *SendVerifyMobile_Request) (*SendVerifyMobile_Response, error)
	// BindMobile 绑定手机号
	BindMobile(context.Context, *BindMobile_Request) (*BindMobile_Response, error)
	// BindEmail 绑定邮箱
	BindEmail(context.Context, *BindEmail_Request) (*BindEmail_Response, error)
	// SendVerifyEmail 发送验证邮件
	SendVerifyEmail(context.Context, *SendVerifyEmail_Request) (*SendVerifyEmail_Response, error)
	// GetSafetyInfo 获取安全设备列表
	GetSafetyInfo(context.Context, *GetSafetyInfo_Request) (*GetSafetyInfo_Response, error)
	// DelSafeDevice 删除安全设备
	DelSafeDevice(context.Context, *DelSafeDevice_Request) (*DelSafeDevice_Response, error)
	// ReportMotion 上报运动步数
	ReportMotion(context.Context, *ReportMotion_Request) (*ReportMotion_Response, error)
	// GetBoundHardDevices 获取绑定的硬件设备列表
	GetBoundHardDevices(context.Context, *GetBoundHardDevices_Request) (*GetBoundHardDevices_Response, error)
	// GetCert 获取证书信息
	GetCert(context.Context, *GetCert_Request) (*GetCert_Response, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserServiceServer struct{}

func (UnimplementedUserServiceServer) GetProfile(context.Context, *GetProfile_Request) (*GetProfile_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedUserServiceServer) UpdateProfile(context.Context, *UpdateProfile_Request) (*UpdateProfile_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedUserServiceServer) UploadAvatar(context.Context, *UploadAvatar_Request) (*UploadAvatar_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadAvatar not implemented")
}
func (UnimplementedUserServiceServer) GetQRCode(context.Context, *GetQRCode_Request) (*GetQRCode_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQRCode not implemented")
}
func (UnimplementedUserServiceServer) SetPrivacy(context.Context, *SetPrivacy_Request) (*SetPrivacy_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPrivacy not implemented")
}
func (UnimplementedUserServiceServer) SetAlias(context.Context, *SetAlias_Request) (*SetAlias_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAlias not implemented")
}
func (UnimplementedUserServiceServer) VerifyPassword(context.Context, *VerifyPassword_Request) (*VerifyPassword_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPassword not implemented")
}
func (UnimplementedUserServiceServer) SetPassword(context.Context, *SetPassword_Request) (*SetPassword_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPassword not implemented")
}
func (UnimplementedUserServiceServer) SendVerifyMobile(context.Context, *SendVerifyMobile_Request) (*SendVerifyMobile_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVerifyMobile not implemented")
}
func (UnimplementedUserServiceServer) BindMobile(context.Context, *BindMobile_Request) (*BindMobile_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method BindMobile not implemented")
}
func (UnimplementedUserServiceServer) BindEmail(context.Context, *BindEmail_Request) (*BindEmail_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method BindEmail not implemented")
}
func (UnimplementedUserServiceServer) SendVerifyEmail(context.Context, *SendVerifyEmail_Request) (*SendVerifyEmail_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SendVerifyEmail not implemented")
}
func (UnimplementedUserServiceServer) GetSafetyInfo(context.Context, *GetSafetyInfo_Request) (*GetSafetyInfo_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSafetyInfo not implemented")
}
func (UnimplementedUserServiceServer) DelSafeDevice(context.Context, *DelSafeDevice_Request) (*DelSafeDevice_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DelSafeDevice not implemented")
}
func (UnimplementedUserServiceServer) ReportMotion(context.Context, *ReportMotion_Request) (*ReportMotion_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportMotion not implemented")
}
func (UnimplementedUserServiceServer) GetBoundHardDevices(context.Context, *GetBoundHardDevices_Request) (*GetBoundHardDevices_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBoundHardDevices not implemented")
}
func (UnimplementedUserServiceServer) GetCert(context.Context, *GetCert_Request) (*GetCert_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCert not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}
func (UnimplementedUserServiceServer) testEmbeddedByValue()                     {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	// If the following call panics, it indicates UnimplementedUserServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfile_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetProfile(ctx, req.(*GetProfile_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfile_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateProfile(ctx, req.(*UpdateProfile_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UploadAvatar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadAvatar_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UploadAvatar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UploadAvatar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UploadAvatar(ctx, req.(*UploadAvatar_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQRCode_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetQRCode(ctx, req.(*GetQRCode_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetPrivacy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrivacy_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetPrivacy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetPrivacy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetPrivacy(ctx, req.(*SetPrivacy_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlias_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetAlias(ctx, req.(*SetAlias_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_VerifyPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPassword_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).VerifyPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_VerifyPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).VerifyPassword(ctx, req.(*VerifyPassword_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPassword_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SetPassword(ctx, req.(*SetPassword_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendVerifyMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerifyMobile_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendVerifyMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SendVerifyMobile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendVerifyMobile(ctx, req.(*SendVerifyMobile_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_BindMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindMobile_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).BindMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_BindMobile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).BindMobile(ctx, req.(*BindMobile_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_BindEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindEmail_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).BindEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_BindEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).BindEmail(ctx, req.(*BindEmail_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SendVerifyEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendVerifyEmail_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendVerifyEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SendVerifyEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendVerifyEmail(ctx, req.(*SendVerifyEmail_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetSafetyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSafetyInfo_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetSafetyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetSafetyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetSafetyInfo(ctx, req.(*GetSafetyInfo_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DelSafeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelSafeDevice_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DelSafeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DelSafeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DelSafeDevice(ctx, req.(*DelSafeDevice_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ReportMotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportMotion_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ReportMotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ReportMotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ReportMotion(ctx, req.(*ReportMotion_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBoundHardDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBoundHardDevices_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBoundHardDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBoundHardDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBoundHardDevices(ctx, req.(*GetBoundHardDevices_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCert_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetCert(ctx, req.(*GetCert_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProfile",
			Handler:    _UserService_GetProfile_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _UserService_UpdateProfile_Handler,
		},
		{
			MethodName: "UploadAvatar",
			Handler:    _UserService_UploadAvatar_Handler,
		},
		{
			MethodName: "GetQRCode",
			Handler:    _UserService_GetQRCode_Handler,
		},
		{
			MethodName: "SetPrivacy",
			Handler:    _UserService_SetPrivacy_Handler,
		},
		{
			MethodName: "SetAlias",
			Handler:    _UserService_SetAlias_Handler,
		},
		{
			MethodName: "VerifyPassword",
			Handler:    _UserService_VerifyPassword_Handler,
		},
		{
			MethodName: "SetPassword",
			Handler:    _UserService_SetPassword_Handler,
		},
		{
			MethodName: "SendVerifyMobile",
			Handler:    _UserService_SendVerifyMobile_Handler,
		},
		{
			MethodName: "BindMobile",
			Handler:    _UserService_BindMobile_Handler,
		},
		{
			MethodName: "BindEmail",
			Handler:    _UserService_BindEmail_Handler,
		},
		{
			MethodName: "SendVerifyEmail",
			Handler:    _UserService_SendVerifyEmail_Handler,
		},
		{
			MethodName: "GetSafetyInfo",
			Handler:    _UserService_GetSafetyInfo_Handler,
		},
		{
			MethodName: "DelSafeDevice",
			Handler:    _UserService_DelSafeDevice_Handler,
		},
		{
			MethodName: "ReportMotion",
			Handler:    _UserService_ReportMotion_Handler,
		},
		{
			MethodName: "GetBoundHardDevices",
			Handler:    _UserService_GetBoundHardDevices_Handler,
		},
		{
			MethodName: "GetCert",
			Handler:    _UserService_GetCert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}
