// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: moments/moments.proto

package moments

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MomentsService_Timeline_FullMethodName      = "/moments.MomentsService/Timeline"
	MomentsService_UserPage_FullMethodName      = "/moments.MomentsService/UserPage"
	MomentsService_Detail_FullMethodName        = "/moments.MomentsService/Detail"
	MomentsService_Comment_FullMethodName       = "/moments.MomentsService/Comment"
	MomentsService_Like_FullMethodName          = "/moments.MomentsService/Like"
	MomentsService_Unlike_FullMethodName        = "/moments.MomentsService/Unlike"
	MomentsService_Delete_FullMethodName        = "/moments.MomentsService/Delete"
	MomentsService_DeleteComment_FullMethodName = "/moments.MomentsService/DeleteComment"
	MomentsService_Post_FullMethodName          = "/moments.MomentsService/Post"
	MomentsService_Upload_FullMethodName        = "/moments.MomentsService/Upload"
	MomentsService_Sync_FullMethodName          = "/moments.MomentsService/Sync"
	MomentsService_SetPrivacy_FullMethodName    = "/moments.MomentsService/SetPrivacy"
)

// MomentsServiceClient is the client API for MomentsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MomentsService 朋友圈服务
type MomentsServiceClient interface {
	// Timeline 获取朋友圈时间线
	Timeline(ctx context.Context, in *Timeline_Request, opts ...grpc.CallOption) (*Timeline_Response, error)
	// UserPage 获取用户朋友圈主页
	UserPage(ctx context.Context, in *UserPage_Request, opts ...grpc.CallOption) (*UserPage_Response, error)
	// Detail 获取单条朋友圈详情
	Detail(ctx context.Context, in *Detail_Request, opts ...grpc.CallOption) (*Detail_Response, error)
	// Comment 评论朋友圈
	Comment(ctx context.Context, in *Comment_Request, opts ...grpc.CallOption) (*Comment_Response, error)
	// Like 点赞朋友圈
	Like(ctx context.Context, in *Like_Request, opts ...grpc.CallOption) (*Like_Response, error)
	// Unlike 取消点赞
	Unlike(ctx context.Context, in *Unlike_Request, opts ...grpc.CallOption) (*Unlike_Response, error)
	// Delete 删除朋友圈
	Delete(ctx context.Context, in *Delete_Request, opts ...grpc.CallOption) (*Delete_Response, error)
	// DeleteComment 删除朋友圈评论
	DeleteComment(ctx context.Context, in *DeleteComment_Request, opts ...grpc.CallOption) (*DeleteComment_Response, error)
	// Post 发布朋友圈
	Post(ctx context.Context, in *Post_Request, opts ...grpc.CallOption) (*Post_Response, error)
	// Upload 上传朋友圈媒体
	Upload(ctx context.Context, in *Upload_Request, opts ...grpc.CallOption) (*Upload_Response, error)
	// Sync 同步朋友圈数据
	Sync(ctx context.Context, in *Sync_Request, opts ...grpc.CallOption) (*Sync_Response, error)
	// SetPrivacy 设置朋友圈隐私
	SetPrivacy(ctx context.Context, in *SetPrivacy_Request, opts ...grpc.CallOption) (*SetPrivacy_Response, error)
}

type momentsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMomentsServiceClient(cc grpc.ClientConnInterface) MomentsServiceClient {
	return &momentsServiceClient{cc}
}

func (c *momentsServiceClient) Timeline(ctx context.Context, in *Timeline_Request, opts ...grpc.CallOption) (*Timeline_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Timeline_Response)
	err := c.cc.Invoke(ctx, MomentsService_Timeline_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) UserPage(ctx context.Context, in *UserPage_Request, opts ...grpc.CallOption) (*UserPage_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPage_Response)
	err := c.cc.Invoke(ctx, MomentsService_UserPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) Detail(ctx context.Context, in *Detail_Request, opts ...grpc.CallOption) (*Detail_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Detail_Response)
	err := c.cc.Invoke(ctx, MomentsService_Detail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) Comment(ctx context.Context, in *Comment_Request, opts ...grpc.CallOption) (*Comment_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Comment_Response)
	err := c.cc.Invoke(ctx, MomentsService_Comment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) Like(ctx context.Context, in *Like_Request, opts ...grpc.CallOption) (*Like_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Like_Response)
	err := c.cc.Invoke(ctx, MomentsService_Like_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) Unlike(ctx context.Context, in *Unlike_Request, opts ...grpc.CallOption) (*Unlike_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Unlike_Response)
	err := c.cc.Invoke(ctx, MomentsService_Unlike_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) Delete(ctx context.Context, in *Delete_Request, opts ...grpc.CallOption) (*Delete_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Delete_Response)
	err := c.cc.Invoke(ctx, MomentsService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) DeleteComment(ctx context.Context, in *DeleteComment_Request, opts ...grpc.CallOption) (*DeleteComment_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteComment_Response)
	err := c.cc.Invoke(ctx, MomentsService_DeleteComment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) Post(ctx context.Context, in *Post_Request, opts ...grpc.CallOption) (*Post_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Post_Response)
	err := c.cc.Invoke(ctx, MomentsService_Post_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) Upload(ctx context.Context, in *Upload_Request, opts ...grpc.CallOption) (*Upload_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Upload_Response)
	err := c.cc.Invoke(ctx, MomentsService_Upload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) Sync(ctx context.Context, in *Sync_Request, opts ...grpc.CallOption) (*Sync_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Sync_Response)
	err := c.cc.Invoke(ctx, MomentsService_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *momentsServiceClient) SetPrivacy(ctx context.Context, in *SetPrivacy_Request, opts ...grpc.CallOption) (*SetPrivacy_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPrivacy_Response)
	err := c.cc.Invoke(ctx, MomentsService_SetPrivacy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MomentsServiceServer is the server API for MomentsService service.
// All implementations must embed UnimplementedMomentsServiceServer
// for forward compatibility.
//
// MomentsService 朋友圈服务
type MomentsServiceServer interface {
	// Timeline 获取朋友圈时间线
	Timeline(context.Context, *Timeline_Request) (*Timeline_Response, error)
	// UserPage 获取用户朋友圈主页
	UserPage(context.Context, *UserPage_Request) (*UserPage_Response, error)
	// Detail 获取单条朋友圈详情
	Detail(context.Context, *Detail_Request) (*Detail_Response, error)
	// Comment 评论朋友圈
	Comment(context.Context, *Comment_Request) (*Comment_Response, error)
	// Like 点赞朋友圈
	Like(context.Context, *Like_Request) (*Like_Response, error)
	// Unlike 取消点赞
	Unlike(context.Context, *Unlike_Request) (*Unlike_Response, error)
	// Delete 删除朋友圈
	Delete(context.Context, *Delete_Request) (*Delete_Response, error)
	// DeleteComment 删除朋友圈评论
	DeleteComment(context.Context, *DeleteComment_Request) (*DeleteComment_Response, error)
	// Post 发布朋友圈
	Post(context.Context, *Post_Request) (*Post_Response, error)
	// Upload 上传朋友圈媒体
	Upload(context.Context, *Upload_Request) (*Upload_Response, error)
	// Sync 同步朋友圈数据
	Sync(context.Context, *Sync_Request) (*Sync_Response, error)
	// SetPrivacy 设置朋友圈隐私
	SetPrivacy(context.Context, *SetPrivacy_Request) (*SetPrivacy_Response, error)
	mustEmbedUnimplementedMomentsServiceServer()
}

// UnimplementedMomentsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMomentsServiceServer struct{}

func (UnimplementedMomentsServiceServer) Timeline(context.Context, *Timeline_Request) (*Timeline_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Timeline not implemented")
}
func (UnimplementedMomentsServiceServer) UserPage(context.Context, *UserPage_Request) (*UserPage_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method UserPage not implemented")
}
func (UnimplementedMomentsServiceServer) Detail(context.Context, *Detail_Request) (*Detail_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Detail not implemented")
}
func (UnimplementedMomentsServiceServer) Comment(context.Context, *Comment_Request) (*Comment_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Comment not implemented")
}
func (UnimplementedMomentsServiceServer) Like(context.Context, *Like_Request) (*Like_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Like not implemented")
}
func (UnimplementedMomentsServiceServer) Unlike(context.Context, *Unlike_Request) (*Unlike_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlike not implemented")
}
func (UnimplementedMomentsServiceServer) Delete(context.Context, *Delete_Request) (*Delete_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedMomentsServiceServer) DeleteComment(context.Context, *DeleteComment_Request) (*DeleteComment_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedMomentsServiceServer) Post(context.Context, *Post_Request) (*Post_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedMomentsServiceServer) Upload(context.Context, *Upload_Request) (*Upload_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedMomentsServiceServer) Sync(context.Context, *Sync_Request) (*Sync_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedMomentsServiceServer) SetPrivacy(context.Context, *SetPrivacy_Request) (*SetPrivacy_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPrivacy not implemented")
}
func (UnimplementedMomentsServiceServer) mustEmbedUnimplementedMomentsServiceServer() {}
func (UnimplementedMomentsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMomentsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MomentsServiceServer will
// result in compilation errors.
type UnsafeMomentsServiceServer interface {
	mustEmbedUnimplementedMomentsServiceServer()
}

func RegisterMomentsServiceServer(s grpc.ServiceRegistrar, srv MomentsServiceServer) {
	// If the following call panics, it indicates UnimplementedMomentsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MomentsService_ServiceDesc, srv)
}

func _MomentsService_Timeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Timeline_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Timeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Timeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Timeline(ctx, req.(*Timeline_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_UserPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPage_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).UserPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_UserPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).UserPage(ctx, req.(*UserPage_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_Detail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Detail_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Detail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Detail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Detail(ctx, req.(*Detail_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_Comment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Comment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Comment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Comment(ctx, req.(*Comment_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_Like_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Like_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Like(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Like_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Like(ctx, req.(*Like_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_Unlike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Unlike_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Unlike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Unlike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Unlike(ctx, req.(*Unlike_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Delete_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Delete(ctx, req.(*Delete_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteComment_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).DeleteComment(ctx, req.(*DeleteComment_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Post_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Post(ctx, req.(*Post_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_Upload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Upload_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Upload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Upload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Upload(ctx, req.(*Upload_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sync_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).Sync(ctx, req.(*Sync_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _MomentsService_SetPrivacy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPrivacy_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MomentsServiceServer).SetPrivacy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MomentsService_SetPrivacy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MomentsServiceServer).SetPrivacy(ctx, req.(*SetPrivacy_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// MomentsService_ServiceDesc is the grpc.ServiceDesc for MomentsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MomentsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "moments.MomentsService",
	HandlerType: (*MomentsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Timeline",
			Handler:    _MomentsService_Timeline_Handler,
		},
		{
			MethodName: "UserPage",
			Handler:    _MomentsService_UserPage_Handler,
		},
		{
			MethodName: "Detail",
			Handler:    _MomentsService_Detail_Handler,
		},
		{
			MethodName: "Comment",
			Handler:    _MomentsService_Comment_Handler,
		},
		{
			MethodName: "Like",
			Handler:    _MomentsService_Like_Handler,
		},
		{
			MethodName: "Unlike",
			Handler:    _MomentsService_Unlike_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _MomentsService_Delete_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _MomentsService_DeleteComment_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _MomentsService_Post_Handler,
		},
		{
			MethodName: "Upload",
			Handler:    _MomentsService_Upload_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _MomentsService_Sync_Handler,
		},
		{
			MethodName: "SetPrivacy",
			Handler:    _MomentsService_SetPrivacy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "moments/moments.proto",
}
