// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: plugin/plugin.proto

package plugin

import (
	message "github.com/sbgayhub/golem/sdk/message"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// metadata 插件元数据
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                             // 名称
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`                         // 作者
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`                       // 版本
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`               // 描述
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`                    // 插件优先级
	Next          bool                   `protobuf:"varint,6,opt,name=next,proto3" json:"next,omitempty"`                            // 插件执行成功后，是否继续执行后续插件
	AlwaysRun     bool                   `protobuf:"varint,7,opt,name=always_run,json=alwaysRun,proto3" json:"always_run,omitempty"` // 一直运行，忽略会话劫持
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_plugin_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metadata) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Metadata) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Metadata) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Metadata) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *Metadata) GetNext() bool {
	if x != nil {
		return x.Next
	}
	return false
}

func (x *Metadata) GetAlwaysRun() bool {
	if x != nil {
		return x.AlwaysRun
	}
	return false
}

// Event 事件
type Event struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Topic  string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`   // 事件主题
	Sender string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"` // 事件发送者username
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Error
	//	*Event_System
	//	*Event_Message
	//	*Event_SessionExpired
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_plugin_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Event) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*Event_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *Event) GetSystem() string {
	if x != nil {
		if x, ok := x.Payload.(*Event_System); ok {
			return x.System
		}
	}
	return ""
}

func (x *Event) GetMessage() *message.Message {
	if x != nil {
		if x, ok := x.Payload.(*Event_Message); ok {
			return x.Message
		}
	}
	return nil
}

func (x *Event) GetSessionExpired() *SessionExpired {
	if x != nil {
		if x, ok := x.Payload.(*Event_SessionExpired); ok {
			return x.SessionExpired
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Error struct {
	Error string `protobuf:"bytes,3,opt,name=error,proto3,oneof"` // 错误消息
}

type Event_System struct {
	System string `protobuf:"bytes,4,opt,name=system,proto3,oneof"` // 系统消息
}

type Event_Message struct {
	Message *message.Message `protobuf:"bytes,5,opt,name=message,proto3,oneof"` // 消息
}

type Event_SessionExpired struct {
	SessionExpired *SessionExpired `protobuf:"bytes,6,opt,name=session_expired,json=sessionExpired,proto3,oneof"` // 会话到期
}

func (*Event_Error) isEvent_Payload() {}

func (*Event_System) isEvent_Payload() {}

func (*Event_Message) isEvent_Payload() {}

func (*Event_SessionExpired) isEvent_Payload() {}

// SessionExpired 会话到期事件
type SessionExpired struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`    // 劫持会话的插件ID
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // 关联的发送者(username)
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`                        // 到期原因: timeout
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionExpired) Reset() {
	*x = SessionExpired{}
	mi := &file_plugin_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionExpired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionExpired) ProtoMessage() {}

func (x *SessionExpired) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionExpired.ProtoReflect.Descriptor instead.
func (*SessionExpired) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *SessionExpired) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *SessionExpired) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionExpired) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GetMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadata) Reset() {
	*x = GetMetadata{}
	mi := &file_plugin_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadata) ProtoMessage() {}

func (x *GetMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadata.ProtoReflect.Descriptor instead.
func (*GetMetadata) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{3}
}

type OnCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCall) Reset() {
	*x = OnCall{}
	mi := &file_plugin_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCall) ProtoMessage() {}

func (x *OnCall) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCall.ProtoReflect.Descriptor instead.
func (*OnCall) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{4}
}

type OnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnEvent) Reset() {
	*x = OnEvent{}
	mi := &file_plugin_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEvent) ProtoMessage() {}

func (x *OnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEvent.ProtoReflect.Descriptor instead.
func (*OnEvent) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{5}
}

type OnCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCommand) Reset() {
	*x = OnCommand{}
	mi := &file_plugin_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCommand) ProtoMessage() {}

func (x *OnCommand) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCommand.ProtoReflect.Descriptor instead.
func (*OnCommand) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{6}
}

type GetCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilities) Reset() {
	*x = GetCapabilities{}
	mi := &file_plugin_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilities) ProtoMessage() {}

func (x *GetCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilities.ProtoReflect.Descriptor instead.
func (*GetCapabilities) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{7}
}

type GetSubscriptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptions) Reset() {
	*x = GetSubscriptions{}
	mi := &file_plugin_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptions) ProtoMessage() {}

func (x *GetSubscriptions) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptions.ProtoReflect.Descriptor instead.
func (*GetSubscriptions) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{8}
}

type GetCommands struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommands) Reset() {
	*x = GetCommands{}
	mi := &file_plugin_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommands) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommands) ProtoMessage() {}

func (x *GetCommands) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommands.ProtoReflect.Descriptor instead.
func (*GetCommands) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{9}
}

type OnLifecycle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnLifecycle) Reset() {
	*x = OnLifecycle{}
	mi := &file_plugin_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnLifecycle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLifecycle) ProtoMessage() {}

func (x *OnLifecycle) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLifecycle.ProtoReflect.Descriptor instead.
func (*OnLifecycle) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{10}
}

type SessionHold struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionHold) Reset() {
	*x = SessionHold{}
	mi := &file_plugin_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHold) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHold) ProtoMessage() {}

func (x *SessionHold) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHold.ProtoReflect.Descriptor instead.
func (*SessionHold) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{11}
}

type SessionRelease struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRelease) Reset() {
	*x = SessionRelease{}
	mi := &file_plugin_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRelease) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRelease) ProtoMessage() {}

func (x *SessionRelease) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRelease.ProtoReflect.Descriptor instead.
func (*SessionRelease) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{12}
}

type CallPlugin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPlugin) Reset() {
	*x = CallPlugin{}
	mi := &file_plugin_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPlugin) ProtoMessage() {}

func (x *CallPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPlugin.ProtoReflect.Descriptor instead.
func (*CallPlugin) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{13}
}

type GetAbilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbilities) Reset() {
	*x = GetAbilities{}
	mi := &file_plugin_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbilities) ProtoMessage() {}

func (x *GetAbilities) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbilities.ProtoReflect.Descriptor instead.
func (*GetAbilities) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{14}
}

type InjectAbility struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectAbility) Reset() {
	*x = InjectAbility{}
	mi := &file_plugin_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectAbility) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectAbility) ProtoMessage() {}

func (x *InjectAbility) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectAbility.ProtoReflect.Descriptor instead.
func (*InjectAbility) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{15}
}

type GetDefaultConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultConfig) Reset() {
	*x = GetDefaultConfig{}
	mi := &file_plugin_plugin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultConfig) ProtoMessage() {}

func (x *GetDefaultConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultConfig.ProtoReflect.Descriptor instead.
func (*GetDefaultConfig) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{16}
}

type SetConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfig) Reset() {
	*x = SetConfig{}
	mi := &file_plugin_plugin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfig) ProtoMessage() {}

func (x *SetConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfig.ProtoReflect.Descriptor instead.
func (*SetConfig) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{17}
}

type SaveConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfig) Reset() {
	*x = SaveConfig{}
	mi := &file_plugin_plugin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfig) ProtoMessage() {}

func (x *SaveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfig.ProtoReflect.Descriptor instead.
func (*SaveConfig) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{18}
}

type GetMetadata_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadata_Request) Reset() {
	*x = GetMetadata_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadata_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadata_Request) ProtoMessage() {}

func (x *GetMetadata_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadata_Request.ProtoReflect.Descriptor instead.
func (*GetMetadata_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{3, 0}
}

type GetMetadata_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Metadata              `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetadata_Response) Reset() {
	*x = GetMetadata_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetadata_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetadata_Response) ProtoMessage() {}

func (x *GetMetadata_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetadata_Response.ProtoReflect.Descriptor instead.
func (*GetMetadata_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{3, 1}
}

func (x *GetMetadata_Response) GetValue() *Metadata {
	if x != nil {
		return x.Value
	}
	return nil
}

type OnCall_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"` // 调用能力
	Args          []byte                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`             // 参数(JSON编码的map[string]string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCall_Request) Reset() {
	*x = OnCall_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCall_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCall_Request) ProtoMessage() {}

func (x *OnCall_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCall_Request.ProtoReflect.Descriptor instead.
func (*OnCall_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{4, 0}
}

func (x *OnCall_Request) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *OnCall_Request) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type OnCall_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mime          string                 `protobuf:"bytes,1,opt,name=mime,proto3" json:"mime,omitempty"`       // 返回数据类型
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`       // 返回数据
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCall_Response) Reset() {
	*x = OnCall_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCall_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCall_Response) ProtoMessage() {}

func (x *OnCall_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCall_Response.ProtoReflect.Descriptor instead.
func (*OnCall_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{4, 1}
}

func (x *OnCall_Response) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *OnCall_Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OnCall_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OnEvent_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Event                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnEvent_Request) Reset() {
	*x = OnEvent_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnEvent_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEvent_Request) ProtoMessage() {}

func (x *OnEvent_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEvent_Request.ProtoReflect.Descriptor instead.
func (*OnEvent_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{5, 0}
}

func (x *OnEvent_Request) GetValue() *Event {
	if x != nil {
		return x.Value
	}
	return nil
}

type OnEvent_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`  // 结果
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnEvent_Response) Reset() {
	*x = OnEvent_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnEvent_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnEvent_Response) ProtoMessage() {}

func (x *OnEvent_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnEvent_Response.ProtoReflect.Descriptor instead.
func (*OnEvent_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{5, 1}
}

func (x *OnEvent_Response) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *OnEvent_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OnCommand_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *Command               `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCommand_Request) Reset() {
	*x = OnCommand_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCommand_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCommand_Request) ProtoMessage() {}

func (x *OnCommand_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCommand_Request.ProtoReflect.Descriptor instead.
func (*OnCommand_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{6, 0}
}

func (x *OnCommand_Request) GetValue() *Command {
	if x != nil {
		return x.Value
	}
	return nil
}

type OnCommand_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`   // 结果
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnCommand_Response) Reset() {
	*x = OnCommand_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnCommand_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnCommand_Response) ProtoMessage() {}

func (x *OnCommand_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnCommand_Response.ProtoReflect.Descriptor instead.
func (*OnCommand_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{6, 1}
}

func (x *OnCommand_Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *OnCommand_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCapabilities_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilities_Request) Reset() {
	*x = GetCapabilities_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilities_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilities_Request) ProtoMessage() {}

func (x *GetCapabilities_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilities_Request.ProtoReflect.Descriptor instead.
func (*GetCapabilities_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{7, 0}
}

type GetCapabilities_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCapabilities_Response) Reset() {
	*x = GetCapabilities_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCapabilities_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilities_Response) ProtoMessage() {}

func (x *GetCapabilities_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilities_Response.ProtoReflect.Descriptor instead.
func (*GetCapabilities_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{7, 1}
}

func (x *GetCapabilities_Response) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetSubscriptions_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptions_Request) Reset() {
	*x = GetSubscriptions_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptions_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptions_Request) ProtoMessage() {}

func (x *GetSubscriptions_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptions_Request.ProtoReflect.Descriptor instead.
func (*GetSubscriptions_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{8, 0}
}

type GetSubscriptions_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSubscriptions_Response) Reset() {
	*x = GetSubscriptions_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSubscriptions_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSubscriptions_Response) ProtoMessage() {}

func (x *GetSubscriptions_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSubscriptions_Response.ProtoReflect.Descriptor instead.
func (*GetSubscriptions_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{8, 1}
}

func (x *GetSubscriptions_Response) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type GetCommands_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommands_Request) Reset() {
	*x = GetCommands_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommands_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommands_Request) ProtoMessage() {}

func (x *GetCommands_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommands_Request.ProtoReflect.Descriptor instead.
func (*GetCommands_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{9, 0}
}

type GetCommands_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	Schemas       []*CommandSchema       `protobuf:"bytes,2,rep,name=schemas,proto3" json:"schemas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommands_Response) Reset() {
	*x = GetCommands_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommands_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommands_Response) ProtoMessage() {}

func (x *GetCommands_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommands_Response.ProtoReflect.Descriptor instead.
func (*GetCommands_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{9, 1}
}

func (x *GetCommands_Response) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *GetCommands_Response) GetSchemas() []*CommandSchema {
	if x != nil {
		return x.Schemas
	}
	return nil
}

type OnLifecycle_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnLifecycle_Request) Reset() {
	*x = OnLifecycle_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnLifecycle_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLifecycle_Request) ProtoMessage() {}

func (x *OnLifecycle_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLifecycle_Request.ProtoReflect.Descriptor instead.
func (*OnLifecycle_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{10, 0}
}

type OnLifecycle_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnLifecycle_Response) Reset() {
	*x = OnLifecycle_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnLifecycle_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnLifecycle_Response) ProtoMessage() {}

func (x *OnLifecycle_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnLifecycle_Response.ProtoReflect.Descriptor instead.
func (*OnLifecycle_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{10, 1}
}

func (x *OnLifecycle_Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SessionHold_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件ID
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`                     // 会话关联的发送者(username)
	Duration      uint32                 `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`                // 保持时长(秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionHold_Request) Reset() {
	*x = SessionHold_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHold_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHold_Request) ProtoMessage() {}

func (x *SessionHold_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHold_Request.ProtoReflect.Descriptor instead.
func (*SessionHold_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{11, 0}
}

func (x *SessionHold_Request) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *SessionHold_Request) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *SessionHold_Request) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type SessionHold_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionHold_Response) Reset() {
	*x = SessionHold_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionHold_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionHold_Response) ProtoMessage() {}

func (x *SessionHold_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionHold_Response.ProtoReflect.Descriptor instead.
func (*SessionHold_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{11, 1}
}

func (x *SessionHold_Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SessionRelease_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件ID
	Sender        string                 `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`                     // 会话关联的发送者(username)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRelease_Request) Reset() {
	*x = SessionRelease_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRelease_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRelease_Request) ProtoMessage() {}

func (x *SessionRelease_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRelease_Request.ProtoReflect.Descriptor instead.
func (*SessionRelease_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{12, 0}
}

func (x *SessionRelease_Request) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *SessionRelease_Request) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

type SessionRelease_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRelease_Response) Reset() {
	*x = SessionRelease_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRelease_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRelease_Response) ProtoMessage() {}

func (x *SessionRelease_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRelease_Response.ProtoReflect.Descriptor instead.
func (*SessionRelease_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{12, 1}
}

func (x *SessionRelease_Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type CallPlugin_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capability    string                 `protobuf:"bytes,1,opt,name=capability,proto3" json:"capability,omitempty"` // 调用能力
	Args          []byte                 `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`             // 参数(JSON编码的map[string]string)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPlugin_Request) Reset() {
	*x = CallPlugin_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPlugin_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPlugin_Request) ProtoMessage() {}

func (x *CallPlugin_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPlugin_Request.ProtoReflect.Descriptor instead.
func (*CallPlugin_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{13, 0}
}

func (x *CallPlugin_Request) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *CallPlugin_Request) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

type CallPlugin_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mime          string                 `protobuf:"bytes,1,opt,name=mime,proto3" json:"mime,omitempty"`       // 返回数据类型
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`       // 返回数据
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallPlugin_Response) Reset() {
	*x = CallPlugin_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallPlugin_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallPlugin_Response) ProtoMessage() {}

func (x *CallPlugin_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallPlugin_Response.ProtoReflect.Descriptor instead.
func (*CallPlugin_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{13, 1}
}

func (x *CallPlugin_Response) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *CallPlugin_Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *CallPlugin_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAbilities_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbilities_Request) Reset() {
	*x = GetAbilities_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbilities_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbilities_Request) ProtoMessage() {}

func (x *GetAbilities_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbilities_Request.ProtoReflect.Descriptor instead.
func (*GetAbilities_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{14, 0}
}

type GetAbilities_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"` // 插件的需要能力列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAbilities_Response) Reset() {
	*x = GetAbilities_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAbilities_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAbilities_Response) ProtoMessage() {}

func (x *GetAbilities_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAbilities_Response.ProtoReflect.Descriptor instead.
func (*GetAbilities_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{14, 1}
}

func (x *GetAbilities_Response) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type InjectAbility_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cdn           uint32                 `protobuf:"varint,1,opt,name=cdn,proto3" json:"cdn,omitempty"`
	Contact       uint32                 `protobuf:"varint,2,opt,name=contact,proto3" json:"contact,omitempty"`    // 联系人管理服务地址
	Message       uint32                 `protobuf:"varint,3,opt,name=message,proto3" json:"message,omitempty"`    // 消息发送服务地址
	Chatroom      uint32                 `protobuf:"varint,4,opt,name=chatroom,proto3" json:"chatroom,omitempty"`  // 群组管理服务地址
	Session       uint32                 `protobuf:"varint,5,opt,name=session,proto3" json:"session,omitempty"`    // 会话管理服务地址
	Caller        uint32                 `protobuf:"varint,6,opt,name=caller,proto3" json:"caller,omitempty"`      // 插件调用服务地址
	Config        uint32                 `protobuf:"varint,7,opt,name=config,proto3" json:"config,omitempty"`      // 配置管理服务地址
	Favor         uint32                 `protobuf:"varint,8,opt,name=favor,proto3" json:"favor,omitempty"`        // 收藏服务地址
	Label         uint32                 `protobuf:"varint,9,opt,name=label,proto3" json:"label,omitempty"`        // 标签服务地址
	Login         uint32                 `protobuf:"varint,10,opt,name=login,proto3" json:"login,omitempty"`       // 登录服务地址
	Miniapp       uint32                 `protobuf:"varint,11,opt,name=miniapp,proto3" json:"miniapp,omitempty"`   // 小程序服务地址
	Moments       uint32                 `protobuf:"varint,12,opt,name=moments,proto3" json:"moments,omitempty"`   // 朋友圈服务地址
	Official      uint32                 `protobuf:"varint,13,opt,name=official,proto3" json:"official,omitempty"` // 公众号服务地址
	Payment       uint32                 `protobuf:"varint,14,opt,name=payment,proto3" json:"payment,omitempty"`   // 支付服务地址
	Report        uint32                 `protobuf:"varint,15,opt,name=report,proto3" json:"report,omitempty"`     // 状态通知服务地址
	User          uint32                 `protobuf:"varint,16,opt,name=user,proto3" json:"user,omitempty"`         // 用户服务地址
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectAbility_Request) Reset() {
	*x = InjectAbility_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectAbility_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectAbility_Request) ProtoMessage() {}

func (x *InjectAbility_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectAbility_Request.ProtoReflect.Descriptor instead.
func (*InjectAbility_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{15, 0}
}

func (x *InjectAbility_Request) GetCdn() uint32 {
	if x != nil {
		return x.Cdn
	}
	return 0
}

func (x *InjectAbility_Request) GetContact() uint32 {
	if x != nil {
		return x.Contact
	}
	return 0
}

func (x *InjectAbility_Request) GetMessage() uint32 {
	if x != nil {
		return x.Message
	}
	return 0
}

func (x *InjectAbility_Request) GetChatroom() uint32 {
	if x != nil {
		return x.Chatroom
	}
	return 0
}

func (x *InjectAbility_Request) GetSession() uint32 {
	if x != nil {
		return x.Session
	}
	return 0
}

func (x *InjectAbility_Request) GetCaller() uint32 {
	if x != nil {
		return x.Caller
	}
	return 0
}

func (x *InjectAbility_Request) GetConfig() uint32 {
	if x != nil {
		return x.Config
	}
	return 0
}

func (x *InjectAbility_Request) GetFavor() uint32 {
	if x != nil {
		return x.Favor
	}
	return 0
}

func (x *InjectAbility_Request) GetLabel() uint32 {
	if x != nil {
		return x.Label
	}
	return 0
}

func (x *InjectAbility_Request) GetLogin() uint32 {
	if x != nil {
		return x.Login
	}
	return 0
}

func (x *InjectAbility_Request) GetMiniapp() uint32 {
	if x != nil {
		return x.Miniapp
	}
	return 0
}

func (x *InjectAbility_Request) GetMoments() uint32 {
	if x != nil {
		return x.Moments
	}
	return 0
}

func (x *InjectAbility_Request) GetOfficial() uint32 {
	if x != nil {
		return x.Official
	}
	return 0
}

func (x *InjectAbility_Request) GetPayment() uint32 {
	if x != nil {
		return x.Payment
	}
	return 0
}

func (x *InjectAbility_Request) GetReport() uint32 {
	if x != nil {
		return x.Report
	}
	return 0
}

func (x *InjectAbility_Request) GetUser() uint32 {
	if x != nil {
		return x.User
	}
	return 0
}

type InjectAbility_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InjectAbility_Response) Reset() {
	*x = InjectAbility_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InjectAbility_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InjectAbility_Response) ProtoMessage() {}

func (x *InjectAbility_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InjectAbility_Response.ProtoReflect.Descriptor instead.
func (*InjectAbility_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{15, 1}
}

func (x *InjectAbility_Response) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type GetDefaultConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultConfig_Request) Reset() {
	*x = GetDefaultConfig_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultConfig_Request) ProtoMessage() {}

func (x *GetDefaultConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultConfig_Request.ProtoReflect.Descriptor instead.
func (*GetDefaultConfig_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{16, 0}
}

type GetDefaultConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"` // 插件配置数据二进制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDefaultConfig_Response) Reset() {
	*x = GetDefaultConfig_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDefaultConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDefaultConfig_Response) ProtoMessage() {}

func (x *GetDefaultConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDefaultConfig_Response.ProtoReflect.Descriptor instead.
func (*GetDefaultConfig_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{16, 1}
}

func (x *GetDefaultConfig_Response) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3,oneof" json:"data,omitempty"` // 插件配置数据二进制
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfig_Request) Reset() {
	*x = SetConfig_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfig_Request) ProtoMessage() {}

func (x *SetConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfig_Request.ProtoReflect.Descriptor instead.
func (*SetConfig_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{17, 0}
}

func (x *SetConfig_Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        bool                   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"` // 配置注入结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfig_Response) Reset() {
	*x = SetConfig_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfig_Response) ProtoMessage() {}

func (x *SetConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfig_Response.ProtoReflect.Descriptor instead.
func (*SetConfig_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{17, 1}
}

func (x *SetConfig_Response) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

type SaveConfig_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"` // 插件ID
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                         // 插件配置数据(JSON)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfig_Request) Reset() {
	*x = SaveConfig_Request{}
	mi := &file_plugin_plugin_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfig_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfig_Request) ProtoMessage() {}

func (x *SaveConfig_Request) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfig_Request.ProtoReflect.Descriptor instead.
func (*SaveConfig_Request) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{18, 0}
}

func (x *SaveConfig_Request) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *SaveConfig_Request) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type SaveConfig_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"` // 错误信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveConfig_Response) Reset() {
	*x = SaveConfig_Response{}
	mi := &file_plugin_plugin_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveConfig_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveConfig_Response) ProtoMessage() {}

func (x *SaveConfig_Response) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_plugin_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveConfig_Response.ProtoReflect.Descriptor instead.
func (*SaveConfig_Response) Descriptor() ([]byte, []int) {
	return file_plugin_plugin_proto_rawDescGZIP(), []int{18, 1}
}

func (x *SaveConfig_Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_plugin_plugin_proto protoreflect.FileDescriptor

const file_plugin_plugin_proto_rawDesc = "" +
	"\n" +
	"\x13plugin/plugin.proto\x12\x06plugin\x1a\x13message/types.proto\x1a\x14plugin/command.proto\"\xc1\x01\n" +
	"\bMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04next\x18\x06 \x01(\bR\x04next\x12\x1d\n" +
	"\n" +
	"always_run\x18\a \x01(\bR\talwaysRun\"\xe3\x01\n" +
	"\x05Event\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x16\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x12\x18\n" +
	"\x06system\x18\x04 \x01(\tH\x00R\x06system\x12,\n" +
	"\amessage\x18\x05 \x01(\v2\x10.message.MessageH\x00R\amessage\x12A\n" +
	"\x0fsession_expired\x18\x06 \x01(\v2\x16.plugin.SessionExpiredH\x00R\x0esessionExpiredB\t\n" +
	"\apayload\"d\n" +
	"\x0eSessionExpired\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"L\n" +
	"\vGetMetadata\x1a\t\n" +
	"\aRequest\x1a2\n" +
	"\bResponse\x12&\n" +
	"\x05value\x18\x01 \x01(\v2\x10.plugin.MetadataR\x05value\"\x95\x01\n" +
	"\x06OnCall\x1a=\n" +
	"\aRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x12\n" +
	"\x04args\x18\x02 \x01(\fR\x04args\x1aL\n" +
	"\bResponse\x12\x12\n" +
	"\x04mime\x18\x01 \x01(\tR\x04mime\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"w\n" +
	"\aOnEvent\x1a.\n" +
	"\aRequest\x12#\n" +
	"\x05value\x18\x01 \x01(\v2\r.plugin.EventR\x05value\x1a<\n" +
	"\bResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\tOnCommand\x1a0\n" +
	"\aRequest\x12%\n" +
	"\x05value\x18\x01 \x01(\v2\x0f.plugin.CommandR\x05value\x1a<\n" +
	"\bResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"@\n" +
	"\x0fGetCapabilities\x1a\t\n" +
	"\aRequest\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"A\n" +
	"\x10GetSubscriptions\x1a\t\n" +
	"\aRequest\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"m\n" +
	"\vGetCommands\x1a\t\n" +
	"\aRequest\x1aS\n" +
	"\bResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x12/\n" +
	"\aschemas\x18\x02 \x03(\v2\x15.plugin.CommandSchemaR\aschemas\":\n" +
	"\vOnLifecycle\x1a\t\n" +
	"\aRequest\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x8b\x01\n" +
	"\vSessionHold\x1aZ\n" +
	"\aRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\rR\bduration\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"r\n" +
	"\x0eSessionRelease\x1a>\n" +
	"\aRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x16\n" +
	"\x06sender\x18\x02 \x01(\tR\x06sender\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"\x99\x01\n" +
	"\n" +
	"CallPlugin\x1a=\n" +
	"\aRequest\x12\x1e\n" +
	"\n" +
	"capability\x18\x01 \x01(\tR\n" +
	"capability\x12\x12\n" +
	"\x04args\x18\x02 \x01(\fR\x04args\x1aL\n" +
	"\bResponse\x12\x12\n" +
	"\x04mime\x18\x01 \x01(\tR\x04mime\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"=\n" +
	"\fGetAbilities\x1a\t\n" +
	"\aRequest\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xc1\x03\n" +
	"\rInjectAbility\x1a\x8d\x03\n" +
	"\aRequest\x12\x10\n" +
	"\x03cdn\x18\x01 \x01(\rR\x03cdn\x12\x18\n" +
	"\acontact\x18\x02 \x01(\rR\acontact\x12\x18\n" +
	"\amessage\x18\x03 \x01(\rR\amessage\x12\x1a\n" +
	"\bchatroom\x18\x04 \x01(\rR\bchatroom\x12\x18\n" +
	"\asession\x18\x05 \x01(\rR\asession\x12\x16\n" +
	"\x06caller\x18\x06 \x01(\rR\x06caller\x12\x16\n" +
	"\x06config\x18\a \x01(\rR\x06config\x12\x14\n" +
	"\x05favor\x18\b \x01(\rR\x05favor\x12\x14\n" +
	"\x05label\x18\t \x01(\rR\x05label\x12\x14\n" +
	"\x05login\x18\n" +
	" \x01(\rR\x05login\x12\x18\n" +
	"\aminiapp\x18\v \x01(\rR\aminiapp\x12\x18\n" +
	"\amoments\x18\f \x01(\rR\amoments\x12\x1a\n" +
	"\bofficial\x18\r \x01(\rR\bofficial\x12\x18\n" +
	"\apayment\x18\x0e \x01(\rR\apayment\x12\x16\n" +
	"\x06report\x18\x0f \x01(\rR\x06report\x12\x12\n" +
	"\x04user\x18\x10 \x01(\rR\x04user\x1a \n" +
	"\bResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\"K\n" +
	"\x10GetDefaultConfig\x1a\t\n" +
	"\aRequest\x1a,\n" +
	"\bResponse\x12\x17\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\"\\\n" +
	"\tSetConfig\x1a+\n" +
	"\aRequest\x12\x17\n" +
	"\x04data\x18\x01 \x01(\fH\x00R\x04data\x88\x01\x01B\a\n" +
	"\x05_data\x1a\"\n" +
	"\bResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\bR\x06result\"n\n" +
	"\n" +
	"SaveConfig\x1a:\n" +
	"\aRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x1a$\n" +
	"\bResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb8\x02\n" +
	"\vHostService\x12H\n" +
	"\vSessionHold\x12\x1b.plugin.SessionHold.Request\x1a\x1c.plugin.SessionHold.Response\x12Q\n" +
	"\x0eSessionRelease\x12\x1e.plugin.SessionRelease.Request\x1a\x1f.plugin.SessionRelease.Response\x12E\n" +
	"\n" +
	"CallPlugin\x12\x1a.plugin.CallPlugin.Request\x1a\x1b.plugin.CallPlugin.Response\x12E\n" +
	"\n" +
	"SaveConfig\x12\x1a.plugin.SaveConfig.Request\x1a\x1b.plugin.SaveConfig.Response2\xe8\b\n" +
	"\rPluginService\x12H\n" +
	"\vGetMetadata\x12\x1b.plugin.GetMetadata.Request\x1a\x1c.plugin.GetMetadata.Response\x129\n" +
	"\x06OnCall\x12\x16.plugin.OnCall.Request\x1a\x17.plugin.OnCall.Response\x12<\n" +
	"\aOnEvent\x12\x17.plugin.OnEvent.Request\x1a\x18.plugin.OnEvent.Response\x12B\n" +
	"\tOnCommand\x12\x19.plugin.OnCommand.Request\x1a\x1a.plugin.OnCommand.Response\x12T\n" +
	"\x0fGetCapabilities\x12\x1f.plugin.GetCapabilities.Request\x1a .plugin.GetCapabilities.Response\x12W\n" +
	"\x10GetSubscriptions\x12 .plugin.GetSubscriptions.Request\x1a!.plugin.GetSubscriptions.Response\x12H\n" +
	"\vGetCommands\x12\x1b.plugin.GetCommands.Request\x1a\x1c.plugin.GetCommands.Response\x12C\n" +
	"\x06OnLoad\x12\x1b.plugin.OnLifecycle.Request\x1a\x1c.plugin.OnLifecycle.Response\x12E\n" +
	"\bOnUnload\x12\x1b.plugin.OnLifecycle.Request\x1a\x1c.plugin.OnLifecycle.Response\x12F\n" +
	"\tOnEnabled\x12\x1b.plugin.OnLifecycle.Request\x1a\x1c.plugin.OnLifecycle.Response\x12G\n" +
	"\n" +
	"OnDisabled\x12\x1b.plugin.OnLifecycle.Request\x1a\x1c.plugin.OnLifecycle.Response\x12K\n" +
	"\fGetAbilities\x12\x1c.plugin.GetAbilities.Request\x1a\x1d.plugin.GetAbilities.Response\x12P\n" +
	"\x0fInjectAbilities\x12\x1d.plugin.InjectAbility.Request\x1a\x1e.plugin.InjectAbility.Response\x12W\n" +
	"\x10GetDefaultConfig\x12 .plugin.GetDefaultConfig.Request\x1a!.plugin.GetDefaultConfig.Response\x12B\n" +
	"\tSetConfig\x12\x19.plugin.SetConfig.Request\x1a\x1a.plugin.SetConfig.ResponseBw\n" +
	"\n" +
	"com.pluginB\vPluginProtoP\x01Z$github.com/sbgayhub/golem/sdk/plugin\xa2\x02\x03PXX\xaa\x02\x06Plugin\xca\x02\x06Plugin\xe2\x02\x12Plugin\\GPBMetadata\xea\x02\x06Pluginb\x06proto3"

var (
	file_plugin_plugin_proto_rawDescOnce sync.Once
	file_plugin_plugin_proto_rawDescData []byte
)

func file_plugin_plugin_proto_rawDescGZIP() []byte {
	file_plugin_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_plugin_proto_rawDesc), len(file_plugin_plugin_proto_rawDesc)))
	})
	return file_plugin_plugin_proto_rawDescData
}

var file_plugin_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 51)
var file_plugin_plugin_proto_goTypes = []any{
	(*Metadata)(nil),                  // 0: plugin.Metadata
	(*Event)(nil),                     // 1: plugin.Event
	(*SessionExpired)(nil),            // 2: plugin.SessionExpired
	(*GetMetadata)(nil),               // 3: plugin.GetMetadata
	(*OnCall)(nil),                    // 4: plugin.OnCall
	(*OnEvent)(nil),                   // 5: plugin.OnEvent
	(*OnCommand)(nil),                 // 6: plugin.OnCommand
	(*GetCapabilities)(nil),           // 7: plugin.GetCapabilities
	(*GetSubscriptions)(nil),          // 8: plugin.GetSubscriptions
	(*GetCommands)(nil),               // 9: plugin.GetCommands
	(*OnLifecycle)(nil),               // 10: plugin.OnLifecycle
	(*SessionHold)(nil),               // 11: plugin.SessionHold
	(*SessionRelease)(nil),            // 12: plugin.SessionRelease
	(*CallPlugin)(nil),                // 13: plugin.CallPlugin
	(*GetAbilities)(nil),              // 14: plugin.GetAbilities
	(*InjectAbility)(nil),             // 15: plugin.InjectAbility
	(*GetDefaultConfig)(nil),          // 16: plugin.GetDefaultConfig
	(*SetConfig)(nil),                 // 17: plugin.SetConfig
	(*SaveConfig)(nil),                // 18: plugin.SaveConfig
	(*GetMetadata_Request)(nil),       // 19: plugin.GetMetadata.Request
	(*GetMetadata_Response)(nil),      // 20: plugin.GetMetadata.Response
	(*OnCall_Request)(nil),            // 21: plugin.OnCall.Request
	(*OnCall_Response)(nil),           // 22: plugin.OnCall.Response
	(*OnEvent_Request)(nil),           // 23: plugin.OnEvent.Request
	(*OnEvent_Response)(nil),          // 24: plugin.OnEvent.Response
	(*OnCommand_Request)(nil),         // 25: plugin.OnCommand.Request
	(*OnCommand_Response)(nil),        // 26: plugin.OnCommand.Response
	(*GetCapabilities_Request)(nil),   // 27: plugin.GetCapabilities.Request
	(*GetCapabilities_Response)(nil),  // 28: plugin.GetCapabilities.Response
	(*GetSubscriptions_Request)(nil),  // 29: plugin.GetSubscriptions.Request
	(*GetSubscriptions_Response)(nil), // 30: plugin.GetSubscriptions.Response
	(*GetCommands_Request)(nil),       // 31: plugin.GetCommands.Request
	(*GetCommands_Response)(nil),      // 32: plugin.GetCommands.Response
	(*OnLifecycle_Request)(nil),       // 33: plugin.OnLifecycle.Request
	(*OnLifecycle_Response)(nil),      // 34: plugin.OnLifecycle.Response
	(*SessionHold_Request)(nil),       // 35: plugin.SessionHold.Request
	(*SessionHold_Response)(nil),      // 36: plugin.SessionHold.Response
	(*SessionRelease_Request)(nil),    // 37: plugin.SessionRelease.Request
	(*SessionRelease_Response)(nil),   // 38: plugin.SessionRelease.Response
	(*CallPlugin_Request)(nil),        // 39: plugin.CallPlugin.Request
	(*CallPlugin_Response)(nil),       // 40: plugin.CallPlugin.Response
	(*GetAbilities_Request)(nil),      // 41: plugin.GetAbilities.Request
	(*GetAbilities_Response)(nil),     // 42: plugin.GetAbilities.Response
	(*InjectAbility_Request)(nil),     // 43: plugin.InjectAbility.Request
	(*InjectAbility_Response)(nil),    // 44: plugin.InjectAbility.Response
	(*GetDefaultConfig_Request)(nil),  // 45: plugin.GetDefaultConfig.Request
	(*GetDefaultConfig_Response)(nil), // 46: plugin.GetDefaultConfig.Response
	(*SetConfig_Request)(nil),         // 47: plugin.SetConfig.Request
	(*SetConfig_Response)(nil),        // 48: plugin.SetConfig.Response
	(*SaveConfig_Request)(nil),        // 49: plugin.SaveConfig.Request
	(*SaveConfig_Response)(nil),       // 50: plugin.SaveConfig.Response
	(*message.Message)(nil),           // 51: message.Message
	(*Command)(nil),                   // 52: plugin.Command
	(*CommandSchema)(nil),             // 53: plugin.CommandSchema
}
var file_plugin_plugin_proto_depIdxs = []int32{
	51, // 0: plugin.Event.message:type_name -> message.Message
	2,  // 1: plugin.Event.session_expired:type_name -> plugin.SessionExpired
	0,  // 2: plugin.GetMetadata.Response.value:type_name -> plugin.Metadata
	1,  // 3: plugin.OnEvent.Request.value:type_name -> plugin.Event
	52, // 4: plugin.OnCommand.Request.value:type_name -> plugin.Command
	53, // 5: plugin.GetCommands.Response.schemas:type_name -> plugin.CommandSchema
	35, // 6: plugin.HostService.SessionHold:input_type -> plugin.SessionHold.Request
	37, // 7: plugin.HostService.SessionRelease:input_type -> plugin.SessionRelease.Request
	39, // 8: plugin.HostService.CallPlugin:input_type -> plugin.CallPlugin.Request
	49, // 9: plugin.HostService.SaveConfig:input_type -> plugin.SaveConfig.Request
	19, // 10: plugin.PluginService.GetMetadata:input_type -> plugin.GetMetadata.Request
	21, // 11: plugin.PluginService.OnCall:input_type -> plugin.OnCall.Request
	23, // 12: plugin.PluginService.OnEvent:input_type -> plugin.OnEvent.Request
	25, // 13: plugin.PluginService.OnCommand:input_type -> plugin.OnCommand.Request
	27, // 14: plugin.PluginService.GetCapabilities:input_type -> plugin.GetCapabilities.Request
	29, // 15: plugin.PluginService.GetSubscriptions:input_type -> plugin.GetSubscriptions.Request
	31, // 16: plugin.PluginService.GetCommands:input_type -> plugin.GetCommands.Request
	33, // 17: plugin.PluginService.OnLoad:input_type -> plugin.OnLifecycle.Request
	33, // 18: plugin.PluginService.OnUnload:input_type -> plugin.OnLifecycle.Request
	33, // 19: plugin.PluginService.OnEnabled:input_type -> plugin.OnLifecycle.Request
	33, // 20: plugin.PluginService.OnDisabled:input_type -> plugin.OnLifecycle.Request
	41, // 21: plugin.PluginService.GetAbilities:input_type -> plugin.GetAbilities.Request
	43, // 22: plugin.PluginService.InjectAbilities:input_type -> plugin.InjectAbility.Request
	45, // 23: plugin.PluginService.GetDefaultConfig:input_type -> plugin.GetDefaultConfig.Request
	47, // 24: plugin.PluginService.SetConfig:input_type -> plugin.SetConfig.Request
	36, // 25: plugin.HostService.SessionHold:output_type -> plugin.SessionHold.Response
	38, // 26: plugin.HostService.SessionRelease:output_type -> plugin.SessionRelease.Response
	40, // 27: plugin.HostService.CallPlugin:output_type -> plugin.CallPlugin.Response
	50, // 28: plugin.HostService.SaveConfig:output_type -> plugin.SaveConfig.Response
	20, // 29: plugin.PluginService.GetMetadata:output_type -> plugin.GetMetadata.Response
	22, // 30: plugin.PluginService.OnCall:output_type -> plugin.OnCall.Response
	24, // 31: plugin.PluginService.OnEvent:output_type -> plugin.OnEvent.Response
	26, // 32: plugin.PluginService.OnCommand:output_type -> plugin.OnCommand.Response
	28, // 33: plugin.PluginService.GetCapabilities:output_type -> plugin.GetCapabilities.Response
	30, // 34: plugin.PluginService.GetSubscriptions:output_type -> plugin.GetSubscriptions.Response
	32, // 35: plugin.PluginService.GetCommands:output_type -> plugin.GetCommands.Response
	34, // 36: plugin.PluginService.OnLoad:output_type -> plugin.OnLifecycle.Response
	34, // 37: plugin.PluginService.OnUnload:output_type -> plugin.OnLifecycle.Response
	34, // 38: plugin.PluginService.OnEnabled:output_type -> plugin.OnLifecycle.Response
	34, // 39: plugin.PluginService.OnDisabled:output_type -> plugin.OnLifecycle.Response
	42, // 40: plugin.PluginService.GetAbilities:output_type -> plugin.GetAbilities.Response
	44, // 41: plugin.PluginService.InjectAbilities:output_type -> plugin.InjectAbility.Response
	46, // 42: plugin.PluginService.GetDefaultConfig:output_type -> plugin.GetDefaultConfig.Response
	48, // 43: plugin.PluginService.SetConfig:output_type -> plugin.SetConfig.Response
	25, // [25:44] is the sub-list for method output_type
	6,  // [6:25] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_plugin_plugin_proto_init() }
func file_plugin_plugin_proto_init() {
	if File_plugin_plugin_proto != nil {
		return
	}
	file_plugin_command_proto_init()
	file_plugin_plugin_proto_msgTypes[1].OneofWrappers = []any{
		(*Event_Error)(nil),
		(*Event_System)(nil),
		(*Event_Message)(nil),
		(*Event_SessionExpired)(nil),
	}
	file_plugin_plugin_proto_msgTypes[46].OneofWrappers = []any{}
	file_plugin_plugin_proto_msgTypes[47].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_plugin_proto_rawDesc), len(file_plugin_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   51,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_plugin_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_plugin_proto_msgTypes,
	}.Build()
	File_plugin_plugin_proto = out.File
	file_plugin_plugin_proto_goTypes = nil
	file_plugin_plugin_proto_depIdxs = nil
}
