// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/login/login_api.proto

package loginapi

import (
	base "github.com/sbgayhub/golem/host/api/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperateResponse 通用操作响应
type OperateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateResponse) Reset() {
	*x = OperateResponse{}
	mi := &file_api_login_login_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateResponse) ProtoMessage() {}

func (x *OperateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_login_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateResponse.ProtoReflect.Descriptor instead.
func (*OperateResponse) Descriptor() ([]byte, []int) {
	return file_api_login_login_api_proto_rawDescGZIP(), []int{0}
}

func (x *OperateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OperateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// QRCodeResult 二维码结果（镜像 golem GetQRCodeResponse，移除 base_response）
type QRCodeResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Qrcode        *base.Buffer           `protobuf:"bytes,2,opt,name=qrcode,proto3,oneof" json:"qrcode,omitempty"`                               // 二维码数据（对应 golem field 2）
	Uuid          *string                `protobuf:"bytes,3,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`                                   // 二维码 UUID（对应 golem field 3）
	CheckTime     *uint32                `protobuf:"varint,4,opt,name=check_time,json=checkTime,proto3,oneof" json:"check_time,omitempty"`       // 检查间隔时间（对应 golem field 4）
	NotifyKey     *base.Buffer           `protobuf:"bytes,5,opt,name=notify_key,json=notifyKey,proto3,oneof" json:"notify_key,omitempty"`        // 通知密钥（对应 golem field 5）
	ExpiredTime   *uint32                `protobuf:"varint,6,opt,name=expired_time,json=expiredTime,proto3,oneof" json:"expired_time,omitempty"` // 过期时间（对应 golem field 6）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QRCodeResult) Reset() {
	*x = QRCodeResult{}
	mi := &file_api_login_login_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QRCodeResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QRCodeResult) ProtoMessage() {}

func (x *QRCodeResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_login_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QRCodeResult.ProtoReflect.Descriptor instead.
func (*QRCodeResult) Descriptor() ([]byte, []int) {
	return file_api_login_login_api_proto_rawDescGZIP(), []int{1}
}

func (x *QRCodeResult) GetQrcode() *base.Buffer {
	if x != nil {
		return x.Qrcode
	}
	return nil
}

func (x *QRCodeResult) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

func (x *QRCodeResult) GetCheckTime() uint32 {
	if x != nil && x.CheckTime != nil {
		return *x.CheckTime
	}
	return 0
}

func (x *QRCodeResult) GetNotifyKey() *base.Buffer {
	if x != nil {
		return x.NotifyKey
	}
	return nil
}

func (x *QRCodeResult) GetExpiredTime() uint32 {
	if x != nil && x.ExpiredTime != nil {
		return *x.ExpiredTime
	}
	return 0
}

// InitResponse 初始化响应
type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_api_login_login_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_login_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_api_login_login_api_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// HeartBeatResponse 心跳响应（镜像 golem HeartBeatResponse，移除 base_response）
type HeartBeatResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	NextTime                  *uint32                `protobuf:"varint,2,opt,name=next_time,json=nextTime,proto3,oneof" json:"next_time,omitempty"`                                                     // 对应 golem field 2
	Selector                  *uint32                `protobuf:"varint,3,opt,name=selector,proto3,oneof" json:"selector,omitempty"`                                                                     // 对应 golem field 3
	BluetoothBroadcastContent *base.Buffer           `protobuf:"bytes,4,opt,name=bluetooth_broadcast_content,json=bluetoothBroadcastContent,proto3,oneof" json:"bluetooth_broadcast_content,omitempty"` // 对应 golem field 4
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HeartBeatResponse) Reset() {
	*x = HeartBeatResponse{}
	mi := &file_api_login_login_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeatResponse) ProtoMessage() {}

func (x *HeartBeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_login_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeatResponse.ProtoReflect.Descriptor instead.
func (*HeartBeatResponse) Descriptor() ([]byte, []int) {
	return file_api_login_login_api_proto_rawDescGZIP(), []int{3}
}

func (x *HeartBeatResponse) GetNextTime() uint32 {
	if x != nil && x.NextTime != nil {
		return *x.NextTime
	}
	return 0
}

func (x *HeartBeatResponse) GetSelector() uint32 {
	if x != nil && x.Selector != nil {
		return *x.Selector
	}
	return 0
}

func (x *HeartBeatResponse) GetBluetoothBroadcastContent() *base.Buffer {
	if x != nil {
		return x.BluetoothBroadcastContent
	}
	return nil
}

// LogoutResponse 退出响应（镜像 golem LogoutResponse，移除 base_response）
type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoginTicket   *string                `protobuf:"bytes,2,opt,name=login_ticket,json=loginTicket,proto3,oneof" json:"login_ticket,omitempty"` // 对应 golem field 2
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_api_login_login_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_login_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_api_login_login_api_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutResponse) GetLoginTicket() string {
	if x != nil && x.LoginTicket != nil {
		return *x.LoginTicket
	}
	return ""
}

// PasswordLoginRequest 密码登录请求（API 层自定义，golem 无对应）
type PasswordLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	DeviceType    string                 `protobuf:"bytes,3,opt,name=device_type,json=deviceType,proto3" json:"device_type,omitempty"`
	DeviceName    string                 `protobuf:"bytes,4,opt,name=device_name,json=deviceName,proto3" json:"device_name,omitempty"`
	DeviceId      string                 `protobuf:"bytes,5,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginRequest) Reset() {
	*x = PasswordLoginRequest{}
	mi := &file_api_login_login_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginRequest) ProtoMessage() {}

func (x *PasswordLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_login_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginRequest.ProtoReflect.Descriptor instead.
func (*PasswordLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_login_login_api_proto_rawDescGZIP(), []int{5}
}

func (x *PasswordLoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PasswordLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *PasswordLoginRequest) GetDeviceType() string {
	if x != nil {
		return x.DeviceType
	}
	return ""
}

func (x *PasswordLoginRequest) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *PasswordLoginRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

// PasswordLoginResult 密码登录结果（API 层自定义，golem 无对应）
type PasswordLoginResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uin           uint32                 `protobuf:"varint,1,opt,name=uin,proto3" json:"uin,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Alias         string                 `protobuf:"bytes,4,opt,name=alias,proto3" json:"alias,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Mobile        string                 `protobuf:"bytes,6,opt,name=mobile,proto3" json:"mobile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PasswordLoginResult) Reset() {
	*x = PasswordLoginResult{}
	mi := &file_api_login_login_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PasswordLoginResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordLoginResult) ProtoMessage() {}

func (x *PasswordLoginResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_login_login_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordLoginResult.ProtoReflect.Descriptor instead.
func (*PasswordLoginResult) Descriptor() ([]byte, []int) {
	return file_api_login_login_api_proto_rawDescGZIP(), []int{6}
}

func (x *PasswordLoginResult) GetUin() uint32 {
	if x != nil {
		return x.Uin
	}
	return 0
}

func (x *PasswordLoginResult) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PasswordLoginResult) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PasswordLoginResult) GetAlias() string {
	if x != nil {
		return x.Alias
	}
	return ""
}

func (x *PasswordLoginResult) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PasswordLoginResult) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

var File_api_login_login_api_proto protoreflect.FileDescriptor

const file_api_login_login_api_proto_rawDesc = "" +
	"\n" +
	"\x19api/login/login_api.proto\x12\tapi.login\x1a\x13api/base/base.proto\"?\n" +
	"\x0fOperateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x9b\x02\n" +
	"\fQRCodeResult\x12-\n" +
	"\x06qrcode\x18\x02 \x01(\v2\x10.api.base.BufferH\x00R\x06qrcode\x88\x01\x01\x12\x17\n" +
	"\x04uuid\x18\x03 \x01(\tH\x01R\x04uuid\x88\x01\x01\x12\"\n" +
	"\n" +
	"check_time\x18\x04 \x01(\rH\x02R\tcheckTime\x88\x01\x01\x124\n" +
	"\n" +
	"notify_key\x18\x05 \x01(\v2\x10.api.base.BufferH\x03R\tnotifyKey\x88\x01\x01\x12&\n" +
	"\fexpired_time\x18\x06 \x01(\rH\x04R\vexpiredTime\x88\x01\x01B\t\n" +
	"\a_qrcodeB\a\n" +
	"\x05_uuidB\r\n" +
	"\v_check_timeB\r\n" +
	"\v_notify_keyB\x0f\n" +
	"\r_expired_time\"<\n" +
	"\fInitResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe8\x01\n" +
	"\x11HeartBeatResponse\x12 \n" +
	"\tnext_time\x18\x02 \x01(\rH\x00R\bnextTime\x88\x01\x01\x12\x1f\n" +
	"\bselector\x18\x03 \x01(\rH\x01R\bselector\x88\x01\x01\x12U\n" +
	"\x1bbluetooth_broadcast_content\x18\x04 \x01(\v2\x10.api.base.BufferH\x02R\x19bluetoothBroadcastContent\x88\x01\x01B\f\n" +
	"\n" +
	"_next_timeB\v\n" +
	"\t_selectorB\x1e\n" +
	"\x1c_bluetooth_broadcast_content\"I\n" +
	"\x0eLogoutResponse\x12&\n" +
	"\flogin_ticket\x18\x02 \x01(\tH\x00R\vloginTicket\x88\x01\x01B\x0f\n" +
	"\r_login_ticket\"\xad\x01\n" +
	"\x14PasswordLoginRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vdevice_type\x18\x03 \x01(\tR\n" +
	"deviceType\x12\x1f\n" +
	"\vdevice_name\x18\x04 \x01(\tR\n" +
	"deviceName\x12\x1b\n" +
	"\tdevice_id\x18\x05 \x01(\tR\bdeviceId\"\xa3\x01\n" +
	"\x13PasswordLoginResult\x12\x10\n" +
	"\x03uin\x18\x01 \x01(\rR\x03uin\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x14\n" +
	"\x05alias\x18\x04 \x01(\tR\x05alias\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x16\n" +
	"\x06mobile\x18\x06 \x01(\tR\x06mobileB3Z1github.com/sbgayhub/golem/host/api/login;loginapib\x06proto3"

var (
	file_api_login_login_api_proto_rawDescOnce sync.Once
	file_api_login_login_api_proto_rawDescData []byte
)

func file_api_login_login_api_proto_rawDescGZIP() []byte {
	file_api_login_login_api_proto_rawDescOnce.Do(func() {
		file_api_login_login_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_login_login_api_proto_rawDesc), len(file_api_login_login_api_proto_rawDesc)))
	})
	return file_api_login_login_api_proto_rawDescData
}

var file_api_login_login_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_login_login_api_proto_goTypes = []any{
	(*OperateResponse)(nil),      // 0: api.login.OperateResponse
	(*QRCodeResult)(nil),         // 1: api.login.QRCodeResult
	(*InitResponse)(nil),         // 2: api.login.InitResponse
	(*HeartBeatResponse)(nil),    // 3: api.login.HeartBeatResponse
	(*LogoutResponse)(nil),       // 4: api.login.LogoutResponse
	(*PasswordLoginRequest)(nil), // 5: api.login.PasswordLoginRequest
	(*PasswordLoginResult)(nil),  // 6: api.login.PasswordLoginResult
	(*base.Buffer)(nil),          // 7: api.base.Buffer
}
var file_api_login_login_api_proto_depIdxs = []int32{
	7, // 0: api.login.QRCodeResult.qrcode:type_name -> api.base.Buffer
	7, // 1: api.login.QRCodeResult.notify_key:type_name -> api.base.Buffer
	7, // 2: api.login.HeartBeatResponse.bluetooth_broadcast_content:type_name -> api.base.Buffer
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_login_login_api_proto_init() }
func file_api_login_login_api_proto_init() {
	if File_api_login_login_api_proto != nil {
		return
	}
	file_api_login_login_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_login_login_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_login_login_api_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_login_login_api_proto_rawDesc), len(file_api_login_login_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_login_login_api_proto_goTypes,
		DependencyIndexes: file_api_login_login_api_proto_depIdxs,
		MessageInfos:      file_api_login_login_api_proto_msgTypes,
	}.Build()
	File_api_login_login_api_proto = out.File
	file_api_login_login_api_proto_goTypes = nil
	file_api_login_login_api_proto_depIdxs = nil
}
