// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: chatroom/chatroom.proto

package chatroom

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChatroomService_Create_FullMethodName             = "/chatroom.ChatroomService/Create"
	ChatroomService_FacingCreate_FullMethodName       = "/chatroom.ChatroomService/FacingCreate"
	ChatroomService_GetInfo_FullMethodName            = "/chatroom.ChatroomService/GetInfo"
	ChatroomService_GetQRCode_FullMethodName          = "/chatroom.ChatroomService/GetQRCode"
	ChatroomService_AddMember_FullMethodName          = "/chatroom.ChatroomService/AddMember"
	ChatroomService_InviteMember_FullMethodName       = "/chatroom.ChatroomService/InviteMember"
	ChatroomService_RemoveMember_FullMethodName       = "/chatroom.ChatroomService/RemoveMember"
	ChatroomService_SetName_FullMethodName            = "/chatroom.ChatroomService/SetName"
	ChatroomService_SetAnnouncement_FullMethodName    = "/chatroom.ChatroomService/SetAnnouncement"
	ChatroomService_SetRemark_FullMethodName          = "/chatroom.ChatroomService/SetRemark"
	ChatroomService_Save_FullMethodName               = "/chatroom.ChatroomService/Save"
	ChatroomService_SetAdmin_FullMethodName           = "/chatroom.ChatroomService/SetAdmin"
	ChatroomService_RemoveAdmin_FullMethodName        = "/chatroom.ChatroomService/RemoveAdmin"
	ChatroomService_TransferOwner_FullMethodName      = "/chatroom.ChatroomService/TransferOwner"
	ChatroomService_Quit_FullMethodName               = "/chatroom.ChatroomService/Quit"
	ChatroomService_ScanJoin_FullMethodName           = "/chatroom.ChatroomService/ScanJoin"
	ChatroomService_ScanJoinEnterprise_FullMethodName = "/chatroom.ChatroomService/ScanJoinEnterprise"
	ChatroomService_ConsentJoin_FullMethodName        = "/chatroom.ChatroomService/ConsentJoin"
	ChatroomService_GetMember_FullMethodName          = "/chatroom.ChatroomService/GetMember"
	ChatroomService_ListMembers_FullMethodName        = "/chatroom.ChatroomService/ListMembers"
	ChatroomService_GetMembersDetail_FullMethodName   = "/chatroom.ChatroomService/GetMembersDetail"
)

// ChatroomServiceClient is the client API for ChatroomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChatroomService 群聊服务
type ChatroomServiceClient interface {
	// Create 创建群聊
	Create(ctx context.Context, in *Create_Request, opts ...grpc.CallOption) (*Create_Response, error)
	// FacingCreate 面对面建群
	FacingCreate(ctx context.Context, in *FacingCreate_Request, opts ...grpc.CallOption) (*FacingCreate_Response, error)
	// GetInfo 获取群信息
	GetInfo(ctx context.Context, in *GetInfo_Request, opts ...grpc.CallOption) (*GetInfo_Response, error)
	// GetQRCode 获取群二维码
	GetQRCode(ctx context.Context, in *GetQRCode_Request, opts ...grpc.CallOption) (*GetQRCode_Response, error)
	// AddMember 添加群成员
	AddMember(ctx context.Context, in *AddMember_Request, opts ...grpc.CallOption) (*AddMember_Response, error)
	// InviteMember 邀请群成员
	InviteMember(ctx context.Context, in *InviteMember_Request, opts ...grpc.CallOption) (*InviteMember_Response, error)
	// RemoveMember 移除群成员
	RemoveMember(ctx context.Context, in *RemoveMember_Request, opts ...grpc.CallOption) (*RemoveMember_Response, error)
	// SetName 设置群名称
	SetName(ctx context.Context, in *SetName_Request, opts ...grpc.CallOption) (*SetName_Response, error)
	// SetAnnouncement 设置群公告
	SetAnnouncement(ctx context.Context, in *SetAnnouncement_Request, opts ...grpc.CallOption) (*SetAnnouncement_Response, error)
	// SetRemark 设置群备注
	SetRemark(ctx context.Context, in *SetRemark_Request, opts ...grpc.CallOption) (*SetRemark_Response, error)
	// Save 保存到通讯录
	Save(ctx context.Context, in *Save_Request, opts ...grpc.CallOption) (*Save_Response, error)
	// SetAdmin 设置群管理员
	SetAdmin(ctx context.Context, in *SetAdmin_Request, opts ...grpc.CallOption) (*SetAdmin_Response, error)
	// RemoveAdmin 移除群管理员
	RemoveAdmin(ctx context.Context, in *RemoveAdmin_Request, opts ...grpc.CallOption) (*RemoveAdmin_Response, error)
	// TransferOwner 转让群主
	TransferOwner(ctx context.Context, in *TransferOwner_Request, opts ...grpc.CallOption) (*TransferOwner_Response, error)
	// Quit 退出群聊
	Quit(ctx context.Context, in *Quit_Request, opts ...grpc.CallOption) (*Quit_Response, error)
	// ScanJoin 扫码进群
	ScanJoin(ctx context.Context, in *ScanJoin_Request, opts ...grpc.CallOption) (*ScanJoin_Response, error)
	// ScanJoinEnterprise 企业微信扫码进群
	ScanJoinEnterprise(ctx context.Context, in *ScanJoin_Request, opts ...grpc.CallOption) (*ScanJoin_Response, error)
	// ConsentJoin 同意入群邀请
	ConsentJoin(ctx context.Context, in *ConsentJoin_Request, opts ...grpc.CallOption) (*ConsentJoin_Response, error)
	// GetMember 获取群成员
	GetMember(ctx context.Context, in *GetMember_Request, opts ...grpc.CallOption) (*GetMember_Response, error)
	// ListMembers 获取群成员列表
	ListMembers(ctx context.Context, in *ListMembers_Request, opts ...grpc.CallOption) (*ListMembers_Response, error)
	// GetMemberDetail 获取群成员详情
	GetMembersDetail(ctx context.Context, in *GetMemberDetail_Request, opts ...grpc.CallOption) (*GetMemberDetail_Response, error)
}

type chatroomServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatroomServiceClient(cc grpc.ClientConnInterface) ChatroomServiceClient {
	return &chatroomServiceClient{cc}
}

func (c *chatroomServiceClient) Create(ctx context.Context, in *Create_Request, opts ...grpc.CallOption) (*Create_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Create_Response)
	err := c.cc.Invoke(ctx, ChatroomService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) FacingCreate(ctx context.Context, in *FacingCreate_Request, opts ...grpc.CallOption) (*FacingCreate_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FacingCreate_Response)
	err := c.cc.Invoke(ctx, ChatroomService_FacingCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) GetInfo(ctx context.Context, in *GetInfo_Request, opts ...grpc.CallOption) (*GetInfo_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfo_Response)
	err := c.cc.Invoke(ctx, ChatroomService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) GetQRCode(ctx context.Context, in *GetQRCode_Request, opts ...grpc.CallOption) (*GetQRCode_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQRCode_Response)
	err := c.cc.Invoke(ctx, ChatroomService_GetQRCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) AddMember(ctx context.Context, in *AddMember_Request, opts ...grpc.CallOption) (*AddMember_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMember_Response)
	err := c.cc.Invoke(ctx, ChatroomService_AddMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) InviteMember(ctx context.Context, in *InviteMember_Request, opts ...grpc.CallOption) (*InviteMember_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InviteMember_Response)
	err := c.cc.Invoke(ctx, ChatroomService_InviteMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) RemoveMember(ctx context.Context, in *RemoveMember_Request, opts ...grpc.CallOption) (*RemoveMember_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMember_Response)
	err := c.cc.Invoke(ctx, ChatroomService_RemoveMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) SetName(ctx context.Context, in *SetName_Request, opts ...grpc.CallOption) (*SetName_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetName_Response)
	err := c.cc.Invoke(ctx, ChatroomService_SetName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) SetAnnouncement(ctx context.Context, in *SetAnnouncement_Request, opts ...grpc.CallOption) (*SetAnnouncement_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAnnouncement_Response)
	err := c.cc.Invoke(ctx, ChatroomService_SetAnnouncement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) SetRemark(ctx context.Context, in *SetRemark_Request, opts ...grpc.CallOption) (*SetRemark_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetRemark_Response)
	err := c.cc.Invoke(ctx, ChatroomService_SetRemark_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) Save(ctx context.Context, in *Save_Request, opts ...grpc.CallOption) (*Save_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Save_Response)
	err := c.cc.Invoke(ctx, ChatroomService_Save_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) SetAdmin(ctx context.Context, in *SetAdmin_Request, opts ...grpc.CallOption) (*SetAdmin_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetAdmin_Response)
	err := c.cc.Invoke(ctx, ChatroomService_SetAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) RemoveAdmin(ctx context.Context, in *RemoveAdmin_Request, opts ...grpc.CallOption) (*RemoveAdmin_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAdmin_Response)
	err := c.cc.Invoke(ctx, ChatroomService_RemoveAdmin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) TransferOwner(ctx context.Context, in *TransferOwner_Request, opts ...grpc.CallOption) (*TransferOwner_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferOwner_Response)
	err := c.cc.Invoke(ctx, ChatroomService_TransferOwner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) Quit(ctx context.Context, in *Quit_Request, opts ...grpc.CallOption) (*Quit_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Quit_Response)
	err := c.cc.Invoke(ctx, ChatroomService_Quit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) ScanJoin(ctx context.Context, in *ScanJoin_Request, opts ...grpc.CallOption) (*ScanJoin_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanJoin_Response)
	err := c.cc.Invoke(ctx, ChatroomService_ScanJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) ScanJoinEnterprise(ctx context.Context, in *ScanJoin_Request, opts ...grpc.CallOption) (*ScanJoin_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScanJoin_Response)
	err := c.cc.Invoke(ctx, ChatroomService_ScanJoinEnterprise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) ConsentJoin(ctx context.Context, in *ConsentJoin_Request, opts ...grpc.CallOption) (*ConsentJoin_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsentJoin_Response)
	err := c.cc.Invoke(ctx, ChatroomService_ConsentJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) GetMember(ctx context.Context, in *GetMember_Request, opts ...grpc.CallOption) (*GetMember_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMember_Response)
	err := c.cc.Invoke(ctx, ChatroomService_GetMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) ListMembers(ctx context.Context, in *ListMembers_Request, opts ...grpc.CallOption) (*ListMembers_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMembers_Response)
	err := c.cc.Invoke(ctx, ChatroomService_ListMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatroomServiceClient) GetMembersDetail(ctx context.Context, in *GetMemberDetail_Request, opts ...grpc.CallOption) (*GetMemberDetail_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberDetail_Response)
	err := c.cc.Invoke(ctx, ChatroomService_GetMembersDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatroomServiceServer is the server API for ChatroomService service.
// All implementations must embed UnimplementedChatroomServiceServer
// for forward compatibility.
//
// ChatroomService 群聊服务
type ChatroomServiceServer interface {
	// Create 创建群聊
	Create(context.Context, *Create_Request) (*Create_Response, error)
	// FacingCreate 面对面建群
	FacingCreate(context.Context, *FacingCreate_Request) (*FacingCreate_Response, error)
	// GetInfo 获取群信息
	GetInfo(context.Context, *GetInfo_Request) (*GetInfo_Response, error)
	// GetQRCode 获取群二维码
	GetQRCode(context.Context, *GetQRCode_Request) (*GetQRCode_Response, error)
	// AddMember 添加群成员
	AddMember(context.Context, *AddMember_Request) (*AddMember_Response, error)
	// InviteMember 邀请群成员
	InviteMember(context.Context, *InviteMember_Request) (*InviteMember_Response, error)
	// RemoveMember 移除群成员
	RemoveMember(context.Context, *RemoveMember_Request) (*RemoveMember_Response, error)
	// SetName 设置群名称
	SetName(context.Context, *SetName_Request) (*SetName_Response, error)
	// SetAnnouncement 设置群公告
	SetAnnouncement(context.Context, *SetAnnouncement_Request) (*SetAnnouncement_Response, error)
	// SetRemark 设置群备注
	SetRemark(context.Context, *SetRemark_Request) (*SetRemark_Response, error)
	// Save 保存到通讯录
	Save(context.Context, *Save_Request) (*Save_Response, error)
	// SetAdmin 设置群管理员
	SetAdmin(context.Context, *SetAdmin_Request) (*SetAdmin_Response, error)
	// RemoveAdmin 移除群管理员
	RemoveAdmin(context.Context, *RemoveAdmin_Request) (*RemoveAdmin_Response, error)
	// TransferOwner 转让群主
	TransferOwner(context.Context, *TransferOwner_Request) (*TransferOwner_Response, error)
	// Quit 退出群聊
	Quit(context.Context, *Quit_Request) (*Quit_Response, error)
	// ScanJoin 扫码进群
	ScanJoin(context.Context, *ScanJoin_Request) (*ScanJoin_Response, error)
	// ScanJoinEnterprise 企业微信扫码进群
	ScanJoinEnterprise(context.Context, *ScanJoin_Request) (*ScanJoin_Response, error)
	// ConsentJoin 同意入群邀请
	ConsentJoin(context.Context, *ConsentJoin_Request) (*ConsentJoin_Response, error)
	// GetMember 获取群成员
	GetMember(context.Context, *GetMember_Request) (*GetMember_Response, error)
	// ListMembers 获取群成员列表
	ListMembers(context.Context, *ListMembers_Request) (*ListMembers_Response, error)
	// GetMemberDetail 获取群成员详情
	GetMembersDetail(context.Context, *GetMemberDetail_Request) (*GetMemberDetail_Response, error)
	mustEmbedUnimplementedChatroomServiceServer()
}

// UnimplementedChatroomServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChatroomServiceServer struct{}

func (UnimplementedChatroomServiceServer) Create(context.Context, *Create_Request) (*Create_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedChatroomServiceServer) FacingCreate(context.Context, *FacingCreate_Request) (*FacingCreate_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method FacingCreate not implemented")
}
func (UnimplementedChatroomServiceServer) GetInfo(context.Context, *GetInfo_Request) (*GetInfo_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedChatroomServiceServer) GetQRCode(context.Context, *GetQRCode_Request) (*GetQRCode_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQRCode not implemented")
}
func (UnimplementedChatroomServiceServer) AddMember(context.Context, *AddMember_Request) (*AddMember_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMember not implemented")
}
func (UnimplementedChatroomServiceServer) InviteMember(context.Context, *InviteMember_Request) (*InviteMember_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method InviteMember not implemented")
}
func (UnimplementedChatroomServiceServer) RemoveMember(context.Context, *RemoveMember_Request) (*RemoveMember_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMember not implemented")
}
func (UnimplementedChatroomServiceServer) SetName(context.Context, *SetName_Request) (*SetName_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetName not implemented")
}
func (UnimplementedChatroomServiceServer) SetAnnouncement(context.Context, *SetAnnouncement_Request) (*SetAnnouncement_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAnnouncement not implemented")
}
func (UnimplementedChatroomServiceServer) SetRemark(context.Context, *SetRemark_Request) (*SetRemark_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetRemark not implemented")
}
func (UnimplementedChatroomServiceServer) Save(context.Context, *Save_Request) (*Save_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Save not implemented")
}
func (UnimplementedChatroomServiceServer) SetAdmin(context.Context, *SetAdmin_Request) (*SetAdmin_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAdmin not implemented")
}
func (UnimplementedChatroomServiceServer) RemoveAdmin(context.Context, *RemoveAdmin_Request) (*RemoveAdmin_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAdmin not implemented")
}
func (UnimplementedChatroomServiceServer) TransferOwner(context.Context, *TransferOwner_Request) (*TransferOwner_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferOwner not implemented")
}
func (UnimplementedChatroomServiceServer) Quit(context.Context, *Quit_Request) (*Quit_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method Quit not implemented")
}
func (UnimplementedChatroomServiceServer) ScanJoin(context.Context, *ScanJoin_Request) (*ScanJoin_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanJoin not implemented")
}
func (UnimplementedChatroomServiceServer) ScanJoinEnterprise(context.Context, *ScanJoin_Request) (*ScanJoin_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ScanJoinEnterprise not implemented")
}
func (UnimplementedChatroomServiceServer) ConsentJoin(context.Context, *ConsentJoin_Request) (*ConsentJoin_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsentJoin not implemented")
}
func (UnimplementedChatroomServiceServer) GetMember(context.Context, *GetMember_Request) (*GetMember_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMember not implemented")
}
func (UnimplementedChatroomServiceServer) ListMembers(context.Context, *ListMembers_Request) (*ListMembers_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMembers not implemented")
}
func (UnimplementedChatroomServiceServer) GetMembersDetail(context.Context, *GetMemberDetail_Request) (*GetMemberDetail_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMembersDetail not implemented")
}
func (UnimplementedChatroomServiceServer) mustEmbedUnimplementedChatroomServiceServer() {}
func (UnimplementedChatroomServiceServer) testEmbeddedByValue()                         {}

// UnsafeChatroomServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatroomServiceServer will
// result in compilation errors.
type UnsafeChatroomServiceServer interface {
	mustEmbedUnimplementedChatroomServiceServer()
}

func RegisterChatroomServiceServer(s grpc.ServiceRegistrar, srv ChatroomServiceServer) {
	// If the following call panics, it indicates UnimplementedChatroomServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChatroomService_ServiceDesc, srv)
}

func _ChatroomService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Create_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).Create(ctx, req.(*Create_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_FacingCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FacingCreate_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).FacingCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_FacingCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).FacingCreate(ctx, req.(*FacingCreate_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfo_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).GetInfo(ctx, req.(*GetInfo_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_GetQRCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQRCode_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).GetQRCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_GetQRCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).GetQRCode(ctx, req.(*GetQRCode_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMember_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_AddMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).AddMember(ctx, req.(*AddMember_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_InviteMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InviteMember_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).InviteMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_InviteMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).InviteMember(ctx, req.(*InviteMember_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMember_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_RemoveMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).RemoveMember(ctx, req.(*RemoveMember_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_SetName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetName_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).SetName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_SetName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).SetName(ctx, req.(*SetName_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_SetAnnouncement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAnnouncement_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).SetAnnouncement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_SetAnnouncement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).SetAnnouncement(ctx, req.(*SetAnnouncement_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_SetRemark_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRemark_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).SetRemark(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_SetRemark_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).SetRemark(ctx, req.(*SetRemark_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_Save_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Save_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).Save(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_Save_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).Save(ctx, req.(*Save_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_SetAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAdmin_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).SetAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_SetAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).SetAdmin(ctx, req.(*SetAdmin_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_RemoveAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAdmin_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).RemoveAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_RemoveAdmin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).RemoveAdmin(ctx, req.(*RemoveAdmin_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_TransferOwner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferOwner_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).TransferOwner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_TransferOwner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).TransferOwner(ctx, req.(*TransferOwner_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_Quit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Quit_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).Quit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_Quit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).Quit(ctx, req.(*Quit_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_ScanJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanJoin_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).ScanJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_ScanJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).ScanJoin(ctx, req.(*ScanJoin_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_ScanJoinEnterprise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScanJoin_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).ScanJoinEnterprise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_ScanJoinEnterprise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).ScanJoinEnterprise(ctx, req.(*ScanJoin_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_ConsentJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsentJoin_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).ConsentJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_ConsentJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).ConsentJoin(ctx, req.(*ConsentJoin_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_GetMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMember_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).GetMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_GetMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).GetMember(ctx, req.(*GetMember_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_ListMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMembers_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).ListMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_ListMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).ListMembers(ctx, req.(*ListMembers_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatroomService_GetMembersDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberDetail_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatroomServiceServer).GetMembersDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChatroomService_GetMembersDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatroomServiceServer).GetMembersDetail(ctx, req.(*GetMemberDetail_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// ChatroomService_ServiceDesc is the grpc.ServiceDesc for ChatroomService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatroomService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatroom.ChatroomService",
	HandlerType: (*ChatroomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ChatroomService_Create_Handler,
		},
		{
			MethodName: "FacingCreate",
			Handler:    _ChatroomService_FacingCreate_Handler,
		},
		{
			MethodName: "GetInfo",
			Handler:    _ChatroomService_GetInfo_Handler,
		},
		{
			MethodName: "GetQRCode",
			Handler:    _ChatroomService_GetQRCode_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _ChatroomService_AddMember_Handler,
		},
		{
			MethodName: "InviteMember",
			Handler:    _ChatroomService_InviteMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _ChatroomService_RemoveMember_Handler,
		},
		{
			MethodName: "SetName",
			Handler:    _ChatroomService_SetName_Handler,
		},
		{
			MethodName: "SetAnnouncement",
			Handler:    _ChatroomService_SetAnnouncement_Handler,
		},
		{
			MethodName: "SetRemark",
			Handler:    _ChatroomService_SetRemark_Handler,
		},
		{
			MethodName: "Save",
			Handler:    _ChatroomService_Save_Handler,
		},
		{
			MethodName: "SetAdmin",
			Handler:    _ChatroomService_SetAdmin_Handler,
		},
		{
			MethodName: "RemoveAdmin",
			Handler:    _ChatroomService_RemoveAdmin_Handler,
		},
		{
			MethodName: "TransferOwner",
			Handler:    _ChatroomService_TransferOwner_Handler,
		},
		{
			MethodName: "Quit",
			Handler:    _ChatroomService_Quit_Handler,
		},
		{
			MethodName: "ScanJoin",
			Handler:    _ChatroomService_ScanJoin_Handler,
		},
		{
			MethodName: "ScanJoinEnterprise",
			Handler:    _ChatroomService_ScanJoinEnterprise_Handler,
		},
		{
			MethodName: "ConsentJoin",
			Handler:    _ChatroomService_ConsentJoin_Handler,
		},
		{
			MethodName: "GetMember",
			Handler:    _ChatroomService_GetMember_Handler,
		},
		{
			MethodName: "ListMembers",
			Handler:    _ChatroomService_ListMembers_Handler,
		},
		{
			MethodName: "GetMembersDetail",
			Handler:    _ChatroomService_GetMembersDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatroom/chatroom.proto",
}
