// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/favor/favor_api.proto

package favorapi

import (
	base "github.com/sbgayhub/golem/host/api/base"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperateResponse 通用操作响应
type OperateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperateResponse) Reset() {
	*x = OperateResponse{}
	mi := &file_api_favor_favor_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperateResponse) ProtoMessage() {}

func (x *OperateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperateResponse.ProtoReflect.Descriptor instead.
func (*OperateResponse) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{0}
}

func (x *OperateResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *OperateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetInfoResponse 获取收藏信息响应（镜像 golem GetInfoResponse，字段号从 2 开始）
type GetInfoResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	UsedSize            *uint64                `protobuf:"varint,2,opt,name=used_size,json=usedSize,proto3,oneof" json:"used_size,omitempty"`                                      // 对应 golem field 2
	TotalSize           *uint64                `protobuf:"varint,3,opt,name=total_size,json=totalSize,proto3,oneof" json:"total_size,omitempty"`                                   // 对应 golem field 3
	MaxFileSize         *uint64                `protobuf:"varint,4,opt,name=max_file_size,json=maxFileSize,proto3,oneof" json:"max_file_size,omitempty"`                           // 对应 golem field 4
	MaxAutoUploadSize   *int32                 `protobuf:"varint,5,opt,name=max_auto_upload_size,json=maxAutoUploadSize,proto3,oneof" json:"max_auto_upload_size,omitempty"`       // 对应 golem field 5
	MaxAutoDownloadSize *int32                 `protobuf:"varint,6,opt,name=max_auto_download_size,json=maxAutoDownloadSize,proto3,oneof" json:"max_auto_download_size,omitempty"` // 对应 golem field 6
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_api_favor_favor_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetInfoResponse) GetUsedSize() uint64 {
	if x != nil && x.UsedSize != nil {
		return *x.UsedSize
	}
	return 0
}

func (x *GetInfoResponse) GetTotalSize() uint64 {
	if x != nil && x.TotalSize != nil {
		return *x.TotalSize
	}
	return 0
}

func (x *GetInfoResponse) GetMaxFileSize() uint64 {
	if x != nil && x.MaxFileSize != nil {
		return *x.MaxFileSize
	}
	return 0
}

func (x *GetInfoResponse) GetMaxAutoUploadSize() int32 {
	if x != nil && x.MaxAutoUploadSize != nil {
		return *x.MaxAutoUploadSize
	}
	return 0
}

func (x *GetInfoResponse) GetMaxAutoDownloadSize() int32 {
	if x != nil && x.MaxAutoDownloadSize != nil {
		return *x.MaxAutoDownloadSize
	}
	return 0
}

// FavorItem 收藏项信息（镜像 golem BatchGetItemResponse.Object，字段编号完全一致）
type FavorItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             *uint32                `protobuf:"varint,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Status         *int32                 `protobuf:"varint,2,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Object         *string                `protobuf:"bytes,3,opt,name=object,proto3,oneof" json:"object,omitempty"`
	Flag           *uint32                `protobuf:"varint,4,opt,name=flag,proto3,oneof" json:"flag,omitempty"`
	UpdateTime     *uint32                `protobuf:"varint,5,opt,name=update_time,json=updateTime,proto3,oneof" json:"update_time,omitempty"`
	UpdateSequence *uint32                `protobuf:"varint,6,opt,name=update_sequence,json=updateSequence,proto3,oneof" json:"update_sequence,omitempty"` // 注意：golem 用 update_sequence，非 update_seq
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FavorItem) Reset() {
	*x = FavorItem{}
	mi := &file_api_favor_favor_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FavorItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FavorItem) ProtoMessage() {}

func (x *FavorItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FavorItem.ProtoReflect.Descriptor instead.
func (*FavorItem) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{2}
}

func (x *FavorItem) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *FavorItem) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

func (x *FavorItem) GetObject() string {
	if x != nil && x.Object != nil {
		return *x.Object
	}
	return ""
}

func (x *FavorItem) GetFlag() uint32 {
	if x != nil && x.Flag != nil {
		return *x.Flag
	}
	return 0
}

func (x *FavorItem) GetUpdateTime() uint32 {
	if x != nil && x.UpdateTime != nil {
		return *x.UpdateTime
	}
	return 0
}

func (x *FavorItem) GetUpdateSequence() uint32 {
	if x != nil && x.UpdateSequence != nil {
		return *x.UpdateSequence
	}
	return 0
}

// GetFavItemResponse 获取收藏项详情响应
type GetFavItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*FavorItem           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFavItemResponse) Reset() {
	*x = GetFavItemResponse{}
	mi := &file_api_favor_favor_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFavItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFavItemResponse) ProtoMessage() {}

func (x *GetFavItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFavItemResponse.ProtoReflect.Descriptor instead.
func (*GetFavItemResponse) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{3}
}

func (x *GetFavItemResponse) GetItems() []*FavorItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// BatchGetFavItemsResponse 批量获取收藏项响应（镜像 golem BatchGetItemResponse，字段号从 2 开始）
type BatchGetFavItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *uint32                `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"` // 对应 golem field 2
	Objects       []*FavorItem           `protobuf:"bytes,3,rep,name=objects,proto3" json:"objects,omitempty"`    // 对应 golem field 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetFavItemsResponse) Reset() {
	*x = BatchGetFavItemsResponse{}
	mi := &file_api_favor_favor_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetFavItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetFavItemsResponse) ProtoMessage() {}

func (x *BatchGetFavItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetFavItemsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetFavItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{4}
}

func (x *BatchGetFavItemsResponse) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *BatchGetFavItemsResponse) GetObjects() []*FavorItem {
	if x != nil {
		return x.Objects
	}
	return nil
}

// DeleteResult 删除结果（镜像 golem BatchDeleteItemResponse.Result，字段编号完全一致）
type DeleteResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *int32                 `protobuf:"varint,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	Id            *uint32                `protobuf:"varint,2,opt,name=id,proto3,oneof" json:"id,omitempty"` // 注意：golem 用 id，非 fav_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResult) Reset() {
	*x = DeleteResult{}
	mi := &file_api_favor_favor_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResult) ProtoMessage() {}

func (x *DeleteResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResult.ProtoReflect.Descriptor instead.
func (*DeleteResult) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResult) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *DeleteResult) GetId() uint32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

// DeleteFavItemResponse 删除收藏项响应
type DeleteFavItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*DeleteResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFavItemResponse) Reset() {
	*x = DeleteFavItemResponse{}
	mi := &file_api_favor_favor_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFavItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFavItemResponse) ProtoMessage() {}

func (x *DeleteFavItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFavItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteFavItemResponse) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFavItemResponse) GetResults() []*DeleteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// BatchDeleteFavItemsResponse 批量删除收藏项响应（镜像 golem BatchDeleteItemResponse，字段号从 2 开始）
type BatchDeleteFavItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *uint32                `protobuf:"varint,2,opt,name=count,proto3,oneof" json:"count,omitempty"` // 对应 golem field 2
	Results       []*DeleteResult        `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`    // 对应 golem field 3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDeleteFavItemsResponse) Reset() {
	*x = BatchDeleteFavItemsResponse{}
	mi := &file_api_favor_favor_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDeleteFavItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDeleteFavItemsResponse) ProtoMessage() {}

func (x *BatchDeleteFavItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDeleteFavItemsResponse.ProtoReflect.Descriptor instead.
func (*BatchDeleteFavItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{7}
}

func (x *BatchDeleteFavItemsResponse) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *BatchDeleteFavItemsResponse) GetResults() []*DeleteResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// SyncFavorResponse 同步收藏列表响应（镜像 golem SyncResponse，字段编号完全一致）
type SyncFavorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          *int32                 `protobuf:"varint,1,opt,name=code,proto3,oneof" json:"code,omitempty"`                                     // 对应 golem field 1
	Commands      *base.Commands         `protobuf:"bytes,2,opt,name=commands,proto3,oneof" json:"commands,omitempty"`                              // 对应 golem field 2
	Key           *base.Buffer           `protobuf:"bytes,3,opt,name=key,proto3,oneof" json:"key,omitempty"`                                        // 对应 golem field 3
	ContinueFlag  *uint32                `protobuf:"varint,4,opt,name=continue_flag,json=continueFlag,proto3,oneof" json:"continue_flag,omitempty"` // 对应 golem field 4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncFavorResponse) Reset() {
	*x = SyncFavorResponse{}
	mi := &file_api_favor_favor_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncFavorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncFavorResponse) ProtoMessage() {}

func (x *SyncFavorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_favor_favor_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncFavorResponse.ProtoReflect.Descriptor instead.
func (*SyncFavorResponse) Descriptor() ([]byte, []int) {
	return file_api_favor_favor_api_proto_rawDescGZIP(), []int{8}
}

func (x *SyncFavorResponse) GetCode() int32 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *SyncFavorResponse) GetCommands() *base.Commands {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *SyncFavorResponse) GetKey() *base.Buffer {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *SyncFavorResponse) GetContinueFlag() uint32 {
	if x != nil && x.ContinueFlag != nil {
		return *x.ContinueFlag
	}
	return 0
}

var File_api_favor_favor_api_proto protoreflect.FileDescriptor

const file_api_favor_favor_api_proto_rawDesc = "" +
	"\n" +
	"\x19api/favor/favor_api.proto\x12\tapi.favor\x1a\x13api/base/base.proto\"?\n" +
	"\x0fOperateResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd3\x02\n" +
	"\x0fGetInfoResponse\x12 \n" +
	"\tused_size\x18\x02 \x01(\x04H\x00R\busedSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"total_size\x18\x03 \x01(\x04H\x01R\ttotalSize\x88\x01\x01\x12'\n" +
	"\rmax_file_size\x18\x04 \x01(\x04H\x02R\vmaxFileSize\x88\x01\x01\x124\n" +
	"\x14max_auto_upload_size\x18\x05 \x01(\x05H\x03R\x11maxAutoUploadSize\x88\x01\x01\x128\n" +
	"\x16max_auto_download_size\x18\x06 \x01(\x05H\x04R\x13maxAutoDownloadSize\x88\x01\x01B\f\n" +
	"\n" +
	"_used_sizeB\r\n" +
	"\v_total_sizeB\x10\n" +
	"\x0e_max_file_sizeB\x17\n" +
	"\x15_max_auto_upload_sizeB\x19\n" +
	"\x17_max_auto_download_size\"\x91\x02\n" +
	"\tFavorItem\x12\x13\n" +
	"\x02id\x18\x01 \x01(\rH\x00R\x02id\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x02 \x01(\x05H\x01R\x06status\x88\x01\x01\x12\x1b\n" +
	"\x06object\x18\x03 \x01(\tH\x02R\x06object\x88\x01\x01\x12\x17\n" +
	"\x04flag\x18\x04 \x01(\rH\x03R\x04flag\x88\x01\x01\x12$\n" +
	"\vupdate_time\x18\x05 \x01(\rH\x04R\n" +
	"updateTime\x88\x01\x01\x12,\n" +
	"\x0fupdate_sequence\x18\x06 \x01(\rH\x05R\x0eupdateSequence\x88\x01\x01B\x05\n" +
	"\x03_idB\t\n" +
	"\a_statusB\t\n" +
	"\a_objectB\a\n" +
	"\x05_flagB\x0e\n" +
	"\f_update_timeB\x12\n" +
	"\x10_update_sequence\"@\n" +
	"\x12GetFavItemResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.api.favor.FavorItemR\x05items\"o\n" +
	"\x18BatchGetFavItemsResponse\x12\x19\n" +
	"\x05count\x18\x02 \x01(\rH\x00R\x05count\x88\x01\x01\x12.\n" +
	"\aobjects\x18\x03 \x03(\v2\x14.api.favor.FavorItemR\aobjectsB\b\n" +
	"\x06_count\"L\n" +
	"\fDeleteResult\x12\x17\n" +
	"\x04code\x18\x01 \x01(\x05H\x00R\x04code\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\rH\x01R\x02id\x88\x01\x01B\a\n" +
	"\x05_codeB\x05\n" +
	"\x03_id\"J\n" +
	"\x15DeleteFavItemResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.api.favor.DeleteResultR\aresults\"u\n" +
	"\x1bBatchDeleteFavItemsResponse\x12\x19\n" +
	"\x05count\x18\x02 \x01(\rH\x00R\x05count\x88\x01\x01\x121\n" +
	"\aresults\x18\x03 \x03(\v2\x17.api.favor.DeleteResultR\aresultsB\b\n" +
	"\x06_count\"\xe4\x01\n" +
	"\x11SyncFavorResponse\x12\x17\n" +
	"\x04code\x18\x01 \x01(\x05H\x00R\x04code\x88\x01\x01\x123\n" +
	"\bcommands\x18\x02 \x01(\v2\x12.api.base.CommandsH\x01R\bcommands\x88\x01\x01\x12'\n" +
	"\x03key\x18\x03 \x01(\v2\x10.api.base.BufferH\x02R\x03key\x88\x01\x01\x12(\n" +
	"\rcontinue_flag\x18\x04 \x01(\rH\x03R\fcontinueFlag\x88\x01\x01B\a\n" +
	"\x05_codeB\v\n" +
	"\t_commandsB\x06\n" +
	"\x04_keyB\x10\n" +
	"\x0e_continue_flagB3Z1github.com/sbgayhub/golem/host/api/favor;favorapib\x06proto3"

var (
	file_api_favor_favor_api_proto_rawDescOnce sync.Once
	file_api_favor_favor_api_proto_rawDescData []byte
)

func file_api_favor_favor_api_proto_rawDescGZIP() []byte {
	file_api_favor_favor_api_proto_rawDescOnce.Do(func() {
		file_api_favor_favor_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_favor_favor_api_proto_rawDesc), len(file_api_favor_favor_api_proto_rawDesc)))
	})
	return file_api_favor_favor_api_proto_rawDescData
}

var file_api_favor_favor_api_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_favor_favor_api_proto_goTypes = []any{
	(*OperateResponse)(nil),             // 0: api.favor.OperateResponse
	(*GetInfoResponse)(nil),             // 1: api.favor.GetInfoResponse
	(*FavorItem)(nil),                   // 2: api.favor.FavorItem
	(*GetFavItemResponse)(nil),          // 3: api.favor.GetFavItemResponse
	(*BatchGetFavItemsResponse)(nil),    // 4: api.favor.BatchGetFavItemsResponse
	(*DeleteResult)(nil),                // 5: api.favor.DeleteResult
	(*DeleteFavItemResponse)(nil),       // 6: api.favor.DeleteFavItemResponse
	(*BatchDeleteFavItemsResponse)(nil), // 7: api.favor.BatchDeleteFavItemsResponse
	(*SyncFavorResponse)(nil),           // 8: api.favor.SyncFavorResponse
	(*base.Commands)(nil),               // 9: api.base.Commands
	(*base.Buffer)(nil),                 // 10: api.base.Buffer
}
var file_api_favor_favor_api_proto_depIdxs = []int32{
	2,  // 0: api.favor.GetFavItemResponse.items:type_name -> api.favor.FavorItem
	2,  // 1: api.favor.BatchGetFavItemsResponse.objects:type_name -> api.favor.FavorItem
	5,  // 2: api.favor.DeleteFavItemResponse.results:type_name -> api.favor.DeleteResult
	5,  // 3: api.favor.BatchDeleteFavItemsResponse.results:type_name -> api.favor.DeleteResult
	9,  // 4: api.favor.SyncFavorResponse.commands:type_name -> api.base.Commands
	10, // 5: api.favor.SyncFavorResponse.key:type_name -> api.base.Buffer
	6,  // [6:6] is the sub-list for method output_type
	6,  // [6:6] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_favor_favor_api_proto_init() }
func file_api_favor_favor_api_proto_init() {
	if File_api_favor_favor_api_proto != nil {
		return
	}
	file_api_favor_favor_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_favor_favor_api_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_favor_favor_api_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_favor_favor_api_proto_msgTypes[5].OneofWrappers = []any{}
	file_api_favor_favor_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_favor_favor_api_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_favor_favor_api_proto_rawDesc), len(file_api_favor_favor_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_favor_favor_api_proto_goTypes,
		DependencyIndexes: file_api_favor_favor_api_proto_depIdxs,
		MessageInfos:      file_api_favor_favor_api_proto_msgTypes,
	}.Build()
	File_api_favor_favor_api_proto = out.File
	file_api_favor_favor_api_proto_goTypes = nil
	file_api_favor_favor_api_proto_depIdxs = nil
}
