// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_GeneratePayQCode_FullMethodName   = "/payment.PaymentService/GeneratePayQCode"
	PaymentService_GetBandCardList_FullMethodName    = "/payment.PaymentService/GetBandCardList"
	PaymentService_CreateHongBao_FullMethodName      = "/payment.PaymentService/CreateHongBao"
	PaymentService_ReceiveHongBao_FullMethodName     = "/payment.PaymentService/ReceiveHongBao"
	PaymentService_OpenHongBao_FullMethodName        = "/payment.PaymentService/OpenHongBao"
	PaymentService_GrabHongBao_FullMethodName        = "/payment.PaymentService/GrabHongBao"
	PaymentService_QueryHongBaoDetail_FullMethodName = "/payment.PaymentService/QueryHongBaoDetail"
	PaymentService_QueryHongBaoList_FullMethodName   = "/payment.PaymentService/QueryHongBaoList"
	PaymentService_CreatePreTransfer_FullMethodName  = "/payment.PaymentService/CreatePreTransfer"
	PaymentService_ConfirmPreTransfer_FullMethodName = "/payment.PaymentService/ConfirmPreTransfer"
	PaymentService_CollectMoney_FullMethodName       = "/payment.PaymentService/CollectMoney"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PaymentService 支付服务
type PaymentServiceClient interface {
	// GeneratePayQCode 生成支付收款二维码
	GeneratePayQCode(ctx context.Context, in *GeneratePayQCode_Request, opts ...grpc.CallOption) (*GeneratePayQCode_Response, error)
	// GetBandCardList 获取已绑定银行卡及余额
	GetBandCardList(ctx context.Context, in *GetBandCardList_Request, opts ...grpc.CallOption) (*GetBandCardList_Response, error)
	// CreateHongBao 创建红包
	CreateHongBao(ctx context.Context, in *CreateHongBao_Request, opts ...grpc.CallOption) (*CreateHongBao_Response, error)
	// ReceiveHongBao 接收红包
	ReceiveHongBao(ctx context.Context, in *ReceiveHongBao_Request, opts ...grpc.CallOption) (*ReceiveHongBao_Response, error)
	// OpenHongBao 打开红包
	OpenHongBao(ctx context.Context, in *OpenHongBao_Request, opts ...grpc.CallOption) (*OpenHongBao_Response, error)
	// GrabHongBao 抢红包
	GrabHongBao(ctx context.Context, in *GrabHongBao_Request, opts ...grpc.CallOption) (*GrabHongBao_Response, error)
	// QueryHongBaoDetail 查询红包领取详情
	QueryHongBaoDetail(ctx context.Context, in *QueryHongBaoDetail_Request, opts ...grpc.CallOption) (*QueryHongBaoDetail_Response, error)
	// QueryHongBaoList 查询红包领取列表
	QueryHongBaoList(ctx context.Context, in *QueryHongBaoList_Request, opts ...grpc.CallOption) (*QueryHongBaoList_Response, error)
	// CreatePreTransfer 创建转账
	CreatePreTransfer(ctx context.Context, in *CreatePreTransfer_Request, opts ...grpc.CallOption) (*CreatePreTransfer_Response, error)
	// ConfirmPreTransfer 确认转账
	ConfirmPreTransfer(ctx context.Context, in *ConfirmPreTransfer_Request, opts ...grpc.CallOption) (*ConfirmPreTransfer_Response, error)
	// CollectMoney 确认收款
	CollectMoney(ctx context.Context, in *CollectMoney_Request, opts ...grpc.CallOption) (*CollectMoney_Response, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) GeneratePayQCode(ctx context.Context, in *GeneratePayQCode_Request, opts ...grpc.CallOption) (*GeneratePayQCode_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeneratePayQCode_Response)
	err := c.cc.Invoke(ctx, PaymentService_GeneratePayQCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GetBandCardList(ctx context.Context, in *GetBandCardList_Request, opts ...grpc.CallOption) (*GetBandCardList_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBandCardList_Response)
	err := c.cc.Invoke(ctx, PaymentService_GetBandCardList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreateHongBao(ctx context.Context, in *CreateHongBao_Request, opts ...grpc.CallOption) (*CreateHongBao_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateHongBao_Response)
	err := c.cc.Invoke(ctx, PaymentService_CreateHongBao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ReceiveHongBao(ctx context.Context, in *ReceiveHongBao_Request, opts ...grpc.CallOption) (*ReceiveHongBao_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReceiveHongBao_Response)
	err := c.cc.Invoke(ctx, PaymentService_ReceiveHongBao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) OpenHongBao(ctx context.Context, in *OpenHongBao_Request, opts ...grpc.CallOption) (*OpenHongBao_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenHongBao_Response)
	err := c.cc.Invoke(ctx, PaymentService_OpenHongBao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) GrabHongBao(ctx context.Context, in *GrabHongBao_Request, opts ...grpc.CallOption) (*GrabHongBao_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GrabHongBao_Response)
	err := c.cc.Invoke(ctx, PaymentService_GrabHongBao_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) QueryHongBaoDetail(ctx context.Context, in *QueryHongBaoDetail_Request, opts ...grpc.CallOption) (*QueryHongBaoDetail_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryHongBaoDetail_Response)
	err := c.cc.Invoke(ctx, PaymentService_QueryHongBaoDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) QueryHongBaoList(ctx context.Context, in *QueryHongBaoList_Request, opts ...grpc.CallOption) (*QueryHongBaoList_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryHongBaoList_Response)
	err := c.cc.Invoke(ctx, PaymentService_QueryHongBaoList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CreatePreTransfer(ctx context.Context, in *CreatePreTransfer_Request, opts ...grpc.CallOption) (*CreatePreTransfer_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePreTransfer_Response)
	err := c.cc.Invoke(ctx, PaymentService_CreatePreTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) ConfirmPreTransfer(ctx context.Context, in *ConfirmPreTransfer_Request, opts ...grpc.CallOption) (*ConfirmPreTransfer_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPreTransfer_Response)
	err := c.cc.Invoke(ctx, PaymentService_ConfirmPreTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) CollectMoney(ctx context.Context, in *CollectMoney_Request, opts ...grpc.CallOption) (*CollectMoney_Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectMoney_Response)
	err := c.cc.Invoke(ctx, PaymentService_CollectMoney_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
//
// PaymentService 支付服务
type PaymentServiceServer interface {
	// GeneratePayQCode 生成支付收款二维码
	GeneratePayQCode(context.Context, *GeneratePayQCode_Request) (*GeneratePayQCode_Response, error)
	// GetBandCardList 获取已绑定银行卡及余额
	GetBandCardList(context.Context, *GetBandCardList_Request) (*GetBandCardList_Response, error)
	// CreateHongBao 创建红包
	CreateHongBao(context.Context, *CreateHongBao_Request) (*CreateHongBao_Response, error)
	// ReceiveHongBao 接收红包
	ReceiveHongBao(context.Context, *ReceiveHongBao_Request) (*ReceiveHongBao_Response, error)
	// OpenHongBao 打开红包
	OpenHongBao(context.Context, *OpenHongBao_Request) (*OpenHongBao_Response, error)
	// GrabHongBao 抢红包
	GrabHongBao(context.Context, *GrabHongBao_Request) (*GrabHongBao_Response, error)
	// QueryHongBaoDetail 查询红包领取详情
	QueryHongBaoDetail(context.Context, *QueryHongBaoDetail_Request) (*QueryHongBaoDetail_Response, error)
	// QueryHongBaoList 查询红包领取列表
	QueryHongBaoList(context.Context, *QueryHongBaoList_Request) (*QueryHongBaoList_Response, error)
	// CreatePreTransfer 创建转账
	CreatePreTransfer(context.Context, *CreatePreTransfer_Request) (*CreatePreTransfer_Response, error)
	// ConfirmPreTransfer 确认转账
	ConfirmPreTransfer(context.Context, *ConfirmPreTransfer_Request) (*ConfirmPreTransfer_Response, error)
	// CollectMoney 确认收款
	CollectMoney(context.Context, *CollectMoney_Request) (*CollectMoney_Response, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) GeneratePayQCode(context.Context, *GeneratePayQCode_Request) (*GeneratePayQCode_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GeneratePayQCode not implemented")
}
func (UnimplementedPaymentServiceServer) GetBandCardList(context.Context, *GetBandCardList_Request) (*GetBandCardList_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBandCardList not implemented")
}
func (UnimplementedPaymentServiceServer) CreateHongBao(context.Context, *CreateHongBao_Request) (*CreateHongBao_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateHongBao not implemented")
}
func (UnimplementedPaymentServiceServer) ReceiveHongBao(context.Context, *ReceiveHongBao_Request) (*ReceiveHongBao_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ReceiveHongBao not implemented")
}
func (UnimplementedPaymentServiceServer) OpenHongBao(context.Context, *OpenHongBao_Request) (*OpenHongBao_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method OpenHongBao not implemented")
}
func (UnimplementedPaymentServiceServer) GrabHongBao(context.Context, *GrabHongBao_Request) (*GrabHongBao_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method GrabHongBao not implemented")
}
func (UnimplementedPaymentServiceServer) QueryHongBaoDetail(context.Context, *QueryHongBaoDetail_Request) (*QueryHongBaoDetail_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryHongBaoDetail not implemented")
}
func (UnimplementedPaymentServiceServer) QueryHongBaoList(context.Context, *QueryHongBaoList_Request) (*QueryHongBaoList_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryHongBaoList not implemented")
}
func (UnimplementedPaymentServiceServer) CreatePreTransfer(context.Context, *CreatePreTransfer_Request) (*CreatePreTransfer_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePreTransfer not implemented")
}
func (UnimplementedPaymentServiceServer) ConfirmPreTransfer(context.Context, *ConfirmPreTransfer_Request) (*ConfirmPreTransfer_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPreTransfer not implemented")
}
func (UnimplementedPaymentServiceServer) CollectMoney(context.Context, *CollectMoney_Request) (*CollectMoney_Response, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectMoney not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_GeneratePayQCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeneratePayQCode_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GeneratePayQCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GeneratePayQCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GeneratePayQCode(ctx, req.(*GeneratePayQCode_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GetBandCardList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBandCardList_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GetBandCardList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GetBandCardList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GetBandCardList(ctx, req.(*GetBandCardList_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreateHongBao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateHongBao_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreateHongBao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreateHongBao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreateHongBao(ctx, req.(*CreateHongBao_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ReceiveHongBao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveHongBao_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ReceiveHongBao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ReceiveHongBao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ReceiveHongBao(ctx, req.(*ReceiveHongBao_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_OpenHongBao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenHongBao_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).OpenHongBao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_OpenHongBao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).OpenHongBao(ctx, req.(*OpenHongBao_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_GrabHongBao_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GrabHongBao_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).GrabHongBao(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_GrabHongBao_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).GrabHongBao(ctx, req.(*GrabHongBao_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_QueryHongBaoDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHongBaoDetail_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).QueryHongBaoDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_QueryHongBaoDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).QueryHongBaoDetail(ctx, req.(*QueryHongBaoDetail_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_QueryHongBaoList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHongBaoList_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).QueryHongBaoList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_QueryHongBaoList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).QueryHongBaoList(ctx, req.(*QueryHongBaoList_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CreatePreTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePreTransfer_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CreatePreTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CreatePreTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CreatePreTransfer(ctx, req.(*CreatePreTransfer_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_ConfirmPreTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPreTransfer_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).ConfirmPreTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_ConfirmPreTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).ConfirmPreTransfer(ctx, req.(*ConfirmPreTransfer_Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_CollectMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectMoney_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).CollectMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_CollectMoney_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).CollectMoney(ctx, req.(*CollectMoney_Request))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GeneratePayQCode",
			Handler:    _PaymentService_GeneratePayQCode_Handler,
		},
		{
			MethodName: "GetBandCardList",
			Handler:    _PaymentService_GetBandCardList_Handler,
		},
		{
			MethodName: "CreateHongBao",
			Handler:    _PaymentService_CreateHongBao_Handler,
		},
		{
			MethodName: "ReceiveHongBao",
			Handler:    _PaymentService_ReceiveHongBao_Handler,
		},
		{
			MethodName: "OpenHongBao",
			Handler:    _PaymentService_OpenHongBao_Handler,
		},
		{
			MethodName: "GrabHongBao",
			Handler:    _PaymentService_GrabHongBao_Handler,
		},
		{
			MethodName: "QueryHongBaoDetail",
			Handler:    _PaymentService_QueryHongBaoDetail_Handler,
		},
		{
			MethodName: "QueryHongBaoList",
			Handler:    _PaymentService_QueryHongBaoList_Handler,
		},
		{
			MethodName: "CreatePreTransfer",
			Handler:    _PaymentService_CreatePreTransfer_Handler,
		},
		{
			MethodName: "ConfirmPreTransfer",
			Handler:    _PaymentService_ConfirmPreTransfer_Handler,
		},
		{
			MethodName: "CollectMoney",
			Handler:    _PaymentService_CollectMoney_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payment/payment.proto",
}
