// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: official/official.proto

package official

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BaseResult 通用结果
type BaseResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`      // 返回码
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"` // 返回消息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseResult) Reset() {
	*x = BaseResult{}
	mi := &file_official_official_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseResult) ProtoMessage() {}

func (x *BaseResult) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseResult.ProtoReflect.Descriptor instead.
func (*BaseResult) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{0}
}

func (x *BaseResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BaseResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Buffer 字节缓冲区
type Buffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          uint32                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"` // 数据长度
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`  // 数据内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Buffer) Reset() {
	*x = Buffer{}
	mi := &file_official_official_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Buffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Buffer) ProtoMessage() {}

func (x *Buffer) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Buffer.ProtoReflect.Descriptor instead.
func (*Buffer) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{1}
}

func (x *Buffer) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Buffer) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// JSAPIPermissionBitSet JSAPI 权限位集
type JSAPIPermissionBitSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value1        uint32                 `protobuf:"varint,1,opt,name=value1,proto3" json:"value1,omitempty"` // 权限值1
	Value2        uint32                 `protobuf:"varint,2,opt,name=value2,proto3" json:"value2,omitempty"` // 权限值2
	Value3        uint32                 `protobuf:"varint,3,opt,name=value3,proto3" json:"value3,omitempty"` // 权限值3
	Value4        uint32                 `protobuf:"varint,4,opt,name=value4,proto3" json:"value4,omitempty"` // 权限值4
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSAPIPermissionBitSet) Reset() {
	*x = JSAPIPermissionBitSet{}
	mi := &file_official_official_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSAPIPermissionBitSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSAPIPermissionBitSet) ProtoMessage() {}

func (x *JSAPIPermissionBitSet) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSAPIPermissionBitSet.ProtoReflect.Descriptor instead.
func (*JSAPIPermissionBitSet) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{2}
}

func (x *JSAPIPermissionBitSet) GetValue1() uint32 {
	if x != nil {
		return x.Value1
	}
	return 0
}

func (x *JSAPIPermissionBitSet) GetValue2() uint32 {
	if x != nil {
		return x.Value2
	}
	return 0
}

func (x *JSAPIPermissionBitSet) GetValue3() uint32 {
	if x != nil {
		return x.Value3
	}
	return 0
}

func (x *JSAPIPermissionBitSet) GetValue4() uint32 {
	if x != nil {
		return x.Value4
	}
	return 0
}

// BizScopeInfo 业务授权范围信息
type BizScopeInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Scope            string                 `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`                                               // 授权范围
	ScopeStatus      uint32                 `protobuf:"varint,2,opt,name=scope_status,json=scopeStatus,proto3" json:"scope_status,omitempty"`               // 授权范围状态
	ScopeDescription string                 `protobuf:"bytes,3,opt,name=scope_description,json=scopeDescription,proto3" json:"scope_description,omitempty"` // 授权范围说明
	ApiCount         uint32                 `protobuf:"varint,4,opt,name=api_count,json=apiCount,proto3" json:"api_count,omitempty"`                        // API 数量
	ApiList          []string               `protobuf:"bytes,5,rep,name=api_list,json=apiList,proto3" json:"api_list,omitempty"`                            // API 列表
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BizScopeInfo) Reset() {
	*x = BizScopeInfo{}
	mi := &file_official_official_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BizScopeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BizScopeInfo) ProtoMessage() {}

func (x *BizScopeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BizScopeInfo.ProtoReflect.Descriptor instead.
func (*BizScopeInfo) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{3}
}

func (x *BizScopeInfo) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *BizScopeInfo) GetScopeStatus() uint32 {
	if x != nil {
		return x.ScopeStatus
	}
	return 0
}

func (x *BizScopeInfo) GetScopeDescription() string {
	if x != nil {
		return x.ScopeDescription
	}
	return ""
}

func (x *BizScopeInfo) GetApiCount() uint32 {
	if x != nil {
		return x.ApiCount
	}
	return 0
}

func (x *BizScopeInfo) GetApiList() []string {
	if x != nil {
		return x.ApiList
	}
	return nil
}

// HttpHeader HTTP 头
type HttpHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`     // 键
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"` // 值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpHeader) Reset() {
	*x = HttpHeader{}
	mi := &file_official_official_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHeader) ProtoMessage() {}

func (x *HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpHeader.ProtoReflect.Descriptor instead.
func (*HttpHeader) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{4}
}

func (x *HttpHeader) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HttpHeader) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// JSAPIResult JSAPI 基础响应
type JSAPIResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`  // 返回码
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 错误信息
	Json          string                 `protobuf:"bytes,3,opt,name=json,proto3" json:"json,omitempty"`   // 微信响应 JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSAPIResult) Reset() {
	*x = JSAPIResult{}
	mi := &file_official_official_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSAPIResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSAPIResult) ProtoMessage() {}

func (x *JSAPIResult) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSAPIResult.ProtoReflect.Descriptor instead.
func (*JSAPIResult) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{5}
}

func (x *JSAPIResult) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JSAPIResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *JSAPIResult) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

// ArticleResult 文章操作结果
type ArticleResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResponseBody  string                 `protobuf:"bytes,1,opt,name=response_body,json=responseBody,proto3" json:"response_body,omitempty"`                                             // HTTP 响应体
	Cookies       string                 `protobuf:"bytes,2,opt,name=cookies,proto3" json:"cookies,omitempty"`                                                                           // Cookie
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 响应头
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleResult) Reset() {
	*x = ArticleResult{}
	mi := &file_official_official_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleResult) ProtoMessage() {}

func (x *ArticleResult) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleResult.ProtoReflect.Descriptor instead.
func (*ArticleResult) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{6}
}

func (x *ArticleResult) GetResponseBody() string {
	if x != nil {
		return x.ResponseBody
	}
	return ""
}

func (x *ArticleResult) GetCookies() string {
	if x != nil {
		return x.Cookies
	}
	return ""
}

func (x *ArticleResult) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type Follow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow) Reset() {
	*x = Follow{}
	mi := &file_official_official_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow) ProtoMessage() {}

func (x *Follow) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow.ProtoReflect.Descriptor instead.
func (*Follow) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{7}
}

type Quit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quit) Reset() {
	*x = Quit{}
	mi := &file_official_official_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quit) ProtoMessage() {}

func (x *Quit) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quit.ProtoReflect.Descriptor instead.
func (*Quit) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{8}
}

type MpGetA8Key struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpGetA8Key) Reset() {
	*x = MpGetA8Key{}
	mi := &file_official_official_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpGetA8Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpGetA8Key) ProtoMessage() {}

func (x *MpGetA8Key) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpGetA8Key.ProtoReflect.Descriptor instead.
func (*MpGetA8Key) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{9}
}

type JSAPIPreVerify struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSAPIPreVerify) Reset() {
	*x = JSAPIPreVerify{}
	mi := &file_official_official_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSAPIPreVerify) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSAPIPreVerify) ProtoMessage() {}

func (x *JSAPIPreVerify) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSAPIPreVerify.ProtoReflect.Descriptor instead.
func (*JSAPIPreVerify) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{10}
}

type OauthAuthorize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthAuthorize) Reset() {
	*x = OauthAuthorize{}
	mi := &file_official_official_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthAuthorize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthAuthorize) ProtoMessage() {}

func (x *OauthAuthorize) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthAuthorize.ProtoReflect.Descriptor instead.
func (*OauthAuthorize) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{11}
}

type ReadArticle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArticle) Reset() {
	*x = ReadArticle{}
	mi := &file_official_official_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArticle) ProtoMessage() {}

func (x *ReadArticle) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArticle.ProtoReflect.Descriptor instead.
func (*ReadArticle) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{12}
}

type LikeArticle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticle) Reset() {
	*x = LikeArticle{}
	mi := &file_official_official_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticle) ProtoMessage() {}

func (x *LikeArticle) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticle.ProtoReflect.Descriptor instead.
func (*LikeArticle) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{13}
}

type Follow_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         string                 `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"` // 公众号 AppID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow_Request) Reset() {
	*x = Follow_Request{}
	mi := &file_official_official_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow_Request) ProtoMessage() {}

func (x *Follow_Request) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow_Request.ProtoReflect.Descriptor instead.
func (*Follow_Request) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{7, 0}
}

func (x *Follow_Request) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

type Follow_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseResult    *BaseResult            `protobuf:"bytes,1,opt,name=base_result,json=baseResult,proto3" json:"base_result,omitempty"` // 基础结果
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`                       // 公众号用户名
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follow_Response) Reset() {
	*x = Follow_Response{}
	mi := &file_official_official_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follow_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follow_Response) ProtoMessage() {}

func (x *Follow_Response) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follow_Response.ProtoReflect.Descriptor instead.
func (*Follow_Response) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{7, 1}
}

func (x *Follow_Response) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

func (x *Follow_Response) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type Quit_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Appid         string                 `protobuf:"bytes,1,opt,name=appid,proto3" json:"appid,omitempty"` // 公众号 AppID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quit_Request) Reset() {
	*x = Quit_Request{}
	mi := &file_official_official_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quit_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quit_Request) ProtoMessage() {}

func (x *Quit_Request) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quit_Request.ProtoReflect.Descriptor instead.
func (*Quit_Request) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{8, 0}
}

func (x *Quit_Request) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

type Quit_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                               // 返回码
	Count         uint32                 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`                             // 操作结果数量
	ResultCode    int32                  `protobuf:"varint,3,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"` // 结果码
	Message       []byte                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`                          // 错误信息内容
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quit_Response) Reset() {
	*x = Quit_Response{}
	mi := &file_official_official_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quit_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quit_Response) ProtoMessage() {}

func (x *Quit_Response) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quit_Response.ProtoReflect.Descriptor instead.
func (*Quit_Response) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{8, 1}
}

func (x *Quit_Response) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Quit_Response) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Quit_Response) GetResultCode() int32 {
	if x != nil {
		return x.ResultCode
	}
	return 0
}

func (x *Quit_Response) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

type MpGetA8Key_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // 请求 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MpGetA8Key_Request) Reset() {
	*x = MpGetA8Key_Request{}
	mi := &file_official_official_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpGetA8Key_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpGetA8Key_Request) ProtoMessage() {}

func (x *MpGetA8Key_Request) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpGetA8Key_Request.ProtoReflect.Descriptor instead.
func (*MpGetA8Key_Request) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{9, 0}
}

func (x *MpGetA8Key_Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MpGetA8Key_Response struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BaseResult        *BaseResult            `protobuf:"bytes,1,opt,name=base_result,json=baseResult,proto3" json:"base_result,omitempty"`                         // 基础结果
	FullUrl           string                 `protobuf:"bytes,2,opt,name=full_url,json=fullUrl,proto3" json:"full_url,omitempty"`                                  // 完整 URL
	A8Key             string                 `protobuf:"bytes,3,opt,name=a8_key,json=a8Key,proto3" json:"a8_key,omitempty"`                                        // A8 密钥
	ActionCode        string                 `protobuf:"bytes,4,opt,name=action_code,json=actionCode,proto3" json:"action_code,omitempty"`                         // 动作码
	Title             string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`                                                     // 标题
	Content           string                 `protobuf:"bytes,6,opt,name=content,proto3" json:"content,omitempty"`                                                 // 内容
	JsapiPermission   *JSAPIPermissionBitSet `protobuf:"bytes,7,opt,name=jsapi_permission,json=jsapiPermission,proto3" json:"jsapi_permission,omitempty"`          // JSAPI 权限位集
	GeneralControl    uint32                 `protobuf:"varint,8,opt,name=general_control,json=generalControl,proto3" json:"general_control,omitempty"`            // 通用控制值
	UserName          string                 `protobuf:"bytes,9,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`                               // 用户名
	ShareUrl          string                 `protobuf:"bytes,15,opt,name=share_url,json=shareUrl,proto3" json:"share_url,omitempty"`                              // 分享 URL
	ScopeCount        uint32                 `protobuf:"varint,16,opt,name=scope_count,json=scopeCount,proto3" json:"scope_count,omitempty"`                       // 授权范围数量
	ScopeList         []*BizScopeInfo        `protobuf:"bytes,17,rep,name=scope_list,json=scopeList,proto3" json:"scope_list,omitempty"`                           // 授权范围列表
	AntispamTicket    string                 `protobuf:"bytes,18,opt,name=antispam_ticket,json=antispamTicket,proto3" json:"antispam_ticket,omitempty"`            // 反垃圾票据
	Ssid              string                 `protobuf:"bytes,20,opt,name=ssid,proto3" json:"ssid,omitempty"`                                                      // SSID
	Mid               string                 `protobuf:"bytes,21,opt,name=mid,proto3" json:"mid,omitempty"`                                                        // MID
	DeepLink          uint64                 `protobuf:"varint,22,opt,name=deep_link,json=deepLink,proto3" json:"deep_link,omitempty"`                             // Deep Link
	JsapiControlBytes *Buffer                `protobuf:"bytes,23,opt,name=jsapi_control_bytes,json=jsapiControlBytes,proto3" json:"jsapi_control_bytes,omitempty"` // JSAPI 控制字节流
	HttpHeaderCount   uint32                 `protobuf:"varint,24,opt,name=http_header_count,json=httpHeaderCount,proto3" json:"http_header_count,omitempty"`      // HTTP 头数量
	HttpHeaderList    []*HttpHeader          `protobuf:"bytes,25,rep,name=http_header_list,json=httpHeaderList,proto3" json:"http_header_list,omitempty"`          // HTTP 头列表
	Wording           string                 `protobuf:"bytes,26,opt,name=wording,proto3" json:"wording,omitempty"`                                                // 文案
	Avatar            string                 `protobuf:"bytes,27,opt,name=avatar,proto3" json:"avatar,omitempty"`                                                  // 头像 URL
	Cookie            *Buffer                `protobuf:"bytes,28,opt,name=cookie,proto3" json:"cookie,omitempty"`                                                  // Cookie
	MenuWording       string                 `protobuf:"bytes,29,opt,name=menu_wording,json=menuWording,proto3" json:"menu_wording,omitempty"`                     // 菜单文案
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MpGetA8Key_Response) Reset() {
	*x = MpGetA8Key_Response{}
	mi := &file_official_official_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MpGetA8Key_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MpGetA8Key_Response) ProtoMessage() {}

func (x *MpGetA8Key_Response) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MpGetA8Key_Response.ProtoReflect.Descriptor instead.
func (*MpGetA8Key_Response) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{9, 1}
}

func (x *MpGetA8Key_Response) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

func (x *MpGetA8Key_Response) GetFullUrl() string {
	if x != nil {
		return x.FullUrl
	}
	return ""
}

func (x *MpGetA8Key_Response) GetA8Key() string {
	if x != nil {
		return x.A8Key
	}
	return ""
}

func (x *MpGetA8Key_Response) GetActionCode() string {
	if x != nil {
		return x.ActionCode
	}
	return ""
}

func (x *MpGetA8Key_Response) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MpGetA8Key_Response) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MpGetA8Key_Response) GetJsapiPermission() *JSAPIPermissionBitSet {
	if x != nil {
		return x.JsapiPermission
	}
	return nil
}

func (x *MpGetA8Key_Response) GetGeneralControl() uint32 {
	if x != nil {
		return x.GeneralControl
	}
	return 0
}

func (x *MpGetA8Key_Response) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *MpGetA8Key_Response) GetShareUrl() string {
	if x != nil {
		return x.ShareUrl
	}
	return ""
}

func (x *MpGetA8Key_Response) GetScopeCount() uint32 {
	if x != nil {
		return x.ScopeCount
	}
	return 0
}

func (x *MpGetA8Key_Response) GetScopeList() []*BizScopeInfo {
	if x != nil {
		return x.ScopeList
	}
	return nil
}

func (x *MpGetA8Key_Response) GetAntispamTicket() string {
	if x != nil {
		return x.AntispamTicket
	}
	return ""
}

func (x *MpGetA8Key_Response) GetSsid() string {
	if x != nil {
		return x.Ssid
	}
	return ""
}

func (x *MpGetA8Key_Response) GetMid() string {
	if x != nil {
		return x.Mid
	}
	return ""
}

func (x *MpGetA8Key_Response) GetDeepLink() uint64 {
	if x != nil {
		return x.DeepLink
	}
	return 0
}

func (x *MpGetA8Key_Response) GetJsapiControlBytes() *Buffer {
	if x != nil {
		return x.JsapiControlBytes
	}
	return nil
}

func (x *MpGetA8Key_Response) GetHttpHeaderCount() uint32 {
	if x != nil {
		return x.HttpHeaderCount
	}
	return 0
}

func (x *MpGetA8Key_Response) GetHttpHeaderList() []*HttpHeader {
	if x != nil {
		return x.HttpHeaderList
	}
	return nil
}

func (x *MpGetA8Key_Response) GetWording() string {
	if x != nil {
		return x.Wording
	}
	return ""
}

func (x *MpGetA8Key_Response) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *MpGetA8Key_Response) GetCookie() *Buffer {
	if x != nil {
		return x.Cookie
	}
	return nil
}

func (x *MpGetA8Key_Response) GetMenuWording() string {
	if x != nil {
		return x.MenuWording
	}
	return ""
}

type JSAPIPreVerify_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`                              // 页面 URL
	Appid         string                 `protobuf:"bytes,2,opt,name=appid,proto3" json:"appid,omitempty"`                          // 公众号 AppID
	JsapiList     []string               `protobuf:"bytes,3,rep,name=jsapi_list,json=jsapiList,proto3" json:"jsapi_list,omitempty"` // JSAPI 列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JSAPIPreVerify_Request) Reset() {
	*x = JSAPIPreVerify_Request{}
	mi := &file_official_official_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSAPIPreVerify_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSAPIPreVerify_Request) ProtoMessage() {}

func (x *JSAPIPreVerify_Request) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSAPIPreVerify_Request.ProtoReflect.Descriptor instead.
func (*JSAPIPreVerify_Request) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{10, 0}
}

func (x *JSAPIPreVerify_Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *JSAPIPreVerify_Request) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

func (x *JSAPIPreVerify_Request) GetJsapiList() []string {
	if x != nil {
		return x.JsapiList
	}
	return nil
}

type JSAPIPreVerify_Response struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BaseResult     *BaseResult            `protobuf:"bytes,1,opt,name=base_result,json=baseResult,proto3" json:"base_result,omitempty"`               // 基础结果
	JsapiResult    *JSAPIResult           `protobuf:"bytes,2,opt,name=jsapi_result,json=jsapiResult,proto3" json:"jsapi_result,omitempty"`            // JSAPI 基础响应
	VerifyInfoList []string               `protobuf:"bytes,3,rep,name=verify_info_list,json=verifyInfoList,proto3" json:"verify_info_list,omitempty"` // 验证信息列表
	DomainPathList []string               `protobuf:"bytes,4,rep,name=domain_path_list,json=domainPathList,proto3" json:"domain_path_list,omitempty"` // 域名路径列表
	AppAvatarUrl   string                 `protobuf:"bytes,5,opt,name=app_avatar_url,json=appAvatarUrl,proto3" json:"app_avatar_url,omitempty"`       // App 头像 URL
	AppNickname    string                 `protobuf:"bytes,6,opt,name=app_nickname,json=appNickname,proto3" json:"app_nickname,omitempty"`            // App 昵称
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *JSAPIPreVerify_Response) Reset() {
	*x = JSAPIPreVerify_Response{}
	mi := &file_official_official_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JSAPIPreVerify_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JSAPIPreVerify_Response) ProtoMessage() {}

func (x *JSAPIPreVerify_Response) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JSAPIPreVerify_Response.ProtoReflect.Descriptor instead.
func (*JSAPIPreVerify_Response) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{10, 1}
}

func (x *JSAPIPreVerify_Response) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

func (x *JSAPIPreVerify_Response) GetJsapiResult() *JSAPIResult {
	if x != nil {
		return x.JsapiResult
	}
	return nil
}

func (x *JSAPIPreVerify_Response) GetVerifyInfoList() []string {
	if x != nil {
		return x.VerifyInfoList
	}
	return nil
}

func (x *JSAPIPreVerify_Response) GetDomainPathList() []string {
	if x != nil {
		return x.DomainPathList
	}
	return nil
}

func (x *JSAPIPreVerify_Response) GetAppAvatarUrl() string {
	if x != nil {
		return x.AppAvatarUrl
	}
	return ""
}

func (x *JSAPIPreVerify_Response) GetAppNickname() string {
	if x != nil {
		return x.AppNickname
	}
	return ""
}

type OauthAuthorize_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`     // OAuth URL
	Appid         string                 `protobuf:"bytes,2,opt,name=appid,proto3" json:"appid,omitempty"` // 公众号 AppID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OauthAuthorize_Request) Reset() {
	*x = OauthAuthorize_Request{}
	mi := &file_official_official_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthAuthorize_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthAuthorize_Request) ProtoMessage() {}

func (x *OauthAuthorize_Request) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthAuthorize_Request.ProtoReflect.Descriptor instead.
func (*OauthAuthorize_Request) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{11, 0}
}

func (x *OauthAuthorize_Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *OauthAuthorize_Request) GetAppid() string {
	if x != nil {
		return x.Appid
	}
	return ""
}

type OauthAuthorize_Response struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	BaseResult              *BaseResult            `protobuf:"bytes,1,opt,name=base_result,json=baseResult,proto3" json:"base_result,omitempty"`                                                // 基础结果
	ScopeList               [][]byte               `protobuf:"bytes,2,rep,name=scope_list,json=scopeList,proto3" json:"scope_list,omitempty"`                                                   // 授权范围列表
	AppName                 string                 `protobuf:"bytes,4,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`                                                         // App 名称
	AppIconUrl              string                 `protobuf:"bytes,5,opt,name=app_icon_url,json=appIconUrl,proto3" json:"app_icon_url,omitempty"`                                              // App 图标 URL
	RedirectUrl             string                 `protobuf:"bytes,6,opt,name=redirect_url,json=redirectUrl,proto3" json:"redirect_url,omitempty"`                                             // 重定向 URL
	IsRecentHasAuth         bool                   `protobuf:"varint,9,opt,name=is_recent_has_auth,json=isRecentHasAuth,proto3" json:"is_recent_has_auth,omitempty"`                            // 最近是否有授权
	IsSilentAuth            bool                   `protobuf:"varint,10,opt,name=is_silent_auth,json=isSilentAuth,proto3" json:"is_silent_auth,omitempty"`                                      // 是否静默授权
	IsCallServerWhenConfirm bool                   `protobuf:"varint,11,opt,name=is_call_server_when_confirm,json=isCallServerWhenConfirm,proto3" json:"is_call_server_when_confirm,omitempty"` // 确认时是否调用服务器
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OauthAuthorize_Response) Reset() {
	*x = OauthAuthorize_Response{}
	mi := &file_official_official_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OauthAuthorize_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OauthAuthorize_Response) ProtoMessage() {}

func (x *OauthAuthorize_Response) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OauthAuthorize_Response.ProtoReflect.Descriptor instead.
func (*OauthAuthorize_Response) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{11, 1}
}

func (x *OauthAuthorize_Response) GetBaseResult() *BaseResult {
	if x != nil {
		return x.BaseResult
	}
	return nil
}

func (x *OauthAuthorize_Response) GetScopeList() [][]byte {
	if x != nil {
		return x.ScopeList
	}
	return nil
}

func (x *OauthAuthorize_Response) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *OauthAuthorize_Response) GetAppIconUrl() string {
	if x != nil {
		return x.AppIconUrl
	}
	return ""
}

func (x *OauthAuthorize_Response) GetRedirectUrl() string {
	if x != nil {
		return x.RedirectUrl
	}
	return ""
}

func (x *OauthAuthorize_Response) GetIsRecentHasAuth() bool {
	if x != nil {
		return x.IsRecentHasAuth
	}
	return false
}

func (x *OauthAuthorize_Response) GetIsSilentAuth() bool {
	if x != nil {
		return x.IsSilentAuth
	}
	return false
}

func (x *OauthAuthorize_Response) GetIsCallServerWhenConfirm() bool {
	if x != nil {
		return x.IsCallServerWhenConfirm
	}
	return false
}

type ReadArticle_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // 文章 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArticle_Request) Reset() {
	*x = ReadArticle_Request{}
	mi := &file_official_official_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArticle_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArticle_Request) ProtoMessage() {}

func (x *ReadArticle_Request) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArticle_Request.ProtoReflect.Descriptor instead.
func (*ReadArticle_Request) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{12, 0}
}

func (x *ReadArticle_Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ReadArticle_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ArticleResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // 文章操作结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadArticle_Response) Reset() {
	*x = ReadArticle_Response{}
	mi := &file_official_official_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadArticle_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadArticle_Response) ProtoMessage() {}

func (x *ReadArticle_Response) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadArticle_Response.ProtoReflect.Descriptor instead.
func (*ReadArticle_Response) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{12, 1}
}

func (x *ReadArticle_Response) GetResult() *ArticleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type LikeArticle_Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // 文章 URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticle_Request) Reset() {
	*x = LikeArticle_Request{}
	mi := &file_official_official_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticle_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticle_Request) ProtoMessage() {}

func (x *LikeArticle_Request) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticle_Request.ProtoReflect.Descriptor instead.
func (*LikeArticle_Request) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{13, 0}
}

func (x *LikeArticle_Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type LikeArticle_Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *ArticleResult         `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"` // 文章操作结果
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeArticle_Response) Reset() {
	*x = LikeArticle_Response{}
	mi := &file_official_official_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeArticle_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeArticle_Response) ProtoMessage() {}

func (x *LikeArticle_Response) ProtoReflect() protoreflect.Message {
	mi := &file_official_official_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeArticle_Response.ProtoReflect.Descriptor instead.
func (*LikeArticle_Response) Descriptor() ([]byte, []int) {
	return file_official_official_proto_rawDescGZIP(), []int{13, 1}
}

func (x *LikeArticle_Response) GetResult() *ArticleResult {
	if x != nil {
		return x.Result
	}
	return nil
}

var File_official_official_proto protoreflect.FileDescriptor

const file_official_official_proto_rawDesc = "" +
	"\n" +
	"\x17official/official.proto\x12\bofficial\":\n" +
	"\n" +
	"BaseResult\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x06Buffer\x12\x12\n" +
	"\x04size\x18\x01 \x01(\rR\x04size\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"w\n" +
	"\x15JSAPIPermissionBitSet\x12\x16\n" +
	"\x06value1\x18\x01 \x01(\rR\x06value1\x12\x16\n" +
	"\x06value2\x18\x02 \x01(\rR\x06value2\x12\x16\n" +
	"\x06value3\x18\x03 \x01(\rR\x06value3\x12\x16\n" +
	"\x06value4\x18\x04 \x01(\rR\x06value4\"\xac\x01\n" +
	"\fBizScopeInfo\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12!\n" +
	"\fscope_status\x18\x02 \x01(\rR\vscopeStatus\x12+\n" +
	"\x11scope_description\x18\x03 \x01(\tR\x10scopeDescription\x12\x1b\n" +
	"\tapi_count\x18\x04 \x01(\rR\bapiCount\x12\x19\n" +
	"\bapi_list\x18\x05 \x03(\tR\aapiList\"4\n" +
	"\n" +
	"HttpHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"K\n" +
	"\vJSAPIResult\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12\x12\n" +
	"\x04json\x18\x03 \x01(\tR\x04json\"\xca\x01\n" +
	"\rArticleResult\x12#\n" +
	"\rresponse_body\x18\x01 \x01(\tR\fresponseBody\x12\x18\n" +
	"\acookies\x18\x02 \x01(\tR\acookies\x12>\n" +
	"\aheaders\x18\x03 \x03(\v2$.official.ArticleResult.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x88\x01\n" +
	"\x06Follow\x1a\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\tR\x05appid\x1a]\n" +
	"\bResponse\x125\n" +
	"\vbase_result\x18\x01 \x01(\v2\x14.official.BaseResultR\n" +
	"baseResult\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"\x98\x01\n" +
	"\x04Quit\x1a\x1f\n" +
	"\aRequest\x12\x14\n" +
	"\x05appid\x18\x01 \x01(\tR\x05appid\x1ao\n" +
	"\bResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x14\n" +
	"\x05count\x18\x02 \x01(\rR\x05count\x12\x1f\n" +
	"\vresult_code\x18\x03 \x01(\x05R\n" +
	"resultCode\x12\x18\n" +
	"\amessage\x18\x04 \x01(\fR\amessage\"\x90\a\n" +
	"\n" +
	"MpGetA8Key\x1a\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x1a\xe4\x06\n" +
	"\bResponse\x125\n" +
	"\vbase_result\x18\x01 \x01(\v2\x14.official.BaseResultR\n" +
	"baseResult\x12\x19\n" +
	"\bfull_url\x18\x02 \x01(\tR\afullUrl\x12\x15\n" +
	"\x06a8_key\x18\x03 \x01(\tR\x05a8Key\x12\x1f\n" +
	"\vaction_code\x18\x04 \x01(\tR\n" +
	"actionCode\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x06 \x01(\tR\acontent\x12J\n" +
	"\x10jsapi_permission\x18\a \x01(\v2\x1f.official.JSAPIPermissionBitSetR\x0fjsapiPermission\x12'\n" +
	"\x0fgeneral_control\x18\b \x01(\rR\x0egeneralControl\x12\x1b\n" +
	"\tuser_name\x18\t \x01(\tR\buserName\x12\x1b\n" +
	"\tshare_url\x18\x0f \x01(\tR\bshareUrl\x12\x1f\n" +
	"\vscope_count\x18\x10 \x01(\rR\n" +
	"scopeCount\x125\n" +
	"\n" +
	"scope_list\x18\x11 \x03(\v2\x16.official.BizScopeInfoR\tscopeList\x12'\n" +
	"\x0fantispam_ticket\x18\x12 \x01(\tR\x0eantispamTicket\x12\x12\n" +
	"\x04ssid\x18\x14 \x01(\tR\x04ssid\x12\x10\n" +
	"\x03mid\x18\x15 \x01(\tR\x03mid\x12\x1b\n" +
	"\tdeep_link\x18\x16 \x01(\x04R\bdeepLink\x12@\n" +
	"\x13jsapi_control_bytes\x18\x17 \x01(\v2\x10.official.BufferR\x11jsapiControlBytes\x12*\n" +
	"\x11http_header_count\x18\x18 \x01(\rR\x0fhttpHeaderCount\x12>\n" +
	"\x10http_header_list\x18\x19 \x03(\v2\x14.official.HttpHeaderR\x0ehttpHeaderList\x12\x18\n" +
	"\awording\x18\x1a \x01(\tR\awording\x12\x16\n" +
	"\x06avatar\x18\x1b \x01(\tR\x06avatar\x12(\n" +
	"\x06cookie\x18\x1c \x01(\v2\x10.official.BufferR\x06cookie\x12!\n" +
	"\fmenu_wording\x18\x1d \x01(\tR\vmenuWording\"\xfd\x02\n" +
	"\x0eJSAPIPreVerify\x1aP\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\tR\x05appid\x12\x1d\n" +
	"\n" +
	"jsapi_list\x18\x03 \x03(\tR\tjsapiList\x1a\x98\x02\n" +
	"\bResponse\x125\n" +
	"\vbase_result\x18\x01 \x01(\v2\x14.official.BaseResultR\n" +
	"baseResult\x128\n" +
	"\fjsapi_result\x18\x02 \x01(\v2\x15.official.JSAPIResultR\vjsapiResult\x12(\n" +
	"\x10verify_info_list\x18\x03 \x03(\tR\x0everifyInfoList\x12(\n" +
	"\x10domain_path_list\x18\x04 \x03(\tR\x0edomainPathList\x12$\n" +
	"\x0eapp_avatar_url\x18\x05 \x01(\tR\fappAvatarUrl\x12!\n" +
	"\fapp_nickname\x18\x06 \x01(\tR\vappNickname\"\x97\x03\n" +
	"\x0eOauthAuthorize\x1a1\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x14\n" +
	"\x05appid\x18\x02 \x01(\tR\x05appid\x1a\xd1\x02\n" +
	"\bResponse\x125\n" +
	"\vbase_result\x18\x01 \x01(\v2\x14.official.BaseResultR\n" +
	"baseResult\x12\x1d\n" +
	"\n" +
	"scope_list\x18\x02 \x03(\fR\tscopeList\x12\x19\n" +
	"\bapp_name\x18\x04 \x01(\tR\aappName\x12 \n" +
	"\fapp_icon_url\x18\x05 \x01(\tR\n" +
	"appIconUrl\x12!\n" +
	"\fredirect_url\x18\x06 \x01(\tR\vredirectUrl\x12+\n" +
	"\x12is_recent_has_auth\x18\t \x01(\bR\x0fisRecentHasAuth\x12$\n" +
	"\x0eis_silent_auth\x18\n" +
	" \x01(\bR\fisSilentAuth\x12<\n" +
	"\x1bis_call_server_when_confirm\x18\v \x01(\bR\x17isCallServerWhenConfirm\"g\n" +
	"\vReadArticle\x1a\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x1a;\n" +
	"\bResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.official.ArticleResultR\x06result\"g\n" +
	"\vLikeArticle\x1a\x1b\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x1a;\n" +
	"\bResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.official.ArticleResultR\x06result2\x9e\x04\n" +
	"\x0fOfficialService\x12=\n" +
	"\x06Follow\x12\x18.official.Follow.Request\x1a\x19.official.Follow.Response\x127\n" +
	"\x04Quit\x12\x16.official.Quit.Request\x1a\x17.official.Quit.Response\x12I\n" +
	"\n" +
	"MpGetA8Key\x12\x1c.official.MpGetA8Key.Request\x1a\x1d.official.MpGetA8Key.Response\x12U\n" +
	"\x0eJSAPIPreVerify\x12 .official.JSAPIPreVerify.Request\x1a!.official.JSAPIPreVerify.Response\x12U\n" +
	"\x0eOauthAuthorize\x12 .official.OauthAuthorize.Request\x1a!.official.OauthAuthorize.Response\x12L\n" +
	"\vReadArticle\x12\x1d.official.ReadArticle.Request\x1a\x1e.official.ReadArticle.Response\x12L\n" +
	"\vLikeArticle\x12\x1d.official.LikeArticle.Request\x1a\x1e.official.LikeArticle.ResponseB\x85\x01\n" +
	"\fcom.officialB\rOfficialProtoP\x01Z&github.com/sbgayhub/golem/sdk/official\xa2\x02\x03OXX\xaa\x02\bOfficial\xca\x02\bOfficial\xe2\x02\x14Official\\GPBMetadata\xea\x02\bOfficialb\x06proto3"

var (
	file_official_official_proto_rawDescOnce sync.Once
	file_official_official_proto_rawDescData []byte
)

func file_official_official_proto_rawDescGZIP() []byte {
	file_official_official_proto_rawDescOnce.Do(func() {
		file_official_official_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_official_official_proto_rawDesc), len(file_official_official_proto_rawDesc)))
	})
	return file_official_official_proto_rawDescData
}

var file_official_official_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_official_official_proto_goTypes = []any{
	(*BaseResult)(nil),              // 0: official.BaseResult
	(*Buffer)(nil),                  // 1: official.Buffer
	(*JSAPIPermissionBitSet)(nil),   // 2: official.JSAPIPermissionBitSet
	(*BizScopeInfo)(nil),            // 3: official.BizScopeInfo
	(*HttpHeader)(nil),              // 4: official.HttpHeader
	(*JSAPIResult)(nil),             // 5: official.JSAPIResult
	(*ArticleResult)(nil),           // 6: official.ArticleResult
	(*Follow)(nil),                  // 7: official.Follow
	(*Quit)(nil),                    // 8: official.Quit
	(*MpGetA8Key)(nil),              // 9: official.MpGetA8Key
	(*JSAPIPreVerify)(nil),          // 10: official.JSAPIPreVerify
	(*OauthAuthorize)(nil),          // 11: official.OauthAuthorize
	(*ReadArticle)(nil),             // 12: official.ReadArticle
	(*LikeArticle)(nil),             // 13: official.LikeArticle
	nil,                             // 14: official.ArticleResult.HeadersEntry
	(*Follow_Request)(nil),          // 15: official.Follow.Request
	(*Follow_Response)(nil),         // 16: official.Follow.Response
	(*Quit_Request)(nil),            // 17: official.Quit.Request
	(*Quit_Response)(nil),           // 18: official.Quit.Response
	(*MpGetA8Key_Request)(nil),      // 19: official.MpGetA8Key.Request
	(*MpGetA8Key_Response)(nil),     // 20: official.MpGetA8Key.Response
	(*JSAPIPreVerify_Request)(nil),  // 21: official.JSAPIPreVerify.Request
	(*JSAPIPreVerify_Response)(nil), // 22: official.JSAPIPreVerify.Response
	(*OauthAuthorize_Request)(nil),  // 23: official.OauthAuthorize.Request
	(*OauthAuthorize_Response)(nil), // 24: official.OauthAuthorize.Response
	(*ReadArticle_Request)(nil),     // 25: official.ReadArticle.Request
	(*ReadArticle_Response)(nil),    // 26: official.ReadArticle.Response
	(*LikeArticle_Request)(nil),     // 27: official.LikeArticle.Request
	(*LikeArticle_Response)(nil),    // 28: official.LikeArticle.Response
}
var file_official_official_proto_depIdxs = []int32{
	14, // 0: official.ArticleResult.headers:type_name -> official.ArticleResult.HeadersEntry
	0,  // 1: official.Follow.Response.base_result:type_name -> official.BaseResult
	0,  // 2: official.MpGetA8Key.Response.base_result:type_name -> official.BaseResult
	2,  // 3: official.MpGetA8Key.Response.jsapi_permission:type_name -> official.JSAPIPermissionBitSet
	3,  // 4: official.MpGetA8Key.Response.scope_list:type_name -> official.BizScopeInfo
	1,  // 5: official.MpGetA8Key.Response.jsapi_control_bytes:type_name -> official.Buffer
	4,  // 6: official.MpGetA8Key.Response.http_header_list:type_name -> official.HttpHeader
	1,  // 7: official.MpGetA8Key.Response.cookie:type_name -> official.Buffer
	0,  // 8: official.JSAPIPreVerify.Response.base_result:type_name -> official.BaseResult
	5,  // 9: official.JSAPIPreVerify.Response.jsapi_result:type_name -> official.JSAPIResult
	0,  // 10: official.OauthAuthorize.Response.base_result:type_name -> official.BaseResult
	6,  // 11: official.ReadArticle.Response.result:type_name -> official.ArticleResult
	6,  // 12: official.LikeArticle.Response.result:type_name -> official.ArticleResult
	15, // 13: official.OfficialService.Follow:input_type -> official.Follow.Request
	17, // 14: official.OfficialService.Quit:input_type -> official.Quit.Request
	19, // 15: official.OfficialService.MpGetA8Key:input_type -> official.MpGetA8Key.Request
	21, // 16: official.OfficialService.JSAPIPreVerify:input_type -> official.JSAPIPreVerify.Request
	23, // 17: official.OfficialService.OauthAuthorize:input_type -> official.OauthAuthorize.Request
	25, // 18: official.OfficialService.ReadArticle:input_type -> official.ReadArticle.Request
	27, // 19: official.OfficialService.LikeArticle:input_type -> official.LikeArticle.Request
	16, // 20: official.OfficialService.Follow:output_type -> official.Follow.Response
	18, // 21: official.OfficialService.Quit:output_type -> official.Quit.Response
	20, // 22: official.OfficialService.MpGetA8Key:output_type -> official.MpGetA8Key.Response
	22, // 23: official.OfficialService.JSAPIPreVerify:output_type -> official.JSAPIPreVerify.Response
	24, // 24: official.OfficialService.OauthAuthorize:output_type -> official.OauthAuthorize.Response
	26, // 25: official.OfficialService.ReadArticle:output_type -> official.ReadArticle.Response
	28, // 26: official.OfficialService.LikeArticle:output_type -> official.LikeArticle.Response
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_official_official_proto_init() }
func file_official_official_proto_init() {
	if File_official_official_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_official_official_proto_rawDesc), len(file_official_official_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_official_official_proto_goTypes,
		DependencyIndexes: file_official_official_proto_depIdxs,
		MessageInfos:      file_official_official_proto_msgTypes,
	}.Build()
	File_official_official_proto = out.File
	file_official_official_proto_goTypes = nil
	file_official_official_proto_depIdxs = nil
}
