// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: api/cdn/cdn_api.proto

package cdnapi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UploadImageResult 聊天图片 CDN 上传结果
type UploadImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`                  // 图片加密 AES 密钥（hex编码）
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`                  // CDN 文件ID
	NewMsgId      uint64                 `protobuf:"varint,3,opt,name=new_msg_id,json=newMsgId,proto3" json:"new_msg_id,omitempty"`         // 新消息ID
	CreateTime    uint32                 `protobuf:"varint,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`     // 创建时间
	FileSize      uint32                 `protobuf:"varint,5,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`           // 文件大小
	FileMd5       string                 `protobuf:"bytes,6,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`               // 文件MD5
	FileWidth     uint32                 `protobuf:"varint,7,opt,name=file_width,json=fileWidth,proto3" json:"file_width,omitempty"`        // 图片宽度
	FileHeight    uint32                 `protobuf:"varint,8,opt,name=file_height,json=fileHeight,proto3" json:"file_height,omitempty"`     // 图片高度
	ThumbSize     uint32                 `protobuf:"varint,9,opt,name=thumb_size,json=thumbSize,proto3" json:"thumb_size,omitempty"`        // 缩略图大小
	ThumbMd5      string                 `protobuf:"bytes,10,opt,name=thumb_md5,json=thumbMd5,proto3" json:"thumb_md5,omitempty"`           // 缩略图MD5
	ThumbWidth    uint32                 `protobuf:"varint,11,opt,name=thumb_width,json=thumbWidth,proto3" json:"thumb_width,omitempty"`    // 缩略图宽度
	ThumbHeight   uint32                 `protobuf:"varint,12,opt,name=thumb_height,json=thumbHeight,proto3" json:"thumb_height,omitempty"` // 缩略图高度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageResult) Reset() {
	*x = UploadImageResult{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageResult) ProtoMessage() {}

func (x *UploadImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageResult.ProtoReflect.Descriptor instead.
func (*UploadImageResult) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{0}
}

func (x *UploadImageResult) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadImageResult) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadImageResult) GetNewMsgId() uint64 {
	if x != nil {
		return x.NewMsgId
	}
	return 0
}

func (x *UploadImageResult) GetCreateTime() uint32 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *UploadImageResult) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadImageResult) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *UploadImageResult) GetFileWidth() uint32 {
	if x != nil {
		return x.FileWidth
	}
	return 0
}

func (x *UploadImageResult) GetFileHeight() uint32 {
	if x != nil {
		return x.FileHeight
	}
	return 0
}

func (x *UploadImageResult) GetThumbSize() uint32 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *UploadImageResult) GetThumbMd5() string {
	if x != nil {
		return x.ThumbMd5
	}
	return ""
}

func (x *UploadImageResult) GetThumbWidth() uint32 {
	if x != nil {
		return x.ThumbWidth
	}
	return 0
}

func (x *UploadImageResult) GetThumbHeight() uint32 {
	if x != nil {
		return x.ThumbHeight
	}
	return 0
}

// UploadSnsImageResult 朋友圈图片 CDN 上传结果
type UploadSnsImageResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`              // CDN 文件URL
	ThumbUrl      string                 `protobuf:"bytes,2,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"`           // CDN 缩略图URL
	FileKey       string                 `protobuf:"bytes,3,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`              // 文件Key
	FileMd5       string                 `protobuf:"bytes,4,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`              // 文件MD5
	ImageWidth    uint32                 `protobuf:"varint,5,opt,name=image_width,json=imageWidth,proto3" json:"image_width,omitempty"`    // 图片宽度
	ImageHeight   uint32                 `protobuf:"varint,6,opt,name=image_height,json=imageHeight,proto3" json:"image_height,omitempty"` // 图片高度
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnsImageResult) Reset() {
	*x = UploadSnsImageResult{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnsImageResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnsImageResult) ProtoMessage() {}

func (x *UploadSnsImageResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnsImageResult.ProtoReflect.Descriptor instead.
func (*UploadSnsImageResult) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{1}
}

func (x *UploadSnsImageResult) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadSnsImageResult) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

func (x *UploadSnsImageResult) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *UploadSnsImageResult) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

func (x *UploadSnsImageResult) GetImageWidth() uint32 {
	if x != nil {
		return x.ImageWidth
	}
	return 0
}

func (x *UploadSnsImageResult) GetImageHeight() uint32 {
	if x != nil {
		return x.ImageHeight
	}
	return 0
}

// UploadVideoResult 聊天视频 CDN 上传结果
type UploadVideoResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AesKey        string                 `protobuf:"bytes,1,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"`           // 视频加密 AES 密钥（hex编码）
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`           // CDN 文件ID
	FileSize      uint32                 `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`    // 视频文件大小
	ThumbSize     uint32                 `protobuf:"varint,4,opt,name=thumb_size,json=thumbSize,proto3" json:"thumb_size,omitempty"` // 缩略图大小
	FileMd5       string                 `protobuf:"bytes,5,opt,name=file_md5,json=fileMd5,proto3" json:"file_md5,omitempty"`        // 视频MD5
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoResult) Reset() {
	*x = UploadVideoResult{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoResult) ProtoMessage() {}

func (x *UploadVideoResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoResult.ProtoReflect.Descriptor instead.
func (*UploadVideoResult) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{2}
}

func (x *UploadVideoResult) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

func (x *UploadVideoResult) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadVideoResult) GetFileSize() uint32 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *UploadVideoResult) GetThumbSize() uint32 {
	if x != nil {
		return x.ThumbSize
	}
	return 0
}

func (x *UploadVideoResult) GetFileMd5() string {
	if x != nil {
		return x.FileMd5
	}
	return ""
}

// UploadSnsVideoResult 朋友圈视频 CDN 上传结果
type UploadSnsVideoResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileUrl       string                 `protobuf:"bytes,1,opt,name=file_url,json=fileUrl,proto3" json:"file_url,omitempty"`    // CDN 视频URL
	ThumbUrl      string                 `protobuf:"bytes,2,opt,name=thumb_url,json=thumbUrl,proto3" json:"thumb_url,omitempty"` // CDN 缩略图URL
	FileId        string                 `protobuf:"bytes,3,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`       // 文件ID
	FileKey       string                 `protobuf:"bytes,4,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`    // 文件Key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadSnsVideoResult) Reset() {
	*x = UploadSnsVideoResult{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadSnsVideoResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadSnsVideoResult) ProtoMessage() {}

func (x *UploadSnsVideoResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadSnsVideoResult.ProtoReflect.Descriptor instead.
func (*UploadSnsVideoResult) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{3}
}

func (x *UploadSnsVideoResult) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

func (x *UploadSnsVideoResult) GetThumbUrl() string {
	if x != nil {
		return x.ThumbUrl
	}
	return ""
}

func (x *UploadSnsVideoResult) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadSnsVideoResult) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

// DownloadImageRequest CDN 下载高清图片请求
type DownloadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // CDN 文件ID
	AesKey        string                 `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"` // AES 密钥（hex编码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadImageRequest) Reset() {
	*x = DownloadImageRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadImageRequest) ProtoMessage() {}

func (x *DownloadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadImageRequest.ProtoReflect.Descriptor instead.
func (*DownloadImageRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{4}
}

func (x *DownloadImageRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadImageRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

// DownloadVideoRequest CDN 下载聊天视频请求
type DownloadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // CDN 文件ID
	AesKey        string                 `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"` // AES 密钥（hex编码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoRequest) Reset() {
	*x = DownloadVideoRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoRequest) ProtoMessage() {}

func (x *DownloadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoRequest.ProtoReflect.Descriptor instead.
func (*DownloadVideoRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{5}
}

func (x *DownloadVideoRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadVideoRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

// DownloadVideoCoverRequest CDN 下载视频封面请求
type DownloadVideoCoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"` // CDN 文件ID
	AesKey        string                 `protobuf:"bytes,2,opt,name=aes_key,json=aesKey,proto3" json:"aes_key,omitempty"` // AES 密钥（hex编码）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadVideoCoverRequest) Reset() {
	*x = DownloadVideoCoverRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadVideoCoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadVideoCoverRequest) ProtoMessage() {}

func (x *DownloadVideoCoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadVideoCoverRequest.ProtoReflect.Descriptor instead.
func (*DownloadVideoCoverRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{6}
}

func (x *DownloadVideoCoverRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *DownloadVideoCoverRequest) GetAesKey() string {
	if x != nil {
		return x.AesKey
	}
	return ""
}

// DownloadSnsVideoRequest CDN 下载朋友圈视频请求
type DownloadSnsVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoUrl      string                 `protobuf:"bytes,1,opt,name=video_url,json=videoUrl,proto3" json:"video_url,omitempty"` // 加密视频 URL
	EncKey        uint64                 `protobuf:"varint,2,opt,name=enc_key,json=encKey,proto3" json:"enc_key,omitempty"`      // 解密密钥
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSnsVideoRequest) Reset() {
	*x = DownloadSnsVideoRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSnsVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSnsVideoRequest) ProtoMessage() {}

func (x *DownloadSnsVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSnsVideoRequest.ProtoReflect.Descriptor instead.
func (*DownloadSnsVideoRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadSnsVideoRequest) GetVideoUrl() string {
	if x != nil {
		return x.VideoUrl
	}
	return ""
}

func (x *DownloadSnsVideoRequest) GetEncKey() uint64 {
	if x != nil {
		return x.EncKey
	}
	return 0
}

// UploadImageRequest CDN 上传聊天图片请求
type UploadImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"` // 接收者 wxid
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`         // 图片二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadImageRequest) Reset() {
	*x = UploadImageRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadImageRequest) ProtoMessage() {}

func (x *UploadImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadImageRequest.ProtoReflect.Descriptor instead.
func (*UploadImageRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{8}
}

func (x *UploadImageRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *UploadImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadMomentsImageRequest CDN 上传朋友圈图片请求
type UploadMomentsImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 图片二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMomentsImageRequest) Reset() {
	*x = UploadMomentsImageRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMomentsImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMomentsImageRequest) ProtoMessage() {}

func (x *UploadMomentsImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMomentsImageRequest.ProtoReflect.Descriptor instead.
func (*UploadMomentsImageRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{9}
}

func (x *UploadMomentsImageRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// UploadVideoRequest CDN 上传聊天视频请求
type UploadVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Receiver      string                 `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`                    // 接收者 wxid
	VideoData     []byte                 `protobuf:"bytes,2,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"` // 视频二进制数据
	ThumbData     []byte                 `protobuf:"bytes,3,opt,name=thumb_data,json=thumbData,proto3" json:"thumb_data,omitempty"` // 缩略图二进制数据
	Duration      uint32                 `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`                   // 视频时长（秒）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadVideoRequest) Reset() {
	*x = UploadVideoRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadVideoRequest) ProtoMessage() {}

func (x *UploadVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadVideoRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{10}
}

func (x *UploadVideoRequest) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *UploadVideoRequest) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *UploadVideoRequest) GetThumbData() []byte {
	if x != nil {
		return x.ThumbData
	}
	return nil
}

func (x *UploadVideoRequest) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

// UploadMomentsVideoRequest CDN 上传朋友圈视频请求
type UploadMomentsVideoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VideoData     []byte                 `protobuf:"bytes,1,opt,name=video_data,json=videoData,proto3" json:"video_data,omitempty"` // 视频二进制数据
	ThumbData     []byte                 `protobuf:"bytes,2,opt,name=thumb_data,json=thumbData,proto3" json:"thumb_data,omitempty"` // 缩略图二进制数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMomentsVideoRequest) Reset() {
	*x = UploadMomentsVideoRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMomentsVideoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMomentsVideoRequest) ProtoMessage() {}

func (x *UploadMomentsVideoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMomentsVideoRequest.ProtoReflect.Descriptor instead.
func (*UploadMomentsVideoRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{11}
}

func (x *UploadMomentsVideoRequest) GetVideoData() []byte {
	if x != nil {
		return x.VideoData
	}
	return nil
}

func (x *UploadMomentsVideoRequest) GetThumbData() []byte {
	if x != nil {
		return x.ThumbData
	}
	return nil
}

// GetDnsRequest 获取 CDN DNS 信息请求
type GetDnsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDnsRequest) Reset() {
	*x = GetDnsRequest{}
	mi := &file_api_cdn_cdn_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDnsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDnsRequest) ProtoMessage() {}

func (x *GetDnsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_cdn_cdn_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDnsRequest.ProtoReflect.Descriptor instead.
func (*GetDnsRequest) Descriptor() ([]byte, []int) {
	return file_api_cdn_cdn_api_proto_rawDescGZIP(), []int{12}
}

var File_api_cdn_cdn_api_proto protoreflect.FileDescriptor

const file_api_cdn_cdn_api_proto_rawDesc = "" +
	"\n" +
	"\x15api/cdn/cdn_api.proto\x12\aapi.cdn\"\xfc\x02\n" +
	"\x11UploadImageResult\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1c\n" +
	"\n" +
	"new_msg_id\x18\x03 \x01(\x04R\bnewMsgId\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\rR\n" +
	"createTime\x12\x1b\n" +
	"\tfile_size\x18\x05 \x01(\rR\bfileSize\x12\x19\n" +
	"\bfile_md5\x18\x06 \x01(\tR\afileMd5\x12\x1d\n" +
	"\n" +
	"file_width\x18\a \x01(\rR\tfileWidth\x12\x1f\n" +
	"\vfile_height\x18\b \x01(\rR\n" +
	"fileHeight\x12\x1d\n" +
	"\n" +
	"thumb_size\x18\t \x01(\rR\tthumbSize\x12\x1b\n" +
	"\tthumb_md5\x18\n" +
	" \x01(\tR\bthumbMd5\x12\x1f\n" +
	"\vthumb_width\x18\v \x01(\rR\n" +
	"thumbWidth\x12!\n" +
	"\fthumb_height\x18\f \x01(\rR\vthumbHeight\"\xc8\x01\n" +
	"\x14UploadSnsImageResult\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tthumb_url\x18\x02 \x01(\tR\bthumbUrl\x12\x19\n" +
	"\bfile_key\x18\x03 \x01(\tR\afileKey\x12\x19\n" +
	"\bfile_md5\x18\x04 \x01(\tR\afileMd5\x12\x1f\n" +
	"\vimage_width\x18\x05 \x01(\rR\n" +
	"imageWidth\x12!\n" +
	"\fimage_height\x18\x06 \x01(\rR\vimageHeight\"\x9c\x01\n" +
	"\x11UploadVideoResult\x12\x17\n" +
	"\aaes_key\x18\x01 \x01(\tR\x06aesKey\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tfile_size\x18\x03 \x01(\rR\bfileSize\x12\x1d\n" +
	"\n" +
	"thumb_size\x18\x04 \x01(\rR\tthumbSize\x12\x19\n" +
	"\bfile_md5\x18\x05 \x01(\tR\afileMd5\"\x82\x01\n" +
	"\x14UploadSnsVideoResult\x12\x19\n" +
	"\bfile_url\x18\x01 \x01(\tR\afileUrl\x12\x1b\n" +
	"\tthumb_url\x18\x02 \x01(\tR\bthumbUrl\x12\x17\n" +
	"\afile_id\x18\x03 \x01(\tR\x06fileId\x12\x19\n" +
	"\bfile_key\x18\x04 \x01(\tR\afileKey\"H\n" +
	"\x14DownloadImageRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\tR\x06aesKey\"H\n" +
	"\x14DownloadVideoRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\tR\x06aesKey\"M\n" +
	"\x19DownloadVideoCoverRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\aaes_key\x18\x02 \x01(\tR\x06aesKey\"O\n" +
	"\x17DownloadSnsVideoRequest\x12\x1b\n" +
	"\tvideo_url\x18\x01 \x01(\tR\bvideoUrl\x12\x17\n" +
	"\aenc_key\x18\x02 \x01(\x04R\x06encKey\"D\n" +
	"\x12UploadImageRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"/\n" +
	"\x19UploadMomentsImageRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\x8a\x01\n" +
	"\x12UploadVideoRequest\x12\x1a\n" +
	"\breceiver\x18\x01 \x01(\tR\breceiver\x12\x1d\n" +
	"\n" +
	"video_data\x18\x02 \x01(\fR\tvideoData\x12\x1d\n" +
	"\n" +
	"thumb_data\x18\x03 \x01(\fR\tthumbData\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\rR\bduration\"Y\n" +
	"\x19UploadMomentsVideoRequest\x12\x1d\n" +
	"\n" +
	"video_data\x18\x01 \x01(\fR\tvideoData\x12\x1d\n" +
	"\n" +
	"thumb_data\x18\x02 \x01(\fR\tthumbData\"\x0f\n" +
	"\rGetDnsRequestB/Z-github.com/sbgayhub/golem/host/api/cdn;cdnapib\x06proto3"

var (
	file_api_cdn_cdn_api_proto_rawDescOnce sync.Once
	file_api_cdn_cdn_api_proto_rawDescData []byte
)

func file_api_cdn_cdn_api_proto_rawDescGZIP() []byte {
	file_api_cdn_cdn_api_proto_rawDescOnce.Do(func() {
		file_api_cdn_cdn_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_cdn_cdn_api_proto_rawDesc), len(file_api_cdn_cdn_api_proto_rawDesc)))
	})
	return file_api_cdn_cdn_api_proto_rawDescData
}

var file_api_cdn_cdn_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_cdn_cdn_api_proto_goTypes = []any{
	(*UploadImageResult)(nil),         // 0: api.cdn.UploadImageResult
	(*UploadSnsImageResult)(nil),      // 1: api.cdn.UploadSnsImageResult
	(*UploadVideoResult)(nil),         // 2: api.cdn.UploadVideoResult
	(*UploadSnsVideoResult)(nil),      // 3: api.cdn.UploadSnsVideoResult
	(*DownloadImageRequest)(nil),      // 4: api.cdn.DownloadImageRequest
	(*DownloadVideoRequest)(nil),      // 5: api.cdn.DownloadVideoRequest
	(*DownloadVideoCoverRequest)(nil), // 6: api.cdn.DownloadVideoCoverRequest
	(*DownloadSnsVideoRequest)(nil),   // 7: api.cdn.DownloadSnsVideoRequest
	(*UploadImageRequest)(nil),        // 8: api.cdn.UploadImageRequest
	(*UploadMomentsImageRequest)(nil), // 9: api.cdn.UploadMomentsImageRequest
	(*UploadVideoRequest)(nil),        // 10: api.cdn.UploadVideoRequest
	(*UploadMomentsVideoRequest)(nil), // 11: api.cdn.UploadMomentsVideoRequest
	(*GetDnsRequest)(nil),             // 12: api.cdn.GetDnsRequest
}
var file_api_cdn_cdn_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_cdn_cdn_api_proto_init() }
func file_api_cdn_cdn_api_proto_init() {
	if File_api_cdn_cdn_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_cdn_cdn_api_proto_rawDesc), len(file_api_cdn_cdn_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_cdn_cdn_api_proto_goTypes,
		DependencyIndexes: file_api_cdn_cdn_api_proto_depIdxs,
		MessageInfos:      file_api_cdn_cdn_api_proto_msgTypes,
	}.Build()
	File_api_cdn_cdn_api_proto = out.File
	file_api_cdn_cdn_api_proto_goTypes = nil
	file_api_cdn_cdn_api_proto_depIdxs = nil
}
